// warp-control.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "career.mode",
    "comms.delay",
    "spaceCenter.scene",
    "spaceCenter.state",
    "vessel.maneuver",
  ],
  optionalChannelFamilies: [],
  commands: ["time.setPaused", "time.setWarpIndex"],
} as const;
