// target-picker.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["system.bodies", "vessel.orbit"],
  optionalChannelFamilies: [],
  commands: ["vessel.target.clear", "vessel.target.set"],
} as const;
