//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface KerbcastCameraEntry
{
	cameraId?: number;
	partId?: number;
	cameraName?: string;
	partName?: string;
	partTitle?: string;
	vesselId?: string;
	supportsZoom?: boolean;
	supportsPan?: boolean;
	fieldOfView?: Value<"°">;
	fieldOfViewMinimum?: Value<"°">;
	fieldOfViewMaximum?: Value<"°">;
	panYaw?: Value<"°">;
	panPitch?: Value<"°">;
	panYawMinimum?: Value<"°">;
	panYawMaximum?: Value<"°">;
	panPitchMinimum?: Value<"°">;
	panPitchMaximum?: Value<"°">;
	isDockingCamera?: boolean;
	dockingPortNodeType?: string;
	dockingPortState?: string;
}
export interface KerbcastSetFieldOfViewArgs
{
	cameraId: number;
	fieldOfView: number;
}
export interface KerbcastSetPanArgs
{
	cameraId: number;
	yaw: number;
	pitch: number;
}
