//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.

import type {
  KerbcastCameraEntry,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "kerbcast.cameras": KerbcastCameraEntry[];
}

export const GENERATED_TOPIC_IDS = [
  "kerbcast.cameras",
] as const;
