// <auto-generated> Written by packages/app/scripts/bake-uplink-hash.ts. DO NOT EDIT.
//
// The sha256 of the client bundle the app's build emits for this Uplink. Empty
// means the DLL vouches for nothing: Manifest.ExpectedClientHash stays null and the
// loader records the mod-hash arm as pending (two-way index==bytes fallback).
//
// A non-empty value is held current by bakedClientHash.test.ts, because one that
// has fallen behind its client source refuses the real bundle on every load:
//   pnpm --filter @ksp-gonogo/app bake-uplink-hash GonogoKosUplink
namespace Gonogo.KosUplink
{
    internal static class ExpectedClientHash
    {
        public const string Value = "sha256-ed58ff9410bfe253fed2a2943fd5cf3b8ebea74e102e379e3b7a205f01a640a6";
    }
}
