// maneuver-planner.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "dv.stages",
    "dv.summary",
    "system.bodies",
    "system.frame",
    "vessel.flight",
    "vessel.identity",
    "vessel.maneuver",
    "vessel.orbit",
    "vessel.propulsion",
    "vessel.structure",
    "vessel.target",
  ],
  optionalChannelFamilies: [],
  commands: [
    "vessel.maneuver.add",
    "vessel.maneuver.remove",
    "vessel.maneuver.update",
  ],
} as const;
