//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface KosProcessorInfo
{
	coreId: number;
	tag?: string;
	hasBooted: boolean;
	bootFilePath?: string;
	processorMode: string;
	partName?: string;
}
export interface KosComputeStatus
{
	running: boolean;
	lastGoodAt?: Value<"s">;
	scriptError?: string;
	parseError?: string;
	paused: boolean;
}
export interface KosExecArgs
{
	coreId: number;
	scriptId: string;
}
export interface KosReEnableArgs
{
	scriptId: string;
}
export interface KosRunArgs
{
	coreId: number;
	requestId: string;
	command: string;
}
export interface KosRunResult
{
	coreId: number;
	requestId: string;
	fields?: { [key:string]: any };
	error?: string;
}
export interface KosTerminalFrame
{
	coreId: number;
	chunk: string;
	fullRepaint: boolean;
}
export interface KosTerminalOpenArgs
{
	coreId: number;
	leaseToken: string;
}
export interface KosKeystrokeArgs
{
	coreId: number;
	leaseToken: string;
	chars: string;
}
export interface KosTerminalResizeArgs
{
	coreId: number;
	leaseToken: string;
	cols: number;
	rows: number;
}
export interface KosTerminalCloseArgs
{
	coreId: number;
	leaseToken: string;
}
