//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/** Every token first-party payloads use (Sitrep.Contract.Units). */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "K"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "h"
  | "id"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete, and a typo in first-party
 * code is still caught at codegen time by the catalog check. The open arm
 * exists because a third-party Uplink CANNOT add to Sitrep.Contract.Units:
 * it is a const-string class compiled into the contract assembly. Closing
 * this union would therefore have meant an Uplink could never declare a
 * unit at all, which contradicts third parties being first-class.
 *
 * A consumer teaches the client what an unknown symbol MEANS by calling
 * registerUnit from @ksp-gonogo/ui-kit. Until it does, the value still
 * renders, bare and unscaled.
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/** Declared units for one payload shape, keyed by camelCased field name. */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "KosComputeStatus": {
    lastGoodAt: "ut",
    parseError: "text",
    paused: "flag",
    running: "flag",
    scriptError: "text",
  },
  "KosExecArgs": {
    coreId: "id",
    scriptId: "id",
  },
  "KosKeystrokeArgs": {
    chars: "text",
    coreId: "id",
    leaseToken: "id",
  },
  "KosProcessorInfo": {
    bootFilePath: "text",
    coreId: "id",
    hasBooted: "flag",
    partName: "text",
    processorMode: "text",
    tag: "text",
  },
  "KosReEnableArgs": {
    scriptId: "id",
  },
  "KosRunArgs": {
    command: "text",
    coreId: "id",
    requestId: "id",
  },
  "KosRunResult": {
    coreId: "id",
    error: "text",
    requestId: "id",
  },
  "KosTerminalCloseArgs": {
    coreId: "id",
    leaseToken: "id",
  },
  "KosTerminalFrame": {
    chunk: "text",
    coreId: "id",
    fullRepaint: "flag",
  },
  "KosTerminalOpenArgs": {
    coreId: "id",
    leaseToken: "id",
  },
  "KosTerminalResizeArgs": {
    cols: "count",
    coreId: "id",
    leaseToken: "id",
    rows: "count",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "kos.processors": {
    bootFilePath: "text",
    coreId: "id",
    hasBooted: "flag",
    partName: "text",
    processorMode: "text",
    tag: "text",
  },
};

/** The nested payload shape each complex field holds, by its interface name. */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * A field holding a LIST of a shape is recorded the same way; the element
 * is what a consumer indexes into, which is the same convention the topic
 * unit map already follows for an array Topic.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
};
