using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Sitrep.Core;
using Xunit;

namespace Sitrep.Core.Tests
{
    /// <summary>
    /// Conformance test for the C# <c>Archive</c> port's READ behavior against
    /// the TS-computed golden fixtures in
    /// <c>mod/golden-fixtures/archive.json</c>. The fixture is generated by
    /// running the REAL TS <c>Archive</c> in
    /// <c>mod/sitrep-server/src/archive.ts</c> over a set of scripted
    /// scenarios (`pnpm --filter @gonogo/sitrep-server gen:golden-fixtures`)
    /// — this test never hand-authors expected values, it only replays each
    /// scenario's ops against the C# port and asserts every
    /// <c>readAtVantage</c> op reproduces the recorded expected result.
    ///
    /// The C#-only <c>Snapshot</c>/<c>Restore</c> addition (for M5b
    /// quicksave) has no TS reference and is NOT exercised here — see
    /// <see cref="ArchiveSnapshotRestoreTests"/> for that round-trip proof.
    ///
    /// A scenario constructs one <c>Archive</c> then runs an ops list that
    /// interleaves mutations (<c>record</c>) with queries
    /// (<c>readAtVantage</c>) — each query op carries the <c>expected</c>
    /// value (an object or <c>null</c>) the TS instance actually returned at
    /// that point, so ordering (e.g. freeze-on-recession across successive
    /// reads) is preserved exactly.
    /// </summary>
    public class ArchiveGoldenFixtureTests
    {
        private static readonly string FixturePath = Path.Combine(
            AppContext.BaseDirectory, "golden-fixtures", "archive.json");

        public static IEnumerable<object[]> Scenarios()
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            var scenarios = new List<object[]>();
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                // Clone: the JsonDocument (and its elements) are invalidated
                // once this method returns and `doc` is disposed.
                scenarios.Add(new object[] { element.Clone() });
            }
            return scenarios;
        }

        [Theory]
        [MemberData(nameof(Scenarios))]
        public void MatchesTsReference(JsonElement scenario)
        {
            var archive = new Archive();
            var name = scenario.GetProperty("name").GetString();

            foreach (var op in scenario.GetProperty("ops").EnumerateArray())
            {
                var kind = op.GetProperty("op").GetString();
                switch (kind)
                {
                    case "record":
                        archive.Record(
                            op.GetProperty("topic").GetString()!,
                            ToClrValue(op.GetProperty("value")),
                            op.GetProperty("validAtUt").GetDouble());
                        break;

                    case "readAtVantage":
                    {
                        var topic = op.GetProperty("topic").GetString()!;
                        var vantage = op.GetProperty("vantage").GetString()!;
                        var delaySeconds = op.GetProperty("delaySeconds").GetDouble();
                        var nowUt = op.GetProperty("nowUt").GetDouble();

                        var actual = archive.ReadAtVantage(topic, vantage, delaySeconds, nowUt);
                        var expectedElement = op.GetProperty("expected");

                        if (expectedElement.ValueKind == JsonValueKind.Null)
                        {
                            Assert.True(
                                actual == null,
                                $"[{name}] readAtVantage({topic}, {vantage}, {delaySeconds}, {nowUt}) expected null but got {{ value: {actual?.Value}, validAt: {actual?.ValidAt} }}");
                        }
                        else
                        {
                            Assert.True(actual != null, $"[{name}] expected a sample but got null");
                            var expectedValue = ToClrValue(expectedElement.GetProperty("value"));
                            var expectedValidAt = expectedElement.GetProperty("validAt").GetDouble();

                            Assert.True(
                                Equals(expectedValue, actual!.Value.Value),
                                $"[{name}] readAtVantage({topic}, {vantage}, {delaySeconds}, {nowUt}) expected value {expectedValue} but got {actual.Value.Value}");
                            Assert.True(
                                expectedValidAt == actual.Value.ValidAt,
                                $"[{name}] readAtVantage({topic}, {vantage}, {delaySeconds}, {nowUt}) expected validAt {expectedValidAt} but got {actual.Value.ValidAt}");
                        }
                        break;
                    }

                    default:
                        throw new InvalidOperationException($"Unknown golden-fixture op: {kind}");
                }
            }
        }

        /// <summary>
        /// Converts a fixture-file <see cref="JsonElement"/> into the plain
        /// CLR value <c>Archive.Record</c> would be called with in production
        /// (double / string / bool / null) — matching the plain CLR value
        /// shape <see cref="Archive.Snapshot"/> / <see cref="Archive.Restore"/>
        /// copy as-is (no serialization involved on that path; see
        /// <c>ArchiveState</c>), so a value round-trips identically whether it
        /// arrives via this test's fixture parsing or via <c>Archive.Restore</c>.
        /// </summary>
        private static object? ToClrValue(JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.Null:
                    return null;
                case JsonValueKind.True:
                    return true;
                case JsonValueKind.False:
                    return false;
                case JsonValueKind.Number:
                    return element.GetDouble();
                case JsonValueKind.String:
                    return element.GetString();
                default:
                    return element.Clone();
            }
        }
    }
}
