using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Sitrep.Core;
using Xunit;

namespace Sitrep.Core.Tests
{
    /// <summary>
    /// Conformance test for the C# <c>ManualClock</c> port against the
    /// TS-computed golden fixtures in <c>mod/golden-fixtures/clock.json</c>.
    /// The fixture is generated by running the REAL TS <c>ManualClock</c> in
    /// <c>mod/sitrep-server/src/clock.ts</c> over a set of scripted scenarios
    /// (`pnpm --filter @ksp-gonogo/sitrep-server gen:golden-fixtures`) — this test
    /// never hand-authors the expected fired-order/now() values, it only
    /// replays each scenario's ops against the C# port and asserts it
    /// reproduces the recorded observable output.
    ///
    /// A scenario is a scripted sequence of ops against one clock instance:
    /// <c>schedule</c> (with an optional nested <c>onFire</c> list of further
    /// schedules issued re-entrantly when the callback fires — this is how the
    /// re-entrancy-safe-drain cases are expressed), <c>advanceTo</c>, and
    /// <c>cancel</c> (by the id of a previous <c>schedule</c> op). Callbacks
    /// are represented by string ids rather than real closures so the
    /// scenario round-trips through JSON.
    /// </summary>
    public class ClockGoldenFixtureTests
    {
        private static readonly string FixturePath = Path.Combine(
            AppContext.BaseDirectory, "golden-fixtures", "clock.json");

        public static IEnumerable<object[]> Scenarios()
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            var scenarios = new List<object[]>();
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                // Clone: the JsonDocument (and its elements) are invalidated
                // once this method returns and `doc` is disposed.
                scenarios.Add(new object[] { element.Clone() });
            }
            return scenarios;
        }

        [Theory]
        [MemberData(nameof(Scenarios))]
        public void MatchesTsReference(JsonElement scenario)
        {
            var startUt = scenario.TryGetProperty("startUt", out var startUtElement)
                ? startUtElement.GetDouble()
                : 0;

            var clock = new ManualClock(startUt);
            var fired = new List<string>();
            var cancelHandles = new Dictionary<string, Action>();

            foreach (var op in scenario.GetProperty("ops").EnumerateArray())
            {
                ApplyOp(clock, op, fired, cancelHandles);
            }

            var expected = scenario.GetProperty("expected");
            var expectedFired = expected.GetProperty("fired")
                .EnumerateArray()
                .Select(e => e.GetString()!)
                .ToList();
            var expectedNowAfter = expected.GetProperty("nowAfter").GetDouble();

            var name = scenario.GetProperty("name").GetString();
            Assert.True(
                expectedFired.SequenceEqual(fired),
                $"[{name}] expected fired order [{string.Join(", ", expectedFired)}] but got [{string.Join(", ", fired)}]");
            Assert.Equal(expectedNowAfter, clock.Now());
        }

        private static void ApplyOp(
            ManualClock clock,
            JsonElement op,
            List<string> fired,
            Dictionary<string, Action> cancelHandles)
        {
            var kind = op.GetProperty("op").GetString();
            switch (kind)
            {
                case "schedule":
                    IssueSchedule(clock, op, fired, cancelHandles);
                    break;
                case "advanceTo":
                    clock.AdvanceTo(op.GetProperty("ut").GetDouble());
                    break;
                case "cancel":
                {
                    var id = op.GetProperty("id").GetString()!;
                    if (!cancelHandles.TryGetValue(id, out var cancel))
                    {
                        throw new InvalidOperationException(
                            $"cancel op referenced unknown schedule id \"{id}\"");
                    }
                    cancel();
                    break;
                }
                default:
                    throw new InvalidOperationException($"Unknown golden-fixture op: {kind}");
            }
        }

        /// <summary>
        /// Issues one `schedule` op (and, recursively, its `onFire` children)
        /// against `clock` — mirrors the generator's `issueSchedule` on the TS
        /// side (`mod/golden-fixtures/gen/clock.gen.ts`).
        /// </summary>
        private static void IssueSchedule(
            ManualClock clock,
            JsonElement op,
            List<string> fired,
            Dictionary<string, Action> cancelHandles)
        {
            var id = op.GetProperty("id").GetString()!;
            var atUt = op.GetProperty("atUt").GetDouble();

            var cancel = clock.Schedule(atUt, () =>
            {
                fired.Add(id);
                if (op.TryGetProperty("onFire", out var onFireElement))
                {
                    foreach (var nested in onFireElement.EnumerateArray())
                    {
                        ApplyOp(clock, nested, fired, cancelHandles);
                    }
                }
            });
            cancelHandles[id] = cancel;
        }
    }
}
