using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Sitrep.Core;
using Xunit;

namespace Sitrep.Core.Tests
{
    /// <summary>
    /// Conformance test for the C# <c>Courier</c> port against the
    /// TS-computed golden fixtures in <c>mod/golden-fixtures/courier.json</c>.
    /// The fixture is generated by running the REAL TS <c>Courier</c> in
    /// <c>mod/sitrep-server/src/courier.ts</c> over a set of scripted
    /// scenarios (`pnpm --filter @gonogo/sitrep-server gen:golden-fixtures`)
    /// — this test never hand-authors the expected event log, it only
    /// replays each scenario's ops against the C# port and asserts it
    /// produces the exact same sequence of observable events (stream
    /// deliveries + command responses), in the exact order they fired,
    /// each carrying the same <c>validAt</c>/<c>deliveredAt</c>/<c>seq</c>.
    ///
    /// A scenario constructs one <c>Courier</c> wired to a fresh
    /// <c>ManualClock</c> + <c>StubNetwork</c>, then runs an ops list
    /// (<c>record</c>, <c>subscribeStream</c>, <c>unsubscribeStream</c>,
    /// <c>setCommandHandler</c>, <c>dispatchCommand</c>, <c>advanceTo</c>).
    /// Every stream delivery / command response callback the real TS
    /// instance actually observed is recorded, in firing order, as
    /// <c>expected.events</c> — including the subtle cases: delivery at
    /// its own captured fire-UT under a batched <c>advanceTo</c> (not a
    /// shared re-read of <c>now()</c>), subscribe-during-transit, and
    /// honest silence on an unreachable node.
    /// </summary>
    public class CourierGoldenFixtureTests
    {
        private static readonly string FixturePath = Path.Combine(
            AppContext.BaseDirectory, "golden-fixtures", "courier.json");

        public static IEnumerable<object[]> Scenarios()
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            var scenarios = new List<object[]>();
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                // Clone: the JsonDocument (and its elements) are invalidated
                // once this method returns and `doc` is disposed.
                scenarios.Add(new object[] { element.Clone() });
            }
            return scenarios;
        }

        private sealed class ActualEvent
        {
            public string Kind = string.Empty;
            public string? SubscribeId;
            public string? RequestId;
            public string? Topic;
            public object? Payload;
            public object? Result;
            public string Source = string.Empty;
            public string Vantage = string.Empty;
            public double ValidAt;
            public double DeliveredAt;
            public long Seq;
        }

        [Theory]
        [MemberData(nameof(Scenarios))]
        public void MatchesTsReference(JsonElement scenario)
        {
            var name = scenario.GetProperty("name").GetString();
            var network = BuildNetwork(scenario);
            var clock = new ManualClock();
            var courier = new Courier(clock, network);

            var actualEvents = new List<ActualEvent>();
            var unsubById = new Dictionary<string, Action>();

            foreach (var op in scenario.GetProperty("ops").EnumerateArray())
            {
                var kind = op.GetProperty("op").GetString();
                switch (kind)
                {
                    case "record":
                        courier.Record(
                            op.GetProperty("node").GetString()!,
                            op.GetProperty("topic").GetString()!,
                            ToClrValue(op.GetProperty("value")),
                            op.GetProperty("validAtUt").GetDouble());
                        break;

                    case "subscribeStream":
                    {
                        var id = op.GetProperty("id").GetString()!;
                        var node = op.GetProperty("node").GetString()!;
                        var topic = op.GetProperty("topic").GetString()!;
                        var vantage = op.GetProperty("vantage").GetString()!;
                        var unsub = courier.SubscribeStream(node, topic, vantage, msg =>
                        {
                            actualEvents.Add(new ActualEvent
                            {
                                Kind = "stream",
                                SubscribeId = id,
                                Topic = msg.Topic,
                                Payload = msg.Payload,
                                Source = msg.Meta.Source,
                                Vantage = msg.Meta.Vantage,
                                ValidAt = msg.Meta.ValidAt,
                                DeliveredAt = msg.Meta.DeliveredAt,
                                Seq = msg.Meta.Seq,
                            });
                        });
                        unsubById[id] = unsub;
                        break;
                    }

                    case "unsubscribeStream":
                    {
                        var id = op.GetProperty("id").GetString()!;
                        if (!unsubById.TryGetValue(id, out var unsub))
                        {
                            throw new InvalidOperationException(
                                $"unsubscribeStream op referenced unknown subscribeStream id \"{id}\"");
                        }
                        unsub();
                        break;
                    }

                    case "setCommandHandler":
                        courier.SetCommandHandler(DefaultCommandHandler);
                        break;

                    case "dispatchCommand":
                    {
                        var node = op.GetProperty("node").GetString()!;
                        var requestId = op.GetProperty("requestId").GetString()!;
                        var command = op.GetProperty("command").GetString()!;
                        var args = ToClrValue(op.GetProperty("args"));
                        var vantage = op.GetProperty("vantage").GetString()!;
                        courier.DispatchCommand(node, requestId, command, args, vantage, msg =>
                        {
                            actualEvents.Add(new ActualEvent
                            {
                                Kind = "command",
                                RequestId = msg.RequestId,
                                Result = msg.Result,
                                Source = msg.Meta.Source,
                                Vantage = msg.Meta.Vantage,
                                ValidAt = msg.Meta.ValidAt,
                                DeliveredAt = msg.Meta.DeliveredAt,
                                Seq = msg.Meta.Seq,
                            });
                        });
                        break;
                    }

                    case "advanceTo":
                        clock.AdvanceTo(op.GetProperty("ut").GetDouble());
                        break;

                    default:
                        throw new InvalidOperationException($"Unknown golden-fixture op: {kind}");
                }
            }

            var expectedEvents = scenario.GetProperty("expected").GetProperty("events");
            var expectedCount = expectedEvents.GetArrayLength();
            Assert.True(
                expectedCount == actualEvents.Count,
                $"[{name}] expected {expectedCount} events but got {actualEvents.Count}");

            var i = 0;
            foreach (var expected in expectedEvents.EnumerateArray())
            {
                var actual = actualEvents[i];
                var expectedKind = expected.GetProperty("kind").GetString();
                Assert.True(expectedKind == actual.Kind, $"[{name}] event[{i}] expected kind {expectedKind} but got {actual.Kind}");

                Assert.True(
                    expected.GetProperty("source").GetString() == actual.Source,
                    $"[{name}] event[{i}] source mismatch");
                Assert.True(
                    expected.GetProperty("vantage").GetString() == actual.Vantage,
                    $"[{name}] event[{i}] vantage mismatch");
                Assert.True(
                    expected.GetProperty("validAt").GetDouble() == actual.ValidAt,
                    $"[{name}] event[{i}] expected validAt {expected.GetProperty("validAt").GetDouble()} but got {actual.ValidAt}");
                Assert.True(
                    expected.GetProperty("deliveredAt").GetDouble() == actual.DeliveredAt,
                    $"[{name}] event[{i}] expected deliveredAt {expected.GetProperty("deliveredAt").GetDouble()} but got {actual.DeliveredAt}");
                Assert.True(
                    expected.GetProperty("seq").GetInt64() == actual.Seq,
                    $"[{name}] event[{i}] expected seq {expected.GetProperty("seq").GetInt64()} but got {actual.Seq}");

                if (expectedKind == "stream")
                {
                    Assert.True(
                        expected.GetProperty("subscribeId").GetString() == actual.SubscribeId,
                        $"[{name}] event[{i}] subscribeId mismatch");
                    Assert.True(
                        expected.GetProperty("topic").GetString() == actual.Topic,
                        $"[{name}] event[{i}] topic mismatch");
                    var expectedPayload = ToClrValue(expected.GetProperty("payload"));
                    Assert.True(
                        DeepEquals(expectedPayload, actual.Payload),
                        $"[{name}] event[{i}] expected payload {Describe(expectedPayload)} but got {Describe(actual.Payload)}");
                }
                else
                {
                    Assert.True(
                        expected.GetProperty("requestId").GetString() == actual.RequestId,
                        $"[{name}] event[{i}] requestId mismatch");
                    var expectedResult = ToClrValue(expected.GetProperty("result"));
                    Assert.True(
                        DeepEquals(expectedResult, actual.Result),
                        $"[{name}] event[{i}] expected result {Describe(expectedResult)} but got {Describe(actual.Result)}");
                }

                i++;
            }
        }

        /// <summary>
        /// The single fixed command handler every <c>setCommandHandler</c> op
        /// installs — mirrors the TS generator's <c>defaultCommandHandler</c>
        /// in <c>mod/golden-fixtures/gen/courier.gen.ts</c>.
        /// </summary>
        private static object? DefaultCommandHandler(string command, object? args, string node)
        {
            return new Dictionary<string, object?>
            {
                ["ok"] = command,
                ["args"] = args,
                ["node"] = node,
            };
        }

        private static StubNetwork BuildNetwork(JsonElement scenario)
        {
            double? delay = null;
            bool? reachable = null;
            double scale = 1;

            if (scenario.TryGetProperty("network", out var networkElement))
            {
                if (networkElement.TryGetProperty("defaults", out var defaultsElement))
                {
                    if (defaultsElement.TryGetProperty("delay", out var delayElement))
                    {
                        delay = delayElement.GetDouble();
                    }
                    if (defaultsElement.TryGetProperty("reachable", out var reachableElement))
                    {
                        reachable = reachableElement.GetBoolean();
                    }
                }
                if (networkElement.TryGetProperty("scale", out var scaleElement))
                {
                    scale = scaleElement.GetDouble();
                }

                var network = new StubNetwork(delay, reachable, scale);

                if (networkElement.TryGetProperty("setDelay", out var setDelayElement))
                {
                    foreach (var entry in setDelayElement.EnumerateArray())
                    {
                        network.SetDelay(
                            entry.GetProperty("vantage").GetString()!,
                            entry.GetProperty("node").GetString()!,
                            entry.GetProperty("seconds").GetDouble());
                    }
                }
                if (networkElement.TryGetProperty("setReachable", out var setReachableElement))
                {
                    foreach (var entry in setReachableElement.EnumerateArray())
                    {
                        network.SetReachable(
                            entry.GetProperty("vantage").GetString()!,
                            entry.GetProperty("node").GetString()!,
                            entry.GetProperty("ok").GetBoolean());
                    }
                }

                return network;
            }

            return new StubNetwork(delay, reachable, scale);
        }

        /// <summary>
        /// Converts a fixture-file <see cref="JsonElement"/> into the plain
        /// CLR value shape production code would pass/receive (double /
        /// string / bool / null / <see cref="Dictionary{TKey, TValue}"/> /
        /// <see cref="List{T}"/>), recursively — unlike the scalar-only
        /// converters in the other golden-fixture tests, <c>Courier</c>'s
        /// command args/results are structured objects (e.g. <c>{ ok, args,
        /// node }</c>), so object/array values need a real recursive
        /// conversion rather than falling back to an opaque
        /// <see cref="JsonElement"/> clone.
        /// </summary>
        private static object? ToClrValue(JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.Null:
                case JsonValueKind.Undefined:
                    return null;
                case JsonValueKind.True:
                    return true;
                case JsonValueKind.False:
                    return false;
                case JsonValueKind.Number:
                    return element.GetDouble();
                case JsonValueKind.String:
                    return element.GetString();
                case JsonValueKind.Object:
                {
                    var dict = new Dictionary<string, object?>();
                    foreach (var property in element.EnumerateObject())
                    {
                        dict[property.Name] = ToClrValue(property.Value);
                    }
                    return dict;
                }
                case JsonValueKind.Array:
                {
                    var list = new List<object?>();
                    foreach (var item in element.EnumerateArray())
                    {
                        list.Add(ToClrValue(item));
                    }
                    return list;
                }
                default:
                    return null;
            }
        }

        /// <summary>
        /// Structural equality for the plain CLR value shapes
        /// <see cref="ToClrValue"/> produces and <c>Courier</c>'s command
        /// handler returns — needed because <see cref="Dictionary{TKey, TValue}"/>
        /// has no built-in structural <c>Equals</c>.
        /// </summary>
        private static bool DeepEquals(object? expected, object? actual)
        {
            if (expected is null || actual is null)
            {
                return expected is null && actual is null;
            }

            if (expected is Dictionary<string, object?> expectedDict)
            {
                if (actual is not Dictionary<string, object?> actualDict || expectedDict.Count != actualDict.Count)
                {
                    return false;
                }
                foreach (var (key, value) in expectedDict)
                {
                    if (!actualDict.TryGetValue(key, out var actualValue) || !DeepEquals(value, actualValue))
                    {
                        return false;
                    }
                }
                return true;
            }

            if (expected is List<object?> expectedList)
            {
                if (actual is not List<object?> actualList || expectedList.Count != actualList.Count)
                {
                    return false;
                }
                for (var i = 0; i < expectedList.Count; i++)
                {
                    if (!DeepEquals(expectedList[i], actualList[i]))
                    {
                        return false;
                    }
                }
                return true;
            }

            return expected.Equals(actual);
        }

        private static string Describe(object? value)
        {
            return value switch
            {
                null => "null",
                Dictionary<string, object?> dict => "{" + string.Join(", ", dict.Select(kv => $"{kv.Key}: {Describe(kv.Value)}")) + "}",
                List<object?> list => "[" + string.Join(", ", list.Select(Describe)) + "]",
                _ => value.ToString() ?? "null",
            };
        }
    }
}
