using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Sitrep.Contract;
using Sitrep.Core.Serialization;
using Xunit;

namespace Sitrep.Core.Tests
{
    /// <summary>
    /// Conformance test for <c>Sitrep.Core.Serialization.EnvelopeCodec</c>
    /// (the hand-written, dependency-free envelope JSON writer/reader —
    /// Task 7 of the M5a C# port) against the TS-computed golden fixtures in
    /// <c>mod/golden-fixtures/serialization.json</c>. The fixture is
    /// generated by the real TS SDK types plus <c>JSON.stringify</c> (with
    /// the NaN/Infinity sentinel policy applied via a replacer — see
    /// <c>mod/golden-fixtures/gen/serialization.gen.ts</c>), never
    /// hand-authored.
    ///
    /// Each vector's <c>json</c> string is parsed with the matching
    /// <c>EnvelopeCodec.Parse*</c> method and re-serialized with the
    /// matching <c>Write*</c> method; asserting the result is
    /// BYTE-FOR-BYTE IDENTICAL to the original proves two things at once:
    /// the C# reader correctly interprets what TS wrote, and the C# writer
    /// produces the exact same on-wire shape TS does for the same message
    /// (field order, optional-field omission, and NaN/Infinity sentinel
    /// encoding all included). Only <c>System.Text.Json</c> (available to
    /// this net10.0 test project, unlike BCL-only <c>Sitrep.Core</c>) is
    /// used to load the fixture file itself — never to touch envelope
    /// bytes, which is what's actually under test.
    /// </summary>
    public class EnvelopeSerializationGoldenFixtureTests
    {
        private static readonly string FixturePath = Path.Combine(
            AppContext.BaseDirectory, "golden-fixtures", "serialization.json");

        public static IEnumerable<object[]> Vectors()
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            var vectors = new List<object[]>();
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                vectors.Add(new object[] { element.Clone() });
            }
            return vectors;
        }

        [Theory]
        [MemberData(nameof(Vectors))]
        public void RoundTripsToTheExactSameWireShapeAsTs(JsonElement vector)
        {
            var name = vector.GetProperty("name").GetString();
            var kind = vector.GetProperty("kind").GetString();
            var wireJson = vector.GetProperty("json").GetString()!;

            var roundTripped = kind switch
            {
                "meta" => EnvelopeCodec.WriteMeta(EnvelopeCodec.ParseMeta(wireJson)),
                "streamData" => EnvelopeCodec.WriteStreamData(EnvelopeCodec.ParseStreamData(wireJson)),
                "eventMsg" => EnvelopeCodec.WriteEventMsg(EnvelopeCodec.ParseEventMsg(wireJson)),
                "commandRequest" => EnvelopeCodec.WriteCommandRequest(EnvelopeCodec.ParseCommandRequest(wireJson)),
                "commandResponse" => EnvelopeCodec.WriteCommandResponse(EnvelopeCodec.ParseCommandResponse(wireJson)),
                "errorMsg" => EnvelopeCodec.WriteErrorMsg(EnvelopeCodec.ParseErrorMsg(wireJson)),
                "subscribe" => EnvelopeCodec.WriteSubscribe(EnvelopeCodec.ParseSubscribe(wireJson)),
                "unsubscribe" => EnvelopeCodec.WriteUnsubscribe(EnvelopeCodec.ParseUnsubscribe(wireJson)),
                _ => throw new InvalidOperationException($"Unknown golden-fixture kind: {kind}"),
            };

            Assert.True(
                wireJson == roundTripped,
                $"[{name}] round trip mismatch:\n  original: {wireJson}\n  produced: {roundTripped}");
        }

        [Fact]
        public void MetaNanInfinityFixtureDecodesToRealNonFiniteDoubles()
        {
            var vector = FindVector("meta-nan-infinity");
            var meta = EnvelopeCodec.ParseMeta(vector.GetProperty("json").GetString()!);

            Assert.True(double.IsNaN(meta.ValidAt), "validAt should decode to NaN");
            Assert.True(double.IsPositiveInfinity(meta.DeliveredAt), "deliveredAt should decode to +Infinity");
            Assert.True(meta.Confidence.HasValue, "confidence should be present");
            Assert.True(double.IsNegativeInfinity(meta.Confidence!.Value), "confidence should decode to -Infinity");
        }

        [Fact]
        public void MetaNoConfidenceFixtureLeavesConfidenceNullRatherThanZeroOrNaN()
        {
            var vector = FindVector("meta-no-confidence");
            var meta = EnvelopeCodec.ParseMeta(vector.GetProperty("json").GetString()!);

            Assert.Null(meta.Confidence);
        }

        [Fact]
        public void StreamDataNanPayloadDecodesNestedSentinelsUniformly()
        {
            var vector = FindVector("stream-data-nan-payload");
            var msg = EnvelopeCodec.ParseStreamData(vector.GetProperty("json").GetString()!);

            var payload = Assert.IsType<Dictionary<string, object?>>(msg.Payload);
            Assert.True(double.IsNaN(Assert.IsType<double>(payload["eccentricAnomaly"])));
            Assert.True(double.IsPositiveInfinity(Assert.IsType<double>(payload["apoapsis"])));
        }

        [Fact]
        public void ParseServerMessageDispatchesOnTypeDiscriminant()
        {
            var streamJson = FindVector("stream-data-number").GetProperty("json").GetString()!;
            Assert.IsType<StreamData<object?>>(EnvelopeCodec.ParseServerMessage(streamJson));

            var eventJson = FindVector("event-msg").GetProperty("json").GetString()!;
            Assert.IsType<EventMsg>(EnvelopeCodec.ParseServerMessage(eventJson));

            var responseJson = FindVector("command-response").GetProperty("json").GetString()!;
            Assert.IsType<CommandResponse<object?>>(EnvelopeCodec.ParseServerMessage(responseJson));

            var errorJson = FindVector("error-msg-full").GetProperty("json").GetString()!;
            Assert.IsType<ErrorMsg>(EnvelopeCodec.ParseServerMessage(errorJson));
        }

        [Fact]
        public void ParseClientMessageDispatchesOnTypeDiscriminant()
        {
            var subscribeJson = FindVector("subscribe").GetProperty("json").GetString()!;
            Assert.IsType<Subscribe>(EnvelopeCodec.ParseClientMessage(subscribeJson));

            var unsubscribeJson = FindVector("unsubscribe").GetProperty("json").GetString()!;
            Assert.IsType<Unsubscribe>(EnvelopeCodec.ParseClientMessage(unsubscribeJson));

            var requestJson = FindVector("command-request").GetProperty("json").GetString()!;
            Assert.IsType<CommandRequest<object?>>(EnvelopeCodec.ParseClientMessage(requestJson));
        }

        private static JsonElement FindVector(string name)
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                if (element.GetProperty("name").GetString() == name)
                {
                    return element.Clone();
                }
            }
            throw new InvalidOperationException($"No golden-fixture vector named \"{name}\".");
        }
    }
}
