using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Sitrep.Core;
using Xunit;
using Sitrep.Contract;

namespace Sitrep.Core.Tests
{
    /// <summary>
    /// Conformance test for the C# <c>Kernel</c> port against the
    /// TS-computed golden fixtures in <c>mod/golden-fixtures/kernel.json</c>.
    /// The fixture is generated by running the REAL TS <c>Kernel</c> in
    /// <c>mod/sitrep-kernel/src/registry.ts</c> over a set of scripted
    /// scenarios (`pnpm --filter @gonogo/sitrep-kernel gen:golden-fixtures`)
    /// — this test never hand-authors the expected active-providers /
    /// notices / activation order, it only replays each scenario's
    /// registration ops against the C# port, calls <c>Resolve()</c> once,
    /// and asserts it reproduces the recorded observable outcome.
    ///
    /// A scenario is a scripted sequence of <c>registerCapability</c> /
    /// <c>registerProvider</c> ops (registration only) against one
    /// <c>Kernel</c> instance, plus a single top-level <c>resolve</c> call.
    /// Since provider factories can't be serialized to JSON, each factory is
    /// replaced by a marker: a provider's factory returns its own <c>id</c>
    /// string, and a capability's vanilla factory (when
    /// <c>hasVanilla: true</c>) returns the literal marker
    /// <c>"vanilla"</c> — unambiguous because <c>activePerCapability</c> is
    /// keyed per capability. Every invoked factory also records its owning
    /// capability's id into a shared activation-order log (checked against
    /// <c>expected.activationOrder</c>), and a provider op's
    /// <c>queryDeps: true</c> makes its factory actually call
    /// <c>ctx.Query(dep)</c> for each declared dep, exercising the real
    /// dependency-satisfaction path.
    ///
    /// Either the scenario resolves successfully (`expected` carries
    /// `activationOrder` / `activePerCapability` / `notices`), or it records
    /// `expectedError` (one of the three kernel exception types) plus
    /// `activeAfterThrow` — a snapshot of every registered capability's
    /// active instances taken right after the catch, asserting the
    /// atomicity invariant: a throwing `Resolve()` must not have activated
    /// anything, anywhere.
    /// </summary>
    public class KernelGoldenFixtureTests
    {
        private static readonly string FixturePath = Path.Combine(
            AppContext.BaseDirectory, "golden-fixtures", "kernel.json");

        public static IEnumerable<object[]> Scenarios()
        {
            var json = File.ReadAllText(FixturePath);
            using var doc = JsonDocument.Parse(json);
            var scenarios = new List<object[]>();
            foreach (var element in doc.RootElement.EnumerateArray())
            {
                // Clone: the JsonDocument (and its elements) are invalidated
                // once this method returns and `doc` is disposed.
                scenarios.Add(new object[] { element.Clone() });
            }
            return scenarios;
        }

        [Theory]
        [MemberData(nameof(Scenarios))]
        public void MatchesTsReference(JsonElement scenario)
        {
            var name = scenario.GetProperty("name").GetString();
            var kernel = new Kernel();
            var activationOrder = new List<string>();

            foreach (var op in scenario.GetProperty("ops").EnumerateArray())
            {
                ApplyOp(kernel, op, activationOrder);
            }

            var resolveOptions = BuildResolveOptions(scenario.GetProperty("resolve"));

            if (scenario.TryGetProperty("expectedError", out var expectedErrorElement))
            {
                var expectedErrorName = expectedErrorElement.GetString();
                Exception? thrown = null;
                try
                {
                    kernel.Resolve(resolveOptions);
                }
                catch (Exception ex)
                {
                    thrown = ex;
                }

                Assert.True(
                    thrown != null,
                    $"[{name}] expected {expectedErrorName} to be thrown, but Resolve() succeeded");
                Assert.True(
                    thrown!.GetType().Name == expectedErrorName,
                    $"[{name}] expected {expectedErrorName} but got {thrown.GetType().Name}: {thrown.Message}");

                // Atomicity: a throwing Resolve() must not have activated
                // anything, anywhere — not just for the capability that
                // caused the throw.
                foreach (var prop in scenario.GetProperty("activeAfterThrow").EnumerateObject())
                {
                    var expectedActive = prop.Value.EnumerateArray().Select(e => e.GetString()).ToList();
                    var actualActive = kernel.Active(prop.Name).Select(v => (string?)v).ToList();
                    Assert.True(
                        expectedActive.SequenceEqual(actualActive),
                        $"[{name}] atomicity: expected \"{prop.Name}\" active " +
                        $"[{string.Join(", ", expectedActive)}] after throw but got [{string.Join(", ", actualActive)}]");
                }

                return;
            }

            var result = kernel.Resolve(resolveOptions);
            var expected = scenario.GetProperty("expected");

            var expectedActivationOrder = expected.GetProperty("activationOrder")
                .EnumerateArray().Select(e => e.GetString()).ToList();
            Assert.True(
                expectedActivationOrder.SequenceEqual(activationOrder),
                $"[{name}] expected activationOrder [{string.Join(", ", expectedActivationOrder)}] " +
                $"but got [{string.Join(", ", activationOrder)}]");

            foreach (var prop in expected.GetProperty("activePerCapability").EnumerateObject())
            {
                var expectedActive = prop.Value.EnumerateArray().Select(e => e.GetString()).ToList();
                var actualActive = kernel.Active(prop.Name).Select(v => (string?)v).ToList();
                Assert.True(
                    expectedActive.SequenceEqual(actualActive),
                    $"[{name}] capability \"{prop.Name}\": expected active [{string.Join(", ", expectedActive)}] " +
                    $"but got [{string.Join(", ", actualActive)}]");
            }

            var expectedNotices = expected.GetProperty("notices")
                .EnumerateArray()
                .Select(n => $"{n.GetProperty("capability").GetString()}|{n.GetProperty("kind").GetString()}")
                .ToList();
            var actualNotices = result.Notices.Select(n => $"{n.Capability}|{n.Kind}").ToList();
            Assert.True(
                expectedNotices.SequenceEqual(actualNotices),
                $"[{name}] expected notices [{string.Join(", ", expectedNotices)}] but got [{string.Join(", ", actualNotices)}]");
        }

        private static void ApplyOp(Kernel kernel, JsonElement op, List<string> activationOrder)
        {
            var kind = op.GetProperty("op").GetString();
            switch (kind)
            {
                case "registerCapability":
                {
                    var id = op.GetProperty("id").GetString()!;
                    var exclusive = op.GetProperty("exclusive").GetBoolean();
                    var spineCritical = op.TryGetProperty("spineCritical", out var scElement) && scElement.GetBoolean();
                    var hasVanilla = op.TryGetProperty("hasVanilla", out var hvElement) && hvElement.GetBoolean();

                    kernel.RegisterCapability(new CapabilityDescriptor
                    {
                        Id = id,
                        Exclusive = exclusive,
                        SpineCritical = spineCritical,
                        Vanilla = hasVanilla
                            ? (ProviderContext ctx) =>
                            {
                                activationOrder.Add(id);
                                return "vanilla";
                            }
                            : null,
                    });
                    break;
                }

                case "registerProvider":
                {
                    var capability = op.GetProperty("capability").GetString()!;
                    var id = op.GetProperty("id").GetString()!;
                    var isDefault = op.TryGetProperty("isDefault", out var isDefaultElement) && isDefaultElement.GetBoolean();
                    var priority = op.TryGetProperty("priority", out var priorityElement) ? priorityElement.GetDouble() : 0;
                    var queryDeps = op.TryGetProperty("queryDeps", out var queryDepsElement) && queryDepsElement.GetBoolean();

                    List<string>? deps = null;
                    if (op.TryGetProperty("deps", out var depsElement))
                    {
                        deps = depsElement.EnumerateArray().Select(e => e.GetString()!).ToList();
                    }

                    ProviderVersions? versions = null;
                    if (op.TryGetProperty("versions", out var versionsElement))
                    {
                        versions = new ProviderVersions
                        {
                            Self = versionsElement.GetProperty("self").GetString()!,
                            MinKernelVersion = versionsElement.TryGetProperty("minKernelVersion", out var minKvElement)
                                ? minKvElement.GetString()
                                : null,
                            TargetModVersionRange = versionsElement.TryGetProperty("targetModVersionRange", out var rangeElement)
                                ? new VersionRange
                                {
                                    Min = rangeElement.GetProperty("min").GetString()!,
                                    Max = rangeElement.TryGetProperty("max", out var maxElement) ? maxElement.GetString() : null,
                                }
                                : null,
                        };
                    }

                    kernel.RegisterProvider(new ProviderRegistration
                    {
                        Capability = capability,
                        Id = id,
                        IsDefault = isDefault,
                        Priority = priority,
                        Deps = deps,
                        Versions = versions,
                        Factory = (ProviderContext ctx) =>
                        {
                            activationOrder.Add(capability);
                            if (queryDeps && deps != null)
                            {
                                foreach (var dep in deps)
                                {
                                    ctx.Query<object?>(dep);
                                }
                            }
                            return id;
                        },
                    });
                    break;
                }

                default:
                    throw new InvalidOperationException($"Unknown golden-fixture op: {kind}");
            }
        }

        private static ResolveOptions BuildResolveOptions(JsonElement resolveElement)
        {
            var kernelVersion = resolveElement.GetProperty("kernelVersion").GetString()!;
            var modVersion = resolveElement.TryGetProperty("modVersion", out var modVersionElement)
                ? modVersionElement.GetString()
                : null;

            Dictionary<string, string>? preferences = null;
            if (resolveElement.TryGetProperty("preferences", out var preferencesElement))
            {
                preferences = new Dictionary<string, string>();
                foreach (var prop in preferencesElement.EnumerateObject())
                {
                    preferences[prop.Name] = prop.Value.GetString()!;
                }
            }

            return new ResolveOptions
            {
                KernelVersion = kernelVersion,
                ModVersion = modVersion,
                Preferences = preferences,
            };
        }
    }
}
