// space-center-status.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["career.mode"],
  optionalChannelFamilies: [],
  commands: ["career.facility.upgrade"],
} as const;
