/**
 * What the dev server says about Uplinks on startup.
 *
 * `pnpm dev` builds no Uplink client bundle: `gonogo-uplink-bundles` is
 * `apply: "build"`, so `public/uplinks/` holds whatever the last `pnpm build`
 * left there, which is usually nothing and occasionally something old. Neither
 * state announces itself, and both reach the operator as a quarantine reason
 * about something else entirely: an absent index as a JSON syntax error (the
 * dev server answers a missing path with the SPA shell, HTTP 200), and a stale
 * one as a per-Uplink contract MISMATCH, which blames ten Uplinks for one
 * out-of-date artifact.
 *
 * So the dev server says it once, at the terminal, where it can name the fix.
 */

import { existsSync, readFileSync } from "node:fs";

/** The app's live compat identity, read by the caller out of vite.config.ts. */
export interface HostCompat {
  apiVersion: string;
  uiKitVersion: string;
  contractMajor: number;
  contractMinor: number;
}

export interface DevNotice {
  level: "info" | "warn";
  message: string;
}

const PREVIEW =
  "Uplink widgets load only from a built tree: `pnpm --filter @ksp-gonogo/app build`, then `vite preview`.";

/**
 * As much of the on-disk index as this notice reads.
 *
 * Deliberately not `RegistryIndex`: that type describes an index the loader
 * accepted, and the whole subject here is a file that may be from another
 * build entirely. Every field is optional because an old one really can be
 * missing a field a newer build writes.
 */
interface BakedGates {
  apiVersion?: string;
  uiKitVersion?: string;
  contractMajor?: number;
  contractMinor?: number;
}

interface BakedIndex {
  generatedAt?: string;
  uplinks?: { id?: string; versions?: BakedGates[] }[];
}

/**
 * Whether the index beside the dev server describes THIS tree.
 *
 * Only the four gated fields are compared, because those are the four the
 * loader refuses on (`checkUplinkCompat`). A version or a bundle hash moving
 * is not by itself a reason to shout: the index is regenerated by any build
 * and a widget that loads is a widget that loads.
 */
function driftOf(entry: BakedGates, host: HostCompat): string | null {
  const baked = `${entry.contractMajor}.${entry.contractMinor}`;
  const live = `${host.contractMajor}.${host.contractMinor}`;
  if (baked !== live) return `contract ${baked}, this tree is ${live}`;
  if (entry.apiVersion !== host.apiVersion) {
    return `extension API ${entry.apiVersion}, this tree is ${host.apiVersion}`;
  }
  if (entry.uiKitVersion !== host.uiKitVersion) {
    return `ui-kit ${entry.uiKitVersion}, this tree is ${host.uiKitVersion}`;
  }
  return null;
}

export function uplinkDevNotices(
  registryPath: string,
  host: HostCompat,
): DevNotice[] {
  if (!existsSync(registryPath)) {
    return [
      {
        level: "warn",
        message: `No Uplink client bundles under public/uplinks/, and \`pnpm dev\` does not build any. Every Uplink will quarantine. ${PREVIEW}`,
      },
    ];
  }

  let index: BakedIndex;
  try {
    index = JSON.parse(readFileSync(registryPath, "utf-8"));
  } catch (err) {
    return [
      {
        level: "warn",
        message: `public/uplinks/registry.local.json could not be read (${
          err instanceof Error ? err.message : String(err)
        }). Delete public/uplinks/ and rebuild. ${PREVIEW}`,
      },
    ];
  }

  const uplinks = index.uplinks ?? [];
  const drifted = uplinks
    .map((u) => {
      const version = u.versions?.[0];
      const drift = version ? driftOf(version, host) : "no version line";
      return drift ? `${u.id} (${drift})` : null;
    })
    .filter((row): row is string => row !== null);

  const when = index.generatedAt ? ` (generated ${index.generatedAt})` : "";
  if (drifted.length > 0) {
    return [
      {
        level: "warn",
        message: `The Uplink bundles under public/uplinks/${when} are from an older build and will each quarantine as a version MISMATCH, which is about the artifact and not about the Uplink: ${drifted.join(", ")}. Rebuild them. ${PREVIEW}`,
      },
    ];
  }

  return [
    {
      level: "info",
      message: `${uplinks.length} Uplink bundle(s) under public/uplinks/${when}. \`pnpm dev\` does not rebuild them, and does not serve the import map they need, so a widget from one will not load here. ${PREVIEW}`,
    },
  ];
}
