// The Uplink Hub registry descriptor — the machine-readable index the loader
// resolves an Uplink client bundle from (design §4.1). Phase A reads a LOCAL
// fixture (public/uplinks/registry.local.json, generated by the vite bundle
// plugin) that resolves to the workspace build. The seam is deliberate: swapping
// to the real Hub is a different `registrySource` URL and nothing else — the
// shapes here mirror the published index schema exactly.

/** One published version line of an Uplink (both halves ship on one tag). */
export interface UplinkVersionDescriptor {
  /** The Uplink's single version line (DLL == client). */
  version: string;
  /** Advisory app-version floor (design §6.3.2) — warned on, not gated. */
  minAppVersion: string;
  /** GATE — the @ksp-gonogo extension-API surface the client was built against. */
  apiVersion: string;
  /** GATE — the @ksp-gonogo/ui-kit version. */
  uiKitVersion: string;
  /** GATE — mirrors the C# ContractVersion.Major stamp. */
  contractMajor: number;
  /** Where the client bundle is fetched from (opaque to the loader). */
  bundleUrl: string;
  /** H_index — sha256 of the client bundle, `sha256-<hex>` (design §3.3 row A). */
  integrity: string;
  /**
   * H_mod — the hash the mod bakes into its DLL and emits on system.uplinks
   * (design §3.3 row B). `null` until the mod ships it (Phase B two-pass build);
   * the three-way check degrades to the two-way index==bytes agreement meanwhile.
   */
  expectedClientHash?: string | null;
}

/** One Uplink's registry entry — id MUST match the mod's `[SitrepUplink("id")]`. */
export interface UplinkDescriptor {
  id: string;
  name: string;
  author: string;
  repo: string;
  versions: UplinkVersionDescriptor[];
}

/** The whole registry index. */
export interface RegistryIndex {
  generatedAt?: string;
  uplinks: UplinkDescriptor[];
}

/**
 * Where the registry index is read from. Phase A: a local URL under the app's own
 * public/. Phase D: a trusted https URL to the Hub repo's index. Same fetch, same
 * parse — only the URL changes, which is the whole point of the seam.
 */
export interface RegistrySource {
  url: string;
}

/** The Phase A local fixture, generated by the vite `gonogo-uplink-bundles` plugin. */
export function localRegistrySource(): RegistrySource {
  return { url: `${import.meta.env.BASE_URL}uplinks/registry.local.json` };
}

/**
 * The Hub-wizard's registry source. For now this is just the local fixture — the
 * seam is here so the wizard's setup-assist step has a stable call site to depend
 * on; swapping it to a real hosted Hub manifest URL (Phase D) is a one-line change
 * confined to this function.
 */
export function hubRegistrySource(): RegistrySource {
  return localRegistrySource();
}

/**
 * Fetch + parse the registry index over the given source. In Phase A this is the
 * app's own origin (trusted); in Phase D it is a trusted https metadata transport
 * (design §4.1 — untrusted PeerJS relay only ever carries bundle *bytes*, hashed
 * against this trusted index, never the index itself).
 */
export async function fetchRegistry(
  source: RegistrySource,
): Promise<RegistryIndex> {
  const res = await fetch(source.url, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(
      `registry fetch failed: HTTP ${res.status} for ${source.url}`,
    );
  }
  const json = (await res.json()) as RegistryIndex;
  if (!json || !Array.isArray(json.uplinks)) {
    throw new Error(`registry at ${source.url} is not a valid index`);
  }
  return json;
}
