//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface AeroState
{
	angleOfAttack?: Value<"°">;
	sideslip?: Value<"°">;
	stallFraction?: Value<"ratio">;
	liftCoefficient?: Value<"1">;
	dragCoefficient?: Value<"1">;
	liftToDragRatio?: Value<"1">;
	referenceArea?: Value<"m²">;
	liftForce?: Value<"kN">;
	dragForce?: Value<"kN">;
	indicatedAirspeed?: Value<"m/s">;
	equivalentAirspeed?: Value<"m/s">;
	terminalVelocity?: Value<"m/s">;
	ballisticCoefficient?: Value<"kg/m²">;
	specificExcessPower?: Value<"W/kg">;
	aeroModelValid?: boolean;
}
