/**
 * `gonogo-uplink.json`: one shape, one writer, whichever command produced it.
 *
 * ## Why this module exists
 *
 * Two commands wrote this filename and they wrote different files. `bundle`
 * emitted thirteen fields beside the bundle it had just built; `docs` emitted
 * nine beside the client, and nothing anywhere said which one the loader
 * honours. An author who ran both got two manifests and no way to tell them
 * apart by reading either. The operator's ruling was to promote `bundle`'s shape
 * and make `docs` an alias, so this is that shape and this is the only code that
 * builds it.
 *
 * It lives in the sdk because the sdk is the one package both writers can reach:
 * `bundle` runs from here, `docs` runs in `@ksp-gonogo/ui-kit`, and ui-kit
 * depends on the sdk while the sdk deliberately cannot depend back.
 *
 * ## Where each field comes from
 *
 * Three sources, and the split is the point:
 *
 *   - `uplink.json`, the author's DISTRIBUTION declaration (id, name, author,
 *     repo, minAppVersion), searched from the client up to three levels so a flat
 *     template and a monorepo both find it
 *   - the client's `package.json`, for the version it publishes under
 *   - the client's own REGISTRATIONS (id, name, version, description), which only
 *     a caller that has evaluated the bundle in a browser can read
 *
 * The last of those is why `bundle` and `docs` are not symmetric: `bundle` never
 * runs the client, so for `name` and `description` it carries forward what the
 * manifest already committed beside the client says. That file is generated by
 * `docs` and held current by `docs --check` in CI, so the value being carried is
 * checked by something, which is what makes carrying it honest rather than
 * hopeful.
 *
 * Node-only: it reads the filesystem, so it is a build-tooling subpath like
 * `./uplink-externals` and never reaches a shipped client bundle.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** The sidecar's name. Fixed: the loader derives its URL from the bundle's. */
export const UPLINK_MANIFEST_FILE = "gonogo-uplink.json";

/**
 * The Uplink as a DISTRIBUTION, from the `uplink.json` an author writes.
 *
 * Distinct from what the code declares: an id and a name appear in both, and
 * `buildUplinkManifest` refuses rather than picking when the two disagree.
 */
export interface UplinkDeclaration {
  id?: string;
  name?: string;
  author?: string;
  repo?: string;
  minAppVersion?: string;
  /**
   * The KSP mod this Uplink wraps, when it wraps one.
   *
   * Not part of the manifest: it says what the Uplink is FOR, which the generated
   * page prints and the loader has no use for.
   */
  mod?: { name?: string; builtAgainst?: string; tier?: string };
}

/** Every field `gonogo-uplink.json` carries, in the order it is written. */
export interface UplinkManifest {
  id: string;
  name: string;
  /** The client's own `defineUplinkClient` description, when it declares one. */
  description?: string;
  author: string;
  repo: string;
  version: string;
  minAppVersion: string;
  apiVersion: string;
  uiKitVersion: string;
  contractMajor: number;
  contractMinor: number;
  /**
   * Where the bundle sits RELATIVE to this file, which is the only thing either
   * writer can honestly say about it: the loader fetches the sidecar by stripping
   * the last segment off the bundle's own URL, so the two are always siblings and
   * an absolute URL here would be a claim about a host neither command knows.
   */
  bundleUrl: string;
  /**
   * `sha256-<hex>` of the bundle the author distributes.
   *
   * EMPTY when no bundle was named, which is every manifest committed to this
   * repo, and that is fail-closed rather than a hole: the loader hashes the bytes
   * it fetched and refuses on any mismatch, and no digest is ever the empty
   * string, so an unstamped manifest quarantines its Uplink every time. Both
   * writers say so on stderr when they write one.
   */
  integrity: string;
  sdkVersion: string;
}

/** What the client's registrations say, for a caller that has read them. */
export interface RegisteredIdentity {
  id: string;
  name: string;
  version: string;
  description?: string;
}

export interface UplinkManifestInputs {
  /** The Uplink's client package: the directory holding its `package.json`. */
  clientDir: string;
  /**
   * The registrations, when the caller evaluated the client. `docs` renders the
   * bundle in a browser and has them; `bundle` never runs the client and does
   * not.
   */
  registered?: RegisteredIdentity;
  /**
   * The compat numbers this Uplink was built against.
   *
   * An input rather than a read of this package's own constants, because the two
   * callers answer it differently on purpose: `docs` reads them out of the very
   * bundle whose registrations it just enumerated, so the manifest claims
   * something true about the code it describes.
   */
  compat: {
    apiVersion: string;
    uiKitVersion: string;
    contractMajor: number;
    contractMinor: number;
  };
  /** `sha256-<hex>` of the distributed bundle, or empty when none was named. */
  integrity: string;
}

/**
 * This package's own version, read off its manifest rather than imported from
 * `version.generated.ts`.
 *
 * The generated constant is the right source everywhere else and is the wrong
 * one here: this module is resolved as SOURCE inside the workspace, where Node
 * strips the types but does not redirect a `./x.js` specifier to `./x.ts`, so
 * importing it made every `gonogo-uplink docs` run fail with a module that
 * cannot be found. The package root is one level up from both `src/` and
 * `dist/`, so the same expression works from either.
 */
function sdkVersion(): string {
  const pkg = JSON.parse(
    readFileSync(join(import.meta.dirname, "..", "package.json"), "utf8"),
  ) as { version?: string };
  return pkg.version ?? "";
}

function readJsonFile(path: string, what: string): Record<string, unknown> {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
  } catch (err) {
    throw new Error(
      `${what} at ${path} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * The `uplink.json` beside both halves of the Uplink, or nothing.
 *
 * Searched upwards rather than required at a fixed path: the template is flat
 * and the operator's monorepo is not, so it is one level above a flat layout's
 * client and two above a monorepo's. Absent is normal for an Uplink that ships
 * inside the app's own repo and has no separate declaration.
 */
export function readUplinkDeclaration(
  clientDir: string,
): { path: string; declared: UplinkDeclaration } | undefined {
  let dir = clientDir;
  for (let up = 0; up < 3; up++) {
    const path = join(dir, "uplink.json");
    if (existsSync(path)) {
      return { path, declared: readJsonFile(path, "uplink.json") };
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return undefined;
}

/**
 * The manifest already committed beside the client, for the two fields only a
 * registration read can supply.
 *
 * `bundle` does not evaluate the client, so `name` and `description` would
 * otherwise be unavailable to it and the two commands would write different
 * files again. Nothing else is taken from here: every other field has a source
 * both writers can read for themselves.
 */
function committedSidecar(clientDir: string): Partial<UplinkManifest> {
  const path = join(clientDir, UPLINK_MANIFEST_FILE);
  if (!existsSync(path)) return {};
  return readJsonFile(path, UPLINK_MANIFEST_FILE) as Partial<UplinkManifest>;
}

/** Refuse rather than pick, when one fact is declared twice and disagrees. */
function agreed(
  field: string,
  declared: string | undefined,
  registered: string | undefined,
): void {
  if (declared === undefined || registered === undefined) return;
  if (declared === registered) return;
  throw new Error(
    `gonogo-uplink: uplink.json declares ${field} "${declared}" and this ` +
      `client's registration says "${registered}". The manifest can only claim ` +
      "one of them, so make them equal rather than leaving the two commands " +
      "that write it free to disagree.",
  );
}

/**
 * The manifest, from the files an Uplink already has.
 *
 * Deterministic: given the same client directory, declaration and compat block
 * it produces the same object every time, and `serialiseUplinkManifest` the same
 * bytes. Nothing here reads a clock, a build artifact or the environment.
 */
export function buildUplinkManifest(
  inputs: UplinkManifestInputs,
): UplinkManifest {
  const { clientDir, registered } = inputs;
  const declared = readUplinkDeclaration(clientDir)?.declared ?? {};
  const pkgPath = join(clientDir, "package.json");
  if (!existsSync(pkgPath)) {
    throw new Error(
      `gonogo-uplink: no package.json in ${clientDir}. The manifest reads the ` +
        "version an Uplink publishes under from it, so it cannot be written " +
        "from anywhere else.",
    );
  }
  const pkg = readJsonFile(pkgPath, "the client's package.json") as {
    version?: string;
    gonogo?: { minAppVersion?: string };
  };
  const carried = committedSidecar(clientDir);

  agreed("id", declared.id, registered?.id);
  agreed("name", declared.name, registered?.name);
  const id = declared.id ?? registered?.id ?? carried.id;
  if (!id) {
    throw new Error(
      "gonogo-uplink: nothing declares this Uplink's id. It comes from " +
        "`uplink.json` or from the client's own `defineUplinkClient`, and the " +
        "loader matches it against the roster, so it cannot be defaulted.",
    );
  }

  // The client's `defineUplinkClient({ version })` and the package's own version
  // are two statements of one fact, and the app compares what it reads here
  // against what the loaded bundle declares. Six Uplinks declared "0.0.0-dev"
  // against a published 0.0.1, under a TODO saying the BUILD would inject the
  // version from this manifest, which cannot work: the manifest is generated
  // from the declaration.
  if (
    pkg.version !== undefined &&
    registered !== undefined &&
    registered.version !== pkg.version
  ) {
    throw new Error(
      `gonogo-uplink: this client declares version "${registered.version}" ` +
        `through defineUplinkClient, and package.json says "${pkg.version}". ` +
        "The manifest can only claim one of them, and the app compares what it " +
        "reads here against what the loaded bundle declares. Make them equal " +
        "(the declaration in client/src/uplink.ts is the one to edit).",
    );
  }

  return {
    id,
    // The id is a fallback, not a name: an Uplink that names itself nowhere is
    // better shown as its id than as a plausible-looking invention.
    name: declared.name ?? registered?.name ?? carried.name ?? id,
    description: registered?.description ?? carried.description,
    // An Uplink that declares no author IS unknown, and an empty string says so
    // without claiming anything.
    author: declared.author ?? "",
    repo: declared.repo ?? "",
    version: pkg.version ?? registered?.version ?? "0.0.0",
    /*
     * The one gate field nothing can derive: it is a claim about the APP, and
     * only the author knows which app feature their Uplink needs. `uplink.json`
     * first, then `package.json`'s `gonogo.minAppVersion`; "0.0.0" means no
     * floor.
     */
    minAppVersion:
      declared.minAppVersion ?? pkg.gonogo?.minAppVersion ?? "0.0.0",
    apiVersion: inputs.compat.apiVersion,
    uiKitVersion: inputs.compat.uiKitVersion,
    contractMajor: inputs.compat.contractMajor,
    contractMinor: inputs.compat.contractMinor,
    bundleUrl: `${id}/${id}.client.js`,
    integrity: inputs.integrity,
    // The version of the tool that WROTE this file, which in both commands is
    // this package. Read here rather than passed in, so the two writers cannot
    // answer it differently.
    sdkVersion: sdkVersion(),
  };
}

/** The manifest's bytes: two-space JSON with a trailing newline, always. */
export function serialiseUplinkManifest(manifest: UplinkManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/**
 * What a writer says when it stamps an empty `integrity`.
 *
 * Here rather than at the one place that prints it, because it describes a FIELD
 * of this manifest: `bundle` hashes the file it just built and never needs it,
 * `docs` prints it whenever no `--bundle` was named, and a second writer of this
 * file should say the same sentence rather than invent its own.
 */
export const NO_BUNDLE_INTEGRITY_WARNING =
  "no bundle was named, so gonogo-uplink.json carries an EMPTY integrity and " +
  "the app will quarantine this Uplink with an integrity mismatch. That is " +
  "correct for a working copy: regenerate with `--bundle <the file you " +
  "distribute>` when you cut a release. It is deliberately NOT defaulted to " +
  "dist/, which holds a compiler output rather than the bundle a consumer " +
  "fetches.";
