//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, run by codegen).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// GENERATED_COMMAND_RAIL below carries the same reflection's answer to the two
// questions the delay rail asks of a command: whether anything answers it, and
// whether it rides signal delay. Both are DATA a client reads, so no consumer
// holds its own list of which commands are which. What a command IS on the
// rail's other two axes is derived: a dispatch is a point, and the direction
// is which map it came out of.
//
// WHAT THE COUNT COUNTS, because a grep gets it wrong. It is one entry per
// [SitrepCommand] ATTRIBUTE, not per tagged type: SetEnabledArgs alone carries
// six. Counting `AddCommandHandler` call sites instead misses the ones the
// engine registers directly; counting `const string \w*Command\w*` catches
// CommandCentreTopic, which is a Topic; counting the strings the bundled
// clients dispatch counts what a widget presses today rather than what the
// mod accepts, and gets a quarter of the answer. Read this file.
//
// THE TOPIC MAP'S DYNAMIC CAVEAT DOES NOT CARRY OVER. There is no such
// thing as a dynamic command. `AddCommandHandler` and
// `AddVantageCommandHandler` both refuse a command with no matching
// `CommandDeclaration` in the registering uplink's Manifest, and
// `ChannelEngine` dispatches by exact dictionary key with no prefix
// matching anywhere, so a per-subject write cannot BE a command id.
//
// The subject travels in the ARGS instead, which is the fact an author
// needs: `vessel.invokePartAction` is ONE command taking a `partId`, not one
// command per part, and `science.experiment.deploy` is one taking a
// `partId`, not one per instrument. A widget composes a topic string per
// subject and never composes a command string. An Uplink's own commands
// work the same way; see that Uplink's map for its examples.
//
// So every command a client can send is nameable before the game is running,
// and this map is that set as far as the [SitrepCommand] reflection reaches.
// What it does NOT prove is that every declared command is tagged: nothing
// checks a Manifest's `Command(...)` entries against the attributes, so one
// declared and handled without a tag would be dispatchable and absent here.

import type {
  ActivateStrategyArgs,
  AddManeuverNodeArgs,
  BodyStatesReply,
  BodyStatesRequest,
  CommandResult,
  CommandResultOf,
  CommcastGroupAddArgs,
  CommcastGroupOpenArgs,
  CommcastMessageAckArgs,
  CommcastMessageSendArgs,
  CommcastRadioTransmitArgs,
  CommcastSendReceipt,
  ContractActionArgs,
  DeactivateStrategyArgs,
  ExperimentActionArgs,
  FireCrewArgs,
  HireApplicantArgs,
  InvokePartActionArgs,
  LaunchArgs,
  NoCommandArgs,
  RemoveManeuverNodeArgs,
  RevertToEditorArgs,
  RotorReverseArgs,
  RotorSetBrakeArgs,
  RotorSetRpmLimitArgs,
  RotorSetTorqueLimitArgs,
  SaveSettingsArgs,
  ScetAlarmArmArgs,
  ScetAlarmDisarmArgs,
  ScienceTransmission,
  ServoSetAngleArgs,
  ServoSetEnabledArgs,
  ServoSetExtensionArgs,
  SetActionGroupArgs,
  SetControlAxesArgs,
  SetControlFrameArgs,
  SetEnabledArgs,
  SetFlyByWireArgs,
  SetPausedArgs,
  SetSasModeArgs,
  SetTargetArgs,
  SetThrottleArgs,
  SetWarpIndexArgs,
  SwitchVesselArgs,
  UnlockTechArgs,
  UpdateManeuverNodeArgs,
  UpgradeFacilityArgs,
  UplinkActionReply,
  UplinkCancelRequest,
  UplinkResendRequest,
  WriteModSettingArgs,
} from "./contract.js";

export interface GeneratedCommandArgsMap {
  /** Register an alarm with the simulation host, or replace one already registered under the same `ScetAlarmArmArgs.id`. */
  "alarm.scet.arm": ScetAlarmArmArgs;
  /** Forget the alarm with this id. */
  "alarm.scet.disarm": ScetAlarmDisarmArgs;
  /** Accept, decline or cancel a contract. */
  "career.contract.accept": ContractActionArgs;
  /** Accept, decline or cancel a contract. */
  "career.contract.cancel": ContractActionArgs;
  /** Accept, decline or cancel a contract. */
  "career.contract.decline": ContractActionArgs;
  /** Fire a hired kerbal, returning them to the applicant pool. */
  "career.crew.fire": FireCrewArgs;
  /** Hire an applicant into the crew roster. */
  "career.crew.hire": HireApplicantArgs;
  /** Raise a Space Center facility by one tier. */
  "career.facility.upgrade": UpgradeFacilityArgs;
  /** Activate a strategy at a chosen commitment. */
  "career.strategy.activate": ActivateStrategyArgs;
  /** Deactivate an active strategy. */
  "career.strategy.deactivate": DeactivateStrategyArgs;
  /** Unlock a tech node, spending its science cost. */
  "career.tech.unlock": UnlockTechArgs;
  /** Bring more centres into a group. */
  "commcast.group.add": CommcastGroupAddArgs;
  /** Start a group, a set of command centres sharing one thread for messages and radio. */
  "commcast.group.open": CommcastGroupOpenArgs;
  /** Tell a message's author it arrived. */
  "commcast.message.ack": CommcastMessageAckArgs;
  /** Say something to a group in text. */
  "commcast.message.send": CommcastMessageSendArgs;
  /** One batch of live push-to-talk audio, spoken to a group. */
  "commcast.radio.transmit": CommcastRadioTransmitArgs;
  /** Load a saved craft onto a launch site. */
  "ksp.launch": LaunchArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.recover": NoCommandArgs;
  /** Revert the flight back into the VAB or SPH. */
  "ksp.revertToEditor": RevertToEditorArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.revertToLaunch": NoCommandArgs;
  /** Switch the flight to another tracked vessel. */
  "ksp.switchVessel": SwitchVesselArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.toSpaceCenter": NoCommandArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.toTrackingStation": NoCommandArgs;
  /** Flips the rotor's spin direction. */
  "robotics.rotor.reverse": RotorReverseArgs;
  /** Set a rotor's brake strength. */
  "robotics.rotor.setBrake": RotorSetBrakeArgs;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.rotor.setLock": ServoSetEnabledArgs;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.rotor.setMotor": ServoSetEnabledArgs;
  /** Set a rotor's rpm cap. */
  "robotics.rotor.setRpmLimit": RotorSetRpmLimitArgs;
  /** Set a rotor's torque limit. */
  "robotics.rotor.setTorqueLimit": RotorSetTorqueLimitArgs;
  /** Drive a hinge or rotation servo to an angle. */
  "robotics.servo.setAngle": ServoSetAngleArgs;
  /** Drive a piston to an extension. */
  "robotics.servo.setExtension": ServoSetExtensionArgs;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.servo.setLock": ServoSetEnabledArgs;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.servo.setMotor": ServoSetEnabledArgs;
  /** Deploy or transmit a science experiment on a part. */
  "science.experiment.deploy": ExperimentActionArgs;
  /** Deploy or transmit a science experiment on a part. */
  "science.experiment.transmit": ExperimentActionArgs;
  /** Change one of a host mod's own settings through its Uplink, at once. */
  "settings.mod.write": WriteModSettingArgs;
  /** Apply the settings from one Save press together and write the settings file once. */
  "settings.save": SaveSettingsArgs;
  /** Ask where a body is at each of a list of instants. */
  "system.bodies.statesAt": BodyStatesRequest;
  /** Put the view in a different reference frame. */
  "system.frame.set": SetControlFrameArgs;
  /** Cancels a held or travelling command: its lane number alone, or it and every later number this centre had sent on the lane when it was pressed. */
  "system.uplink.cancel": UplinkCancelRequest;
  /** Sends a held or overdue command again in its own place on its lane: a new copy with the same lane number, which must arrive before the commands behind it stop waiting for it. */
  "system.uplink.resend": UplinkResendRequest;
  /** Pause or resume the game. */
  "time.setPaused": SetPausedArgs;
  /** Select a time-warp rate. */
  "time.setWarpIndex": SetWarpIndexArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setAbort": SetEnabledArgs;
  /** Set a numbered custom action group on or off. */
  "vessel.control.setActionGroup": SetActionGroupArgs;
  /** Drive the held control axes of the fly-by-wire override. */
  "vessel.control.setAxes": SetControlAxesArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setBrakes": SetEnabledArgs;
  /** Turn the fly-by-wire override on or off. */
  "vessel.control.setFlyByWire": SetFlyByWireArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setGear": SetEnabledArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setLights": SetEnabledArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setRcs": SetEnabledArgs;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setSas": SetEnabledArgs;
  /** Set the SAS mode to hold. */
  "vessel.control.setSasMode": SetSasModeArgs;
  /** Set the main throttle. */
  "vessel.control.setThrottle": SetThrottleArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "vessel.control.stage": NoCommandArgs;
  /** Fire one button of one part's right-click Part Action Window, the remote-control equivalent of the player clicking it in-game. */
  "vessel.invokePartAction": InvokePartActionArgs;
  /** Add a manoeuvre node. */
  "vessel.maneuver.add": AddManeuverNodeArgs;
  /** Delete a manoeuvre node. */
  "vessel.maneuver.remove": RemoveManeuverNodeArgs;
  /** Replace an existing node's time and delta-v. */
  "vessel.maneuver.update": UpdateManeuverNodeArgs;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "vessel.target.clear": NoCommandArgs;
  /** Set the active vessel's target. */
  "vessel.target.set": SetTargetArgs;
}

export interface GeneratedCommandReplyMap {
  /** Register an alarm with the simulation host, or replace one already registered under the same `ScetAlarmArmArgs.id`. */
  "alarm.scet.arm": CommandResult;
  /** Forget the alarm with this id. */
  "alarm.scet.disarm": CommandResult;
  /** Accept, decline or cancel a contract. */
  "career.contract.accept": CommandResult;
  /** Accept, decline or cancel a contract. */
  "career.contract.cancel": CommandResult;
  /** Accept, decline or cancel a contract. */
  "career.contract.decline": CommandResult;
  /** Fire a hired kerbal, returning them to the applicant pool. */
  "career.crew.fire": CommandResult;
  /** Hire an applicant into the crew roster. */
  "career.crew.hire": CommandResult;
  /** Raise a Space Center facility by one tier. */
  "career.facility.upgrade": CommandResult;
  /** Activate a strategy at a chosen commitment. */
  "career.strategy.activate": CommandResult;
  /** Deactivate an active strategy. */
  "career.strategy.deactivate": CommandResult;
  /** Unlock a tech node, spending its science cost. */
  "career.tech.unlock": CommandResult;
  /** Bring more centres into a group. */
  "commcast.group.add": CommandResult;
  /** Start a group, a set of command centres sharing one thread for messages and radio. */
  "commcast.group.open": CommandResult;
  /** Tell a message's author it arrived. */
  "commcast.message.ack": CommandResult;
  /** Say something to a group in text. */
  "commcast.message.send": CommcastSendReceipt;
  /** One batch of live push-to-talk audio, spoken to a group. */
  "commcast.radio.transmit": CommandResult;
  /** Load a saved craft onto a launch site. */
  "ksp.launch": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.recover": CommandResult;
  /** Revert the flight back into the VAB or SPH. */
  "ksp.revertToEditor": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.revertToLaunch": CommandResult;
  /** Switch the flight to another tracked vessel. */
  "ksp.switchVessel": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.toSpaceCenter": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "ksp.toTrackingStation": CommandResult;
  /** Flips the rotor's spin direction. */
  "robotics.rotor.reverse": CommandResult;
  /** Set a rotor's brake strength. */
  "robotics.rotor.setBrake": CommandResult;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.rotor.setLock": CommandResult;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.rotor.setMotor": CommandResult;
  /** Set a rotor's rpm cap. */
  "robotics.rotor.setRpmLimit": CommandResult;
  /** Set a rotor's torque limit. */
  "robotics.rotor.setTorqueLimit": CommandResult;
  /** Drive a hinge or rotation servo to an angle. */
  "robotics.servo.setAngle": CommandResult;
  /** Drive a piston to an extension. */
  "robotics.servo.setExtension": CommandResult;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.servo.setLock": CommandResult;
  /** Switch a robotics servo or rotor motor or lock on or off. */
  "robotics.servo.setMotor": CommandResult;
  /** Deploy or transmit a science experiment on a part. */
  "science.experiment.deploy": CommandResult;
  /** Deploy or transmit a science experiment on a part. */
  "science.experiment.transmit": CommandResultOf<ScienceTransmission>;
  /** Change one of a host mod's own settings through its Uplink, at once. */
  "settings.mod.write": CommandResult;
  /** Apply the settings from one Save press together and write the settings file once. */
  "settings.save": CommandResult;
  /** Ask where a body is at each of a list of instants. */
  "system.bodies.statesAt": BodyStatesReply;
  /** Put the view in a different reference frame. */
  "system.frame.set": CommandResult;
  /** Cancels a held or travelling command: its lane number alone, or it and every later number this centre had sent on the lane when it was pressed. */
  "system.uplink.cancel": UplinkActionReply;
  /** Sends a held or overdue command again in its own place on its lane: a new copy with the same lane number, which must arrive before the commands behind it stop waiting for it. */
  "system.uplink.resend": UplinkActionReply;
  /** Pause or resume the game. */
  "time.setPaused": CommandResult;
  /** Select a time-warp rate. */
  "time.setWarpIndex": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setAbort": CommandResult;
  /** Set a numbered custom action group on or off. */
  "vessel.control.setActionGroup": CommandResult;
  /** Drive the held control axes of the fly-by-wire override. */
  "vessel.control.setAxes": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setBrakes": CommandResult;
  /** Turn the fly-by-wire override on or off. */
  "vessel.control.setFlyByWire": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setGear": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setLights": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setRcs": CommandResult;
  /** Switch SAS, RCS, landing gear, brakes, lights or the abort group on or off. */
  "vessel.control.setSas": CommandResult;
  /** Set the SAS mode to hold. */
  "vessel.control.setSasMode": CommandResult;
  /** Set the main throttle. */
  "vessel.control.setThrottle": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "vessel.control.stage": CommandResultOf<number>;
  /** Fire one button of one part's right-click Part Action Window, the remote-control equivalent of the player clicking it in-game. */
  "vessel.invokePartAction": CommandResult;
  /** Add a manoeuvre node. */
  "vessel.maneuver.add": CommandResultOf<string>;
  /** Delete a manoeuvre node. */
  "vessel.maneuver.remove": CommandResult;
  /** Replace an existing node's time and delta-v. */
  "vessel.maneuver.update": CommandResult;
  /** Take no args: stage, clear the target, recover, revert to launch, or go to the Tracking Station or Space Center. */
  "vessel.target.clear": CommandResult;
  /** Set the active vessel's target. */
  "vessel.target.set": CommandResult;
}

/**
 * The same mapping as a RUNTIME value: command id -> the NAME of the type
 * its dispatch resolves with, spelled exactly as the interface above spells
 * it, `CommandResultOf<Payload>` envelope included.
 *
 * An interface is erased before a client runs, and a command reply arrives
 * carrying a requestId and nothing else, so the command that was dispatched
 * is the only route back to a type. Anything that has to treat a reply by
 * its declared shape, unit hydration first among them, reads this.
 */
export const GENERATED_COMMAND_REPLY_TYPES = {
  "alarm.scet.arm": "CommandResult",
  "alarm.scet.disarm": "CommandResult",
  "career.contract.accept": "CommandResult",
  "career.contract.cancel": "CommandResult",
  "career.contract.decline": "CommandResult",
  "career.crew.fire": "CommandResult",
  "career.crew.hire": "CommandResult",
  "career.facility.upgrade": "CommandResult",
  "career.strategy.activate": "CommandResult",
  "career.strategy.deactivate": "CommandResult",
  "career.tech.unlock": "CommandResult",
  "commcast.group.add": "CommandResult",
  "commcast.group.open": "CommandResult",
  "commcast.message.ack": "CommandResult",
  "commcast.message.send": "CommcastSendReceipt",
  "commcast.radio.transmit": "CommandResult",
  "ksp.launch": "CommandResult",
  "ksp.recover": "CommandResult",
  "ksp.revertToEditor": "CommandResult",
  "ksp.revertToLaunch": "CommandResult",
  "ksp.switchVessel": "CommandResult",
  "ksp.toSpaceCenter": "CommandResult",
  "ksp.toTrackingStation": "CommandResult",
  "robotics.rotor.reverse": "CommandResult",
  "robotics.rotor.setBrake": "CommandResult",
  "robotics.rotor.setLock": "CommandResult",
  "robotics.rotor.setMotor": "CommandResult",
  "robotics.rotor.setRpmLimit": "CommandResult",
  "robotics.rotor.setTorqueLimit": "CommandResult",
  "robotics.servo.setAngle": "CommandResult",
  "robotics.servo.setExtension": "CommandResult",
  "robotics.servo.setLock": "CommandResult",
  "robotics.servo.setMotor": "CommandResult",
  "science.experiment.deploy": "CommandResult",
  "science.experiment.transmit": "CommandResultOf<ScienceTransmission>",
  "settings.mod.write": "CommandResult",
  "settings.save": "CommandResult",
  "system.bodies.statesAt": "BodyStatesReply",
  "system.frame.set": "CommandResult",
  "system.uplink.cancel": "UplinkActionReply",
  "system.uplink.resend": "UplinkActionReply",
  "time.setPaused": "CommandResult",
  "time.setWarpIndex": "CommandResult",
  "vessel.control.setAbort": "CommandResult",
  "vessel.control.setActionGroup": "CommandResult",
  "vessel.control.setAxes": "CommandResult",
  "vessel.control.setBrakes": "CommandResult",
  "vessel.control.setFlyByWire": "CommandResult",
  "vessel.control.setGear": "CommandResult",
  "vessel.control.setLights": "CommandResult",
  "vessel.control.setRcs": "CommandResult",
  "vessel.control.setSas": "CommandResult",
  "vessel.control.setSasMode": "CommandResult",
  "vessel.control.setThrottle": "CommandResult",
  "vessel.control.stage": "CommandResultOf<number>",
  "vessel.invokePartAction": "CommandResult",
  "vessel.maneuver.add": "CommandResultOf<string>",
  "vessel.maneuver.remove": "CommandResult",
  "vessel.maneuver.update": "CommandResult",
  "vessel.target.clear": "CommandResult",
  "vessel.target.set": "CommandResult",
} as const satisfies Record<string, string>;

/**
 * What the delay rail needs to know about a command, as DATA: a client asks
 * this table rather than carrying a list of ids it recognises.
 */
export interface GeneratedCommandRail {
  /** Whether the dispatch resolves with anything, i.e. whether an ack comes back. */
  readonly replies: boolean;
  /**
   * Whether the host holds this command for the signal delay before running it,
   * off the same `[SitrepCommand(Delayed = ...)]` the host itself dispatches by.
   */
  readonly delayed: boolean;
  /**
   * The args field holding the UT this command acts at, off
   * `[SitrepCommand(ArriveBefore = ...)]`. A client refuses to send the command
   * when it would reach the craft at or after that UT. Absent for every other
   * command.
   */
  readonly arriveBefore?: string;
}

/**
 * The rail columns for every command above, keyed the same way.
 *
 * An Uplink's own commands come out of ITS map, and its client feeds them to
 * the SDK through `registerUplinkCommand`.
 *
 * `replies` reads `true` on every row here, and that is a finding rather than
 * a placeholder: `Sitrep.Contract/CommandResult.cs` rules that results are
 * always delivered, never a fire-and-forget void, so no declared command can
 * be unacked. The column exists because a client must READ that rather than
 * assume it; the day the contract declares a command that answers nothing,
 * this is where it says so.
 *
 * `delayed` is the mod's own dispatch decision, not a client-side opinion of
 * it. A `false` row runs the instant it arrives, so drawing it a countdown or
 * an in-flight queue entry would be a fiction about the operator's own order.
 */
export const GENERATED_COMMAND_RAIL = {
  "alarm.scet.arm": { replies: true, delayed: false },
  "alarm.scet.disarm": { replies: true, delayed: false },
  "career.contract.accept": { replies: true, delayed: true },
  "career.contract.cancel": { replies: true, delayed: true },
  "career.contract.decline": { replies: true, delayed: true },
  "career.crew.fire": { replies: true, delayed: true },
  "career.crew.hire": { replies: true, delayed: true },
  "career.facility.upgrade": { replies: true, delayed: true },
  "career.strategy.activate": { replies: true, delayed: true },
  "career.strategy.deactivate": { replies: true, delayed: true },
  "career.tech.unlock": { replies: true, delayed: true },
  "commcast.group.add": { replies: true, delayed: false },
  "commcast.group.open": { replies: true, delayed: false },
  "commcast.message.ack": { replies: true, delayed: false },
  "commcast.message.send": { replies: true, delayed: false },
  "commcast.radio.transmit": { replies: true, delayed: false },
  "ksp.launch": { replies: true, delayed: false },
  "ksp.recover": { replies: true, delayed: false },
  "ksp.revertToEditor": { replies: true, delayed: false },
  "ksp.revertToLaunch": { replies: true, delayed: false },
  "ksp.switchVessel": { replies: true, delayed: false },
  "ksp.toSpaceCenter": { replies: true, delayed: false },
  "ksp.toTrackingStation": { replies: true, delayed: false },
  "robotics.rotor.reverse": { replies: true, delayed: true },
  "robotics.rotor.setBrake": { replies: true, delayed: true },
  "robotics.rotor.setLock": { replies: true, delayed: true },
  "robotics.rotor.setMotor": { replies: true, delayed: true },
  "robotics.rotor.setRpmLimit": { replies: true, delayed: true },
  "robotics.rotor.setTorqueLimit": { replies: true, delayed: true },
  "robotics.servo.setAngle": { replies: true, delayed: true },
  "robotics.servo.setExtension": { replies: true, delayed: true },
  "robotics.servo.setLock": { replies: true, delayed: true },
  "robotics.servo.setMotor": { replies: true, delayed: true },
  "science.experiment.deploy": { replies: true, delayed: true },
  "science.experiment.transmit": { replies: true, delayed: true },
  "settings.mod.write": { replies: true, delayed: false },
  "settings.save": { replies: true, delayed: false },
  "system.bodies.statesAt": { replies: true, delayed: false },
  "system.frame.set": { replies: true, delayed: false },
  "system.uplink.cancel": { replies: true, delayed: false },
  "system.uplink.resend": { replies: true, delayed: false },
  "time.setPaused": { replies: true, delayed: false },
  "time.setWarpIndex": { replies: true, delayed: false },
  "vessel.control.setAbort": { replies: true, delayed: true },
  "vessel.control.setActionGroup": { replies: true, delayed: true },
  "vessel.control.setAxes": { replies: true, delayed: true },
  "vessel.control.setBrakes": { replies: true, delayed: true },
  "vessel.control.setFlyByWire": { replies: true, delayed: true },
  "vessel.control.setGear": { replies: true, delayed: true },
  "vessel.control.setLights": { replies: true, delayed: true },
  "vessel.control.setRcs": { replies: true, delayed: true },
  "vessel.control.setSas": { replies: true, delayed: true },
  "vessel.control.setSasMode": { replies: true, delayed: true },
  "vessel.control.setThrottle": { replies: true, delayed: true },
  "vessel.control.stage": { replies: true, delayed: true },
  "vessel.invokePartAction": { replies: true, delayed: true },
  "vessel.maneuver.add": { replies: true, delayed: true, arriveBefore: "ut" },
  "vessel.maneuver.remove": { replies: true, delayed: true },
  "vessel.maneuver.update": { replies: true, delayed: true, arriveBefore: "ut" },
  "vessel.target.clear": { replies: true, delayed: true },
  "vessel.target.set": { replies: true, delayed: true },
} as const satisfies Record<string, GeneratedCommandRail>;

export const GENERATED_COMMAND_IDS = [
  "alarm.scet.arm",
  "alarm.scet.disarm",
  "career.contract.accept",
  "career.contract.cancel",
  "career.contract.decline",
  "career.crew.fire",
  "career.crew.hire",
  "career.facility.upgrade",
  "career.strategy.activate",
  "career.strategy.deactivate",
  "career.tech.unlock",
  "commcast.group.add",
  "commcast.group.open",
  "commcast.message.ack",
  "commcast.message.send",
  "commcast.radio.transmit",
  "ksp.launch",
  "ksp.recover",
  "ksp.revertToEditor",
  "ksp.revertToLaunch",
  "ksp.switchVessel",
  "ksp.toSpaceCenter",
  "ksp.toTrackingStation",
  "robotics.rotor.reverse",
  "robotics.rotor.setBrake",
  "robotics.rotor.setLock",
  "robotics.rotor.setMotor",
  "robotics.rotor.setRpmLimit",
  "robotics.rotor.setTorqueLimit",
  "robotics.servo.setAngle",
  "robotics.servo.setExtension",
  "robotics.servo.setLock",
  "robotics.servo.setMotor",
  "science.experiment.deploy",
  "science.experiment.transmit",
  "settings.mod.write",
  "settings.save",
  "system.bodies.statesAt",
  "system.frame.set",
  "system.uplink.cancel",
  "system.uplink.resend",
  "time.setPaused",
  "time.setWarpIndex",
  "vessel.control.setAbort",
  "vessel.control.setActionGroup",
  "vessel.control.setAxes",
  "vessel.control.setBrakes",
  "vessel.control.setFlyByWire",
  "vessel.control.setGear",
  "vessel.control.setLights",
  "vessel.control.setRcs",
  "vessel.control.setSas",
  "vessel.control.setSasMode",
  "vessel.control.setThrottle",
  "vessel.control.stage",
  "vessel.invokePartAction",
  "vessel.maneuver.add",
  "vessel.maneuver.remove",
  "vessel.maneuver.update",
  "vessel.target.clear",
  "vessel.target.set",
] as const;
