//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// THIS IS NOT A LIST OF EVERY COMMAND ON THE WIRE, for the same reason the
// topic map is not one: a command in a DYNAMIC namespace is addressed per
// subject at runtime and has no tagged type to find. What is below is every
// command that can be named before the game is running.

import type {
  ActivateStrategyArgs,
  AddManeuverNodeArgs,
  CommandResult,
  CommandResultOf,
  ContractActionArgs,
  DeactivateStrategyArgs,
  ExperimentActionArgs,
  FireCrewArgs,
  HireApplicantArgs,
  InvokePartActionArgs,
  LaunchArgs,
  NoCommandArgs,
  RemoveManeuverNodeArgs,
  RepairOutcome,
  RepairPartArgs,
  RevertToEditorArgs,
  RotorReverseArgs,
  RotorSetValueArgs,
  SendManeuverPlanArgs,
  ServoSetEnabledArgs,
  ServoSetTargetArgs,
  SetActionGroupArgs,
  SetControlAxesArgs,
  SetControlFrameArgs,
  SetEnabledArgs,
  SetFlyByWireArgs,
  SetPausedArgs,
  SetSasModeArgs,
  SetSimulationDelayPolicyArgs,
  SetTargetArgs,
  SetThrottleArgs,
  SetWarpIndexArgs,
  SwitchVesselArgs,
  UnlockTechArgs,
  UpdateManeuverNodeArgs,
  UpgradeFacilityArgs,
  VantagePlanReply,
  VantagePlanRequest,
} from "./contract.js";

export interface GeneratedCommandArgsMap {
  "career.contract.accept": ContractActionArgs;
  "career.contract.cancel": ContractActionArgs;
  "career.contract.decline": ContractActionArgs;
  "career.crew.fire": FireCrewArgs;
  "career.crew.hire": HireApplicantArgs;
  "career.facility.upgrade": UpgradeFacilityArgs;
  "career.strategy.activate": ActivateStrategyArgs;
  "career.strategy.deactivate": DeactivateStrategyArgs;
  "career.tech.unlock": UnlockTechArgs;
  "comms.setSimulationDelayPolicy": SetSimulationDelayPolicyArgs;
  "ksp.launch": LaunchArgs;
  "ksp.recover": NoCommandArgs;
  "ksp.revertToEditor": RevertToEditorArgs;
  "ksp.revertToLaunch": NoCommandArgs;
  "ksp.switchVessel": SwitchVesselArgs;
  "ksp.toTrackingStation": NoCommandArgs;
  "robotics.rotor.reverse": RotorReverseArgs;
  "robotics.rotor.setBrake": RotorSetValueArgs;
  "robotics.rotor.setLock": ServoSetEnabledArgs;
  "robotics.rotor.setMotor": ServoSetEnabledArgs;
  "robotics.rotor.setRpmLimit": RotorSetValueArgs;
  "robotics.rotor.setTorqueLimit": RotorSetValueArgs;
  "robotics.servo.setLock": ServoSetEnabledArgs;
  "robotics.servo.setMotor": ServoSetEnabledArgs;
  "robotics.servo.setTarget": ServoSetTargetArgs;
  "science.experiment.deploy": ExperimentActionArgs;
  "science.experiment.transmit": ExperimentActionArgs;
  "system.frame.set": SetControlFrameArgs;
  "time.setPaused": SetPausedArgs;
  "time.setWarpIndex": SetWarpIndexArgs;
  "vessel.control.setAbort": SetEnabledArgs;
  "vessel.control.setActionGroup": SetActionGroupArgs;
  "vessel.control.setAxes": SetControlAxesArgs;
  "vessel.control.setBrakes": SetEnabledArgs;
  "vessel.control.setFlyByWire": SetFlyByWireArgs;
  "vessel.control.setGear": SetEnabledArgs;
  "vessel.control.setLights": SetEnabledArgs;
  "vessel.control.setRcs": SetEnabledArgs;
  "vessel.control.setSas": SetEnabledArgs;
  "vessel.control.setSasMode": SetSasModeArgs;
  "vessel.control.setThrottle": SetThrottleArgs;
  "vessel.control.stage": NoCommandArgs;
  "vessel.invokePartAction": InvokePartActionArgs;
  "vessel.maneuver.add": AddManeuverNodeArgs;
  "vessel.maneuver.plan.send": SendManeuverPlanArgs;
  "vessel.maneuver.remove": RemoveManeuverNodeArgs;
  "vessel.maneuver.update": UpdateManeuverNodeArgs;
  "vessel.repair": RepairPartArgs;
  "vessel.target.clear": NoCommandArgs;
  "vessel.target.set": SetTargetArgs;
  "vessel.trajectory.forVantage": VantagePlanRequest;
}

export interface GeneratedCommandReplyMap {
  "career.contract.accept": CommandResult;
  "career.contract.cancel": CommandResult;
  "career.contract.decline": CommandResult;
  "career.crew.fire": CommandResult;
  "career.crew.hire": CommandResult;
  "career.facility.upgrade": CommandResult;
  "career.strategy.activate": CommandResult;
  "career.strategy.deactivate": CommandResult;
  "career.tech.unlock": CommandResult;
  "comms.setSimulationDelayPolicy": CommandResult;
  "ksp.launch": CommandResult;
  "ksp.recover": CommandResult;
  "ksp.revertToEditor": CommandResult;
  "ksp.revertToLaunch": CommandResult;
  "ksp.switchVessel": CommandResult;
  "ksp.toTrackingStation": CommandResult;
  "robotics.rotor.reverse": CommandResult;
  "robotics.rotor.setBrake": CommandResult;
  "robotics.rotor.setLock": CommandResult;
  "robotics.rotor.setMotor": CommandResult;
  "robotics.rotor.setRpmLimit": CommandResult;
  "robotics.rotor.setTorqueLimit": CommandResult;
  "robotics.servo.setLock": CommandResult;
  "robotics.servo.setMotor": CommandResult;
  "robotics.servo.setTarget": CommandResult;
  "science.experiment.deploy": CommandResult;
  "science.experiment.transmit": CommandResult;
  "system.frame.set": CommandResult;
  "time.setPaused": CommandResult;
  "time.setWarpIndex": CommandResult;
  "vessel.control.setAbort": CommandResult;
  "vessel.control.setActionGroup": CommandResult;
  "vessel.control.setAxes": CommandResult;
  "vessel.control.setBrakes": CommandResult;
  "vessel.control.setFlyByWire": CommandResult;
  "vessel.control.setGear": CommandResult;
  "vessel.control.setLights": CommandResult;
  "vessel.control.setRcs": CommandResult;
  "vessel.control.setSas": CommandResult;
  "vessel.control.setSasMode": CommandResult;
  "vessel.control.setThrottle": CommandResult;
  "vessel.control.stage": CommandResultOf<number>;
  "vessel.invokePartAction": CommandResult;
  "vessel.maneuver.add": CommandResultOf<string>;
  "vessel.maneuver.plan.send": CommandResult;
  "vessel.maneuver.remove": CommandResult;
  "vessel.maneuver.update": CommandResult;
  "vessel.repair": CommandResultOf<RepairOutcome>;
  "vessel.target.clear": CommandResult;
  "vessel.target.set": CommandResult;
  "vessel.trajectory.forVantage": VantagePlanReply;
}

export const GENERATED_COMMAND_IDS = [
  "career.contract.accept",
  "career.contract.cancel",
  "career.contract.decline",
  "career.crew.fire",
  "career.crew.hire",
  "career.facility.upgrade",
  "career.strategy.activate",
  "career.strategy.deactivate",
  "career.tech.unlock",
  "comms.setSimulationDelayPolicy",
  "ksp.launch",
  "ksp.recover",
  "ksp.revertToEditor",
  "ksp.revertToLaunch",
  "ksp.switchVessel",
  "ksp.toTrackingStation",
  "robotics.rotor.reverse",
  "robotics.rotor.setBrake",
  "robotics.rotor.setLock",
  "robotics.rotor.setMotor",
  "robotics.rotor.setRpmLimit",
  "robotics.rotor.setTorqueLimit",
  "robotics.servo.setLock",
  "robotics.servo.setMotor",
  "robotics.servo.setTarget",
  "science.experiment.deploy",
  "science.experiment.transmit",
  "system.frame.set",
  "time.setPaused",
  "time.setWarpIndex",
  "vessel.control.setAbort",
  "vessel.control.setActionGroup",
  "vessel.control.setAxes",
  "vessel.control.setBrakes",
  "vessel.control.setFlyByWire",
  "vessel.control.setGear",
  "vessel.control.setLights",
  "vessel.control.setRcs",
  "vessel.control.setSas",
  "vessel.control.setSasMode",
  "vessel.control.setThrottle",
  "vessel.control.stage",
  "vessel.invokePartAction",
  "vessel.maneuver.add",
  "vessel.maneuver.plan.send",
  "vessel.maneuver.remove",
  "vessel.maneuver.update",
  "vessel.repair",
  "vessel.target.clear",
  "vessel.target.set",
  "vessel.trajectory.forVantage",
] as const;
