//     This code was generated by the Sitrep contract control-channel codegen
//     (Sitrep.Contract.RtConfig.EmitChannelMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepControlChannel]-tagged read property
// in Sitrep.Contract: the property's owning [SitrepTopic] is the read topic, the
// camelCased property name is the read field, and the attribute carries the
// paired write command + its typed args + the camelCased value field. Read and
// write stay two wire keys; the SDK unifies them into one handle (see
// ../control-channels.ts).

export interface GeneratedControlChannel {
  readonly id: string;
  readonly readTopic: string;
  readonly readField: string;
  readonly writeCommand: string;
  readonly argsType: string;
  readonly valueField: string;
}

export const GENERATED_CONTROL_CHANNELS = [
  { id: "vessel.control.pitch", readTopic: "vessel.control", readField: "pitch", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "pitch" },
  { id: "vessel.control.roll", readTopic: "vessel.control", readField: "roll", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "roll" },
  { id: "vessel.control.throttle", readTopic: "vessel.control", readField: "throttle", writeCommand: "vessel.control.setThrottle", argsType: "SetThrottleArgs", valueField: "value" },
  { id: "vessel.control.translationX", readTopic: "vessel.control", readField: "translationX", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "x" },
  { id: "vessel.control.translationY", readTopic: "vessel.control", readField: "translationY", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "y" },
  { id: "vessel.control.translationZ", readTopic: "vessel.control", readField: "translationZ", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "z" },
  { id: "vessel.control.yaw", readTopic: "vessel.control", readField: "yaw", writeCommand: "vessel.control.setAxes", argsType: "SetControlAxesArgs", valueField: "yaw" },
] as const satisfies readonly GeneratedControlChannel[];

export type GeneratedControlChannelId =
  (typeof GENERATED_CONTROL_CHANNELS)[number]["id"];
