//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

/**
 * One declared error code, as a client reads it.
 *
 * @category Error codes
 */
export interface ErrorCodeDeclaration {
  /** The camelCase id: one segment for a root or a fault, `owner.name` for a refinement. */
  readonly id: string;
  /** `refusal`: the game ran the command and said no. `fault`: nothing was decided, the request could not be carried. */
  readonly kind: "refusal" | "fault";
  /** The root a refinement refines; `null` on a root and on every fault. */
  readonly refines: string | null;
  /** Where a fault is minted; `null` on a refusal. */
  readonly origin: "mod" | "client" | null;
  /** What an operator reads after "refused:" or "failed:", lower case and without a full stop. */
  readonly sentence: string;
  /** What the code means, from its declaration's doc comment. Empty when that is not to hand. */
  readonly meaning: string;
}

/**
 * The root refusals: the closed set every client can switch over. Each says
 * what KIND of no it was, and so whether waiting, changing the craft, or doing
 * something in the game is what makes a retry mean anything.
 *
 * A producer that can say more names a refinement of one of these (see
 * `RefusalCode.Refine`); the root still travels, so nothing a client does with
 * a root depends on knowing the refinement.
 *
 * @category Error codes
 */
export const CommandErrorCode = {
  /**
   * No active vessel to act on.
   */
  NoVessel: "noVessel",
  /**
   * The requested mode or state is not available, and the game gave no more
   * specific reason.
   */
  ModeUnavailable: "modeUnavailable",
  /**
   * An argument was out of its valid range.
   */
  Range: "range",
  /**
   * The referenced entity (node id, vessel/body target) did not resolve.
   */
  NotFound: "notFound",
  /**
   * The elected maneuver-plan provider is not the one that reads stock's
   * `patchedConicSolver`, so a write there would never be seen.
   *
   * Refused rather than attempted, because attempting it produces a GHOST NODE:
   * we mutate stock's solver, the owning planner never reads it (an n-body
   * backend clears that list every frame and writes its own guidance node into
   * it), and the operator sees a maneuver node on the board that does precisely
   * nothing. A silent wrong answer with a confident presentation.
   *
   * The code says WHY, not WHO: the owner is already on the wire as
   * `VesselManeuver.Planner` for a readout to name.
   */
  PlanNotOwned: "planNotOwned",
  /**
   * A capacity is full: the Astronaut Complex holds its cap of active crew, a
   * facility holds its cap of anything else countable.
   *
   * The world has to change before a retry means anything; freeing a slot is a
   * thing an operator can actually do.
   *
   * The arm chooses the sentence, `CommandResult.breach` supplies the numbers in
   * it. Neither is worth sending without the other: a code with no payload
   * cannot say "16 of 16".
   */
  LimitReached: "limitReached",
  /**
   * Already at the top of an upgradeable scale, so there is nothing above this
   * to move to. The Launch Pad at tier 3 of 3.
   *
   * Deliberately NOT `CommandErrorCode.LimitReached`. A cap that is full can be
   * freed; a maximum tier cannot be exceeded by any action at all, and an
   * operator reads those two differently.
   */
  AlreadyAtMaximum: "alreadyAtMaximum",
  /**
   * The command costs more than the funds on hand.
   *
   * `CommandResult.breach` carries the cost as `Actual` against the balance as
   * `Limit`, so the client can say how short and in the operator's own currency
   * rendering.
   */
  InsufficientFunds: "insufficientFunds",
  /**
   * The command costs more science than is banked.
   * `CommandErrorCode.InsufficientFunds`'s twin, and separate for the same
   * reason the game keeps `Currency` as three members: an operator short of
   * science does something entirely different about it from one short of funds.
   *
   * Authority: `CurrencyModifierQuery.RunQuery(reason,
   * ...).CanAfford(Currency.Science)`, which is what `RDTech.ResearchTech` asks.
   * NOT `ResearchAndDevelopment.CanAfford`, which skips the modifier chain and
   * so answers a different question from the one the game acts on.
   */
  InsufficientScience: "insufficientScience",
  /**
   * The save is not a career save, so this command's whole subsystem does not
   * exist here.
   *
   * Authority: `HighLogic.CurrentGame.Mode`, and in practice the null `Instance`
   * of the `ScenarioModule` that would have answered (`Funding`,
   * `ContractSystem`, `StrategySystem`, `ResearchAndDevelopment`,
   * `ScenarioUpgradeableFacilities`).
   *
   * This is a PERMANENT property of the save, not a state that may change, which
   * is exactly what `CommandErrorCode.ModeUnavailable` could not say. An
   * operator should see the control absent rather than refused; a client that
   * can tell this arm from the others can do that.
   */
  CareerModeRequired: "careerModeRequired",
  /**
   * The game is in a scene this command cannot run from.
   *
   * Authority: `HighLogic.LoadedScene` (`GameScenes`). `CommandResult.detail`
   * names the scene when the producer had one.
   */
  WrongScene: "wrongScene",
  /**
   * The entity is not in a state this transition applies to: an already-active
   * strategy asked to activate, an already-researched node asked to unlock, a
   * contract asked to accept when it is not offered, an assigned kerbal asked to
   * be sacked, a spent experiment asked to deploy.
   *
   * Authority: the entity's own state enum. `Strategies.Strategy.IsActive`,
   * `RDTech.State`, `Contract.State`, `ProtoCrewMember.RosterStatus`,
   * `ModuleScienceExperiment.Deployed`/`Inoperable`. Every one of those is
   * `[Description]`-tagged or otherwise nameable, so `CommandResult.detail` can
   * carry the state in the game's own words.
   */
  WrongState: "wrongState",
  /**
   * Right command, wrong moment: the flight is not in a state that permits it
   * yet, and will be later.
   *
   * Authority: `FlightGlobals.ClearToSave()`, which returns one of five refusals
   * (in atmosphere, under acceleration, moving over the surface, about to crash,
   * on a ladder), plus `FlightDriver.CanRevertToPostInit`/`CanRevertToPrelaunch`
   * and the `GameParameters` flags for leaving to the space center and to the
   * tracking station. The arm rides on `CommandResult.detail`.
   *
   * Also the SCET alarm arm, for a vantage it cannot check because no command
   * centre is known to the simulation yet: the main menu, and the ticks before
   * the first capture. A vantage that is known and inactive is
   * `CommandErrorCode.Range` instead, because that one does not resolve by
   * waiting.
   *
   * Distinct from `CommandErrorCode.WrongState`, which is about the entity and
   * does not resolve by waiting.
   */
  NotClearToProceed: "notClearToProceed",
  /**
   * The part or vessel does not have the capability this command needs: a rotor
   * asked for a target angle, an unmotorised servo asked to drive, a part with
   * no such action, an action present but inert, an autopilot mode this craft
   * cannot hold.
   *
   * Authority: the part's own module list and fields
   * (`ModuleRoboticServoRotor`/`Hinge`/`Piston`, `servoIsMotorized`,
   * `BaseEvent.active`, `BaseEvent.EventIsDisabledByVariant`) and
   * `VesselAutopilot.CanSetMode`.
   *
   * Nothing an operator waits for. The craft would have to be different for this
   * to work, which is why it is not `CommandErrorCode.NotClearToProceed` and not
   * `CommandErrorCode.WrongState`.
   */
  CapabilityMismatch: "capabilityMismatch",
  /**
   * There is no usable link for what this command needs to send.
   *
   * Authority: `ScienceUtil.GetBestTransmitter(Vessel)` and
   * `IScienceDataTransmitter.CanTransmit()`. Deliberately NOT the Courier's own
   * comms-loss gate, which refuses the dispatch before a handler ever runs; this
   * is the vessel finding it has no antenna that can carry the payload.
   */
  NoConnection: "noConnection",
  /**
   * The capability exists in the game but this save has not unlocked it: fuel
   * transfer, custom action groups, flight planning, EVA, the maneuver tool.
   *
   * Authority: `GameVariables.UnlockedFuelTransfer`,
   * `UnlockedActionGroupsStock`/`Custom`, `UnlockedFlightPlanning`,
   * `UnlockedEVA`/`Flags`/`Clamber`, `ManeuverToolAvailable`, each read at the
   * owning facility's normalised level.
   *
   * Distinct from `CommandErrorCode.LimitReached`, which is a number against a
   * number. This is a switch that is off, and the fix is an upgrade rather than
   * freeing a slot.
   */
  NotUnlocked: "notUnlocked",
  /**
   * Another vessel is on the launch site.
   *
   * Authority: `PreFlightTests.LaunchSiteClear`, whose
   * `GetWarningTitle()`/`GetWarningDescription()` are the game's own words for
   * it and ride on `CommandResult.detail`.
   */
  SiteOccupied: "siteOccupied",
  /**
   * The facility this command needs is destroyed or damaged.
   *
   * Authority: `PreFlightTests.FacilityOperational`, over
   * `PSystemSetup.Instance.GetSpaceCenterFacility(name).GetFacilityDamage()`.
   */
  FacilityDamaged: "facilityDamaged",
  /**
   * The vehicle is not a launchable article yet: an install's build and
   * logistics model has work outstanding on it. Nothing is over a limit and
   * nothing is broken, the thing simply has not been made ready.
   *
   * Authority: whichever Uplink CONTRIBUTED the readiness requirement that
   * refused (see `IUplinkHost.AddCommandRequirement`), never a stock KSP read:
   * stock has no build step, so it contributes no readiness requirements and
   * this code never arrives on a stock install. Under RP-1 it is a vehicle that
   * was never integrated, one still integrating, one finished but not rolled
   * out, or one rolled out to a pad still being reconditioned.
   * `CommandResult.detail` says which.
   *
   * Deliberately NOT `CommandErrorCode.LimitReached`, which is the launch
   * refusal an operator already gets for a craft that is too heavy or too large
   * for the site, and which is fixed by changing the craft or upgrading the pad.
   * This one is fixed by doing the outstanding work, and the two want entirely
   * different next moves.
   *
   * Deliberately NOT `CommandErrorCode.NotFound` either, which `ksp.launch`
   * already returns when no craft file answers to the name. A craft that exists
   * on disk and has never been built is a different situation from one that does
   * not exist, and collapsing them tells an operator to go looking for a file
   * that is sitting right there.
   */
  NotReady: "notReady",
  /**
   * The command consumes a countable ITEM and there are not enough of them
   * aboard: an EVA repair kit for a repair, on a provider that charges one.
   *
   * Authority: the provider's own charge, read back from the same function that
   * STATES the cost on `ReliabilityPartEntry.repairCost`. The two come from one
   * place precisely so a console cannot show one number while the repair takes
   * another, and the ITEM is always the provider's to name: this code never
   * asserts which one, only that there were too few.
   *
   * `CommandErrorCode.InsufficientFunds`'s and
   * `CommandErrorCode.InsufficientScience`'s third sibling, and separate for the
   * same reason those two are separate from each other: an operator short of a
   * physical item does something entirely different about it from one short of a
   * currency, and nothing can be bought to fix it.
   *
   * Deliberately NOT `CommandErrorCode.LimitReached`, which is a capacity that
   * is FULL. This is a store that is empty, and the two read as opposites.
   */
  InsufficientResource: "insufficientResource",
  /**
   * The provider was ASKED and COULD NOT ANSWER. Nothing about the craft, the
   * save or the moment was established, so the one fact this refusal carries is
   * that the question went unanswered.
   *
   * None of its three neighbours, and folding it into any of them states
   * something that was never established rather than merely stating it coarsely.
   * "The answer is no" (a genuine omni antenna asked to aim) is a FACT about the
   * craft, and that is `CommandErrorCode.CapabilityMismatch`. "Not applicable"
   * (asked of a craft that carries nothing this command could act on) is a
   * refusal about what is there at all, and that is `CommandErrorCode.NotFound`.
   * "Not yet" resolves by waiting, which is
   * `CommandErrorCode.NotClearToProceed`; this does not resolve by waiting, and
   * a retry is a second attempt at the same question rather than a later one.
   *
   * `CommandResult.detail` names WHAT could not be read when the producer had a
   * name for it, and never says what the answer would have been. A surface has
   * nothing to tell the operator about their vehicle here, because nothing was
   * learned about it; offering the command again is the only honest next move.
   */
  Unreadable: "unreadable",
  /**
   * The command acts at a PLACE, and the command centre it was sent from has no
   * authority there: a launch from a pad in another planet's system.
   *
   * Authority, never delay. The command itself is still instant; what this
   * refuses is the sender, not the moment, so no amount of waiting makes it
   * succeed. Sending from a centre in the place's own system does.
   *
   * `CommandResult.detail` names the centre and the place, and the system each
   * is in, so an operator learns which seat to move to rather than seeing a
   * control that simply does nothing.
   *
   * Distinct from `CommandErrorCode.NoConnection`, which is a link that cannot
   * carry the command. A centre may be perfectly linked to the place and still
   * have no authority over it.
   */
  OutOfReach: "outOfReach",
} as const;
export type CommandErrorCode = (typeof CommandErrorCode)[keyof typeof CommandErrorCode];

/**
 * Why a command, or any other request, could not be CARRIED: nothing about the
 * game was decided. The refused/failed split is the kind of code, not a
 * judgement a client makes: a `RefusalCode` says the game said no, this says
 * the machinery did not get that far, and a retry may work.
 *
 * Closed, and declared only here. An Uplink never mints a fault: a handler
 * that throws already becomes `FaultCode.CommandUnavailable`, and
 * `CommandFaultException` is how a handler raises one of these deliberately.
 *
 * @category Error codes
 */
export const FaultCode = {
  /**
   * A frame of a known type that could not be read, including a
   * `command-request` whose `args` do not fit the command. Only that call is
   * refused; the command stays available.
   */
  InvalidEnvelope: "invalidEnvelope",
  /**
   * A frame whose `type` this build does not recognise.
   */
  UnknownEnvelopeType: "unknownEnvelopeType",
  /**
   * A frame that parsed as a type this build has nothing to do with.
   */
  UnhandledEnvelope: "unhandledEnvelope",
  /**
   * A binary frame sent up the socket, which nothing accepts.
   */
  BinaryFrameNotAccepted: "binaryFrameNotAccepted",
  /**
   * A command that is unknown or unavailable, or whose handler threw. A handler
   * that threw leaves its command unavailable for the session.
   */
  CommandUnavailable: "commandUnavailable",
  /**
   * A command the host could not run in time: it was handed to the game's main
   * thread and the game did not take it before the host stopped waiting, as
   * during a scene load. Nothing was decided, and the command may still run
   * later.
   */
  MainThreadTimeout: "mainThreadTimeout",
  /**
   * A command that ran and whose result could not be written.
   */
  ResultSerializationError: "resultSerializationError",
  /**
   * A subscription to a topic nothing declares.
   */
  UnknownTopic: "unknownTopic",
  /**
   * A topic whose payload could not be written.
   */
  PayloadSerializationError: "payloadSerializationError",
  /**
   * A `set-vantage`, or a command's `vantage`, naming a command centre that is
   * not active.
   */
  UnknownVantage: "unknownVantage",
  /**
   * The transport held the command for a link that never came back, and has
   * stopped retrying. It never left this machine.
   */
  Undelivered: "undelivered",
  /**
   * The client was shut down while the command waited for an answer.
   */
  Disposed: "disposed",
  /**
   * The transport's queue of commands waiting for a link is full, so this one
   * was not queued.
   */
  SendQueueFull: "sendQueueFull",
  /**
   * A station's link to the main screen dropped while the command was on it.
   */
  PeerDisconnected: "peerDisconnected",
  /**
   * The main screen had no connection to the mod to relay a station's command
   * over.
   */
  NoClient: "noClient",
  /**
   * A rejection that carried no code a client could read, such as a throw from
   * inside a handler on the client.
   */
  Unclassified: "unclassified",
} as const;
export type FaultCode = (typeof FaultCode)[keyof typeof FaultCode];

/**
 * Why a repair was refused, finer than its root: a part that does not resolve
 * and a crew member who does not are both `notFound`, and only the refinement
 * says which.
 *
 * A backend states WHY in this vocabulary, or with a bare root when none of
 * these fits. It does not write a sentence of its own: each code here carries
 * the one an operator reads.
 *
 * @category Error codes
 */
export const RepairRefusal = {
  /**
   * No crew member aboard answers to the requested name.
   */
  NoSuchCrew: "repair.noSuchCrew",
  /**
   * The named kerbal is aboard but does not satisfy the provider's own
   * (elevated, for a critical failure) crew requirement.
   */
  CrewNotQualified: "repair.crewNotQualified",
  /**
   * The kerbal could not have got out: the hatch is inside a fairing. Resolves
   * by waiting, since the fairing is jettisoned later in the same flight.
   */
  EvaImpossible: "repair.evaImpossible",
  /**
   * Fewer consumables aboard than the provider charges for this repair.
   */
  NoKits: "repair.noKits",
  /**
   * Nothing on this install models reliability, so there is nothing to repair.
   */
  NotModelled: "repair.notModelled",
  /**
   * No part on the vessel carries that id, or it carries nothing repairable.
   */
  NoSuchPart: "repair.noSuchPart",
  /**
   * The provider models this failure and states that it cannot be repaired at
   * all: TestFlight's `ITestFlightFailure.CanAttemptRepair()` is false for an
   * exploded part, a fired docking clamp and a snapped solar mechanism, whatever
   * crew are aboard and whatever they carry.
   *
   * Deliberately NOT `RepairRefusal.NotModelled`. The model is present and
   * working; this is its answer.
   */
  Unrepairable: "repair.unrepairable",
} as const;
export type RepairRefusal = (typeof RepairRefusal)[keyof typeof RepairRefusal];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const CORE_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "noVessel",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "there is no vessel to act on",
    meaning: "No active vessel to act on.",
  },
  {
    id: "modeUnavailable",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the game would not say why",
    meaning: "The requested mode or state is not available, and the game gave no more specific reason.",
  },
  {
    id: "range",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "an argument was outside its valid range",
    meaning: "An argument was out of its valid range.",
  },
  {
    id: "notFound",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "nothing here answers to that",
    meaning: "The referenced entity (node id, vessel/body target) did not resolve.",
  },
  {
    id: "planNotOwned",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "another planner owns the flight plan",
    meaning: "The elected maneuver-plan provider is not the one that reads stock's `patchedConicSolver`, so a write there would never be seen.\n\nRefused rather than attempted, because attempting it produces a GHOST NODE: we mutate stock's solver, the owning planner never reads it (an n-body backend clears that list every frame and writes its own guidance node into it), and the operator sees a maneuver node on the board that does precisely nothing. A silent wrong answer with a confident presentation.\n\nThe code says WHY, not WHO: the owner is already on the wire as `VesselManeuver.Planner` for a readout to name.",
  },
  {
    id: "limitReached",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "a limit has been reached",
    meaning: "A capacity is full: the Astronaut Complex holds its cap of active crew, a facility holds its cap of anything else countable.\n\nThe world has to change before a retry means anything; freeing a slot is a thing an operator can actually do.\n\nThe arm chooses the sentence, `CommandResult.breach` supplies the numbers in it. Neither is worth sending without the other: a code with no payload cannot say \"16 of 16\".",
  },
  {
    id: "alreadyAtMaximum",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "it is already at its maximum",
    meaning: "Already at the top of an upgradeable scale, so there is nothing above this to move to. The Launch Pad at tier 3 of 3.\n\nDeliberately NOT `CommandErrorCode.LimitReached`. A cap that is full can be freed; a maximum tier cannot be exceeded by any action at all, and an operator reads those two differently.",
  },
  {
    id: "insufficientFunds",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "there are not enough funds",
    meaning: "The command costs more than the funds on hand.\n\n`CommandResult.breach` carries the cost as `Actual` against the balance as `Limit`, so the client can say how short and in the operator's own currency rendering.",
  },
  {
    id: "insufficientScience",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "there is not enough science",
    meaning: "The command costs more science than is banked. `CommandErrorCode.InsufficientFunds`'s twin, and separate for the same reason the game keeps `Currency` as three members: an operator short of science does something entirely different about it from one short of funds.\n\nAuthority: `CurrencyModifierQuery.RunQuery(reason, ...).CanAfford(Currency.Science)`, which is what `RDTech.ResearchTech` asks. NOT `ResearchAndDevelopment.CanAfford`, which skips the modifier chain and so answers a different question from the one the game acts on.",
  },
  {
    id: "careerModeRequired",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "this save is not a career game",
    meaning: "The save is not a career save, so this command's whole subsystem does not exist here.\n\nAuthority: `HighLogic.CurrentGame.Mode`, and in practice the null `Instance` of the `ScenarioModule` that would have answered (`Funding`, `ContractSystem`, `StrategySystem`, `ResearchAndDevelopment`, `ScenarioUpgradeableFacilities`).\n\nThis is a PERMANENT property of the save, not a state that may change, which is exactly what `CommandErrorCode.ModeUnavailable` could not say. An operator should see the control absent rather than refused; a client that can tell this arm from the others can do that.",
  },
  {
    id: "wrongScene",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the game is not in a scene that allows it",
    meaning: "The game is in a scene this command cannot run from.\n\nAuthority: `HighLogic.LoadedScene` (`GameScenes`). `CommandResult.detail` names the scene when the producer had one.",
  },
  {
    id: "wrongState",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "it is not in a state that allows it",
    meaning: "The entity is not in a state this transition applies to: an already-active strategy asked to activate, an already-researched node asked to unlock, a contract asked to accept when it is not offered, an assigned kerbal asked to be sacked, a spent experiment asked to deploy.\n\nAuthority: the entity's own state enum. `Strategies.Strategy.IsActive`, `RDTech.State`, `Contract.State`, `ProtoCrewMember.RosterStatus`, `ModuleScienceExperiment.Deployed`/`Inoperable`. Every one of those is `[Description]`-tagged or otherwise nameable, so `CommandResult.detail` can carry the state in the game's own words.",
  },
  {
    id: "notClearToProceed",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the flight is not clear for it yet",
    meaning: "Right command, wrong moment: the flight is not in a state that permits it yet, and will be later.\n\nAuthority: `FlightGlobals.ClearToSave()`, which returns one of five refusals (in atmosphere, under acceleration, moving over the surface, about to crash, on a ladder), plus `FlightDriver.CanRevertToPostInit`/`CanRevertToPrelaunch` and the `GameParameters` flags for leaving to the space center and to the tracking station. The arm rides on `CommandResult.detail`.\n\nAlso the SCET alarm arm, for a vantage it cannot check because no command centre is known to the simulation yet: the main menu, and the ticks before the first capture. A vantage that is known and inactive is `CommandErrorCode.Range` instead, because that one does not resolve by waiting.\n\nDistinct from `CommandErrorCode.WrongState`, which is about the entity and does not resolve by waiting.",
  },
  {
    id: "capabilityMismatch",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "this craft cannot do it",
    meaning: "The part or vessel does not have the capability this command needs: a rotor asked for a target angle, an unmotorised servo asked to drive, a part with no such action, an action present but inert, an autopilot mode this craft cannot hold.\n\nAuthority: the part's own module list and fields (`ModuleRoboticServoRotor`/`Hinge`/`Piston`, `servoIsMotorized`, `BaseEvent.active`, `BaseEvent.EventIsDisabledByVariant`) and `VesselAutopilot.CanSetMode`.\n\nNothing an operator waits for. The craft would have to be different for this to work, which is why it is not `CommandErrorCode.NotClearToProceed` and not `CommandErrorCode.WrongState`.",
  },
  {
    id: "noConnection",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "there is no usable link",
    meaning: "There is no usable link for what this command needs to send.\n\nAuthority: `ScienceUtil.GetBestTransmitter(Vessel)` and `IScienceDataTransmitter.CanTransmit()`. Deliberately NOT the Courier's own comms-loss gate, which refuses the dispatch before a handler ever runs; this is the vessel finding it has no antenna that can carry the payload.",
  },
  {
    id: "notUnlocked",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "it has not been unlocked yet",
    meaning: "The capability exists in the game but this save has not unlocked it: fuel transfer, custom action groups, flight planning, EVA, the maneuver tool.\n\nAuthority: `GameVariables.UnlockedFuelTransfer`, `UnlockedActionGroupsStock`/`Custom`, `UnlockedFlightPlanning`, `UnlockedEVA`/`Flags`/`Clamber`, `ManeuverToolAvailable`, each read at the owning facility's normalised level.\n\nDistinct from `CommandErrorCode.LimitReached`, which is a number against a number. This is a switch that is off, and the fix is an upgrade rather than freeing a slot.",
  },
  {
    id: "siteOccupied",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "another vessel is on the launch site",
    meaning: "Another vessel is on the launch site.\n\nAuthority: `PreFlightTests.LaunchSiteClear`, whose `GetWarningTitle()`/`GetWarningDescription()` are the game's own words for it and ride on `CommandResult.detail`.",
  },
  {
    id: "facilityDamaged",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the building is out of action",
    meaning: "The facility this command needs is destroyed or damaged.\n\nAuthority: `PreFlightTests.FacilityOperational`, over `PSystemSetup.Instance.GetSpaceCenterFacility(name).GetFacilityDamage()`.",
  },
  {
    id: "notReady",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the vehicle is not ready to fly yet",
    meaning: "The vehicle is not a launchable article yet: an install's build and logistics model has work outstanding on it. Nothing is over a limit and nothing is broken, the thing simply has not been made ready.\n\nAuthority: whichever Uplink CONTRIBUTED the readiness requirement that refused (see `IUplinkHost.AddCommandRequirement`), never a stock KSP read: stock has no build step, so it contributes no readiness requirements and this code never arrives on a stock install. Under RP-1 it is a vehicle that was never integrated, one still integrating, one finished but not rolled out, or one rolled out to a pad still being reconditioned. `CommandResult.detail` says which.\n\nDeliberately NOT `CommandErrorCode.LimitReached`, which is the launch refusal an operator already gets for a craft that is too heavy or too large for the site, and which is fixed by changing the craft or upgrading the pad. This one is fixed by doing the outstanding work, and the two want entirely different next moves.\n\nDeliberately NOT `CommandErrorCode.NotFound` either, which `ksp.launch` already returns when no craft file answers to the name. A craft that exists on disk and has never been built is a different situation from one that does not exist, and collapsing them tells an operator to go looking for a file that is sitting right there.",
  },
  {
    id: "insufficientResource",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "there are not enough of what it uses aboard",
    meaning: "The command consumes a countable ITEM and there are not enough of them aboard: an EVA repair kit for a repair, on a provider that charges one.\n\nAuthority: the provider's own charge, read back from the same function that STATES the cost on `ReliabilityPartEntry.repairCost`. The two come from one place precisely so a console cannot show one number while the repair takes another, and the ITEM is always the provider's to name: this code never asserts which one, only that there were too few.\n\n`CommandErrorCode.InsufficientFunds`'s and `CommandErrorCode.InsufficientScience`'s third sibling, and separate for the same reason those two are separate from each other: an operator short of a physical item does something entirely different about it from one short of a currency, and nothing can be bought to fix it.\n\nDeliberately NOT `CommandErrorCode.LimitReached`, which is a capacity that is FULL. This is a store that is empty, and the two read as opposites.",
  },
  {
    id: "unreadable",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "the game would not answer",
    meaning: "The provider was ASKED and COULD NOT ANSWER. Nothing about the craft, the save or the moment was established, so the one fact this refusal carries is that the question went unanswered.\n\nNone of its three neighbours, and folding it into any of them states something that was never established rather than merely stating it coarsely. \"The answer is no\" (a genuine omni antenna asked to aim) is a FACT about the craft, and that is `CommandErrorCode.CapabilityMismatch`. \"Not applicable\" (asked of a craft that carries nothing this command could act on) is a refusal about what is there at all, and that is `CommandErrorCode.NotFound`. \"Not yet\" resolves by waiting, which is `CommandErrorCode.NotClearToProceed`; this does not resolve by waiting, and a retry is a second attempt at the same question rather than a later one.\n\n`CommandResult.detail` names WHAT could not be read when the producer had a name for it, and never says what the answer would have been. A surface has nothing to tell the operator about their vehicle here, because nothing was learned about it; offering the command again is the only honest next move.",
  },
  {
    id: "outOfReach",
    kind: "refusal",
    refines: null,
    origin: null,
    sentence: "this command centre has no authority over that place",
    meaning: "The command acts at a PLACE, and the command centre it was sent from has no authority there: a launch from a pad in another planet's system.\n\nAuthority, never delay. The command itself is still instant; what this refuses is the sender, not the moment, so no amount of waiting makes it succeed. Sending from a centre in the place's own system does.\n\n`CommandResult.detail` names the centre and the place, and the system each is in, so an operator learns which seat to move to rather than seeing a control that simply does nothing.\n\nDistinct from `CommandErrorCode.NoConnection`, which is a link that cannot carry the command. A centre may be perfectly linked to the place and still have no authority over it.",
  },
  {
    id: "invalidEnvelope",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the request could not be read",
    meaning: "A frame of a known type that could not be read, including a `command-request` whose `args` do not fit the command. Only that call is refused; the command stays available.",
  },
  {
    id: "unknownEnvelopeType",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the mod does not recognise that kind of request",
    meaning: "A frame whose `type` this build does not recognise.",
  },
  {
    id: "unhandledEnvelope",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the mod has nothing to do with that request",
    meaning: "A frame that parsed as a type this build has nothing to do with.",
  },
  {
    id: "binaryFrameNotAccepted",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the mod accepts no binary frames",
    meaning: "A binary frame sent up the socket, which nothing accepts.",
  },
  {
    id: "commandUnavailable",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the command is not available",
    meaning: "A command that is unknown or unavailable, or whose handler threw. A handler that threw leaves its command unavailable for the session.",
  },
  {
    id: "mainThreadTimeout",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "the game did not get to it in time",
    meaning: "A command the host could not run in time: it was handed to the game's main thread and the game did not take it before the host stopped waiting, as during a scene load. Nothing was decided, and the command may still run later.",
  },
  {
    id: "resultSerializationError",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "its answer could not be sent",
    meaning: "A command that ran and whose result could not be written.",
  },
  {
    id: "unknownTopic",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "nothing publishes that",
    meaning: "A subscription to a topic nothing declares.",
  },
  {
    id: "payloadSerializationError",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "its value could not be sent",
    meaning: "A topic whose payload could not be written.",
  },
  {
    id: "unknownVantage",
    kind: "fault",
    refines: null,
    origin: "mod",
    sentence: "that command centre is not active",
    meaning: "A `set-vantage`, or a command's `vantage`, naming a command centre that is not active.",
  },
  {
    id: "undelivered",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "it was never sent",
    meaning: "The transport held the command for a link that never came back, and has stopped retrying. It never left this machine.",
  },
  {
    id: "disposed",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "the connection closed before an answer came",
    meaning: "The client was shut down while the command waited for an answer.",
  },
  {
    id: "sendQueueFull",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "too many commands are waiting for the link",
    meaning: "The transport's queue of commands waiting for a link is full, so this one was not queued.",
  },
  {
    id: "peerDisconnected",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "the link to the main screen dropped",
    meaning: "A station's link to the main screen dropped while the command was on it.",
  },
  {
    id: "noClient",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "the main screen is not connected to the game",
    meaning: "The main screen had no connection to the mod to relay a station's command over.",
  },
  {
    id: "unclassified",
    kind: "fault",
    refines: null,
    origin: "client",
    sentence: "something went wrong",
    meaning: "A rejection that carried no code a client could read, such as a throw from inside a handler on the client.",
  },
  {
    id: "repair.noSuchCrew",
    kind: "refusal",
    refines: "notFound",
    origin: null,
    sentence: "no crew member aboard has that name",
    meaning: "No crew member aboard answers to the requested name.",
  },
  {
    id: "repair.crewNotQualified",
    kind: "refusal",
    refines: "capabilityMismatch",
    origin: null,
    sentence: "that crew member is not qualified to repair it",
    meaning: "The named kerbal is aboard but does not satisfy the provider's own (elevated, for a critical failure) crew requirement.",
  },
  {
    id: "repair.evaImpossible",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "the crew cannot get out to it yet",
    meaning: "The kerbal could not have got out: the hatch is inside a fairing. Resolves by waiting, since the fairing is jettisoned later in the same flight.",
  },
  {
    id: "repair.noKits",
    kind: "refusal",
    refines: "insufficientResource",
    origin: null,
    sentence: "there are not enough repair kits aboard",
    meaning: "Fewer consumables aboard than the provider charges for this repair.",
  },
  {
    id: "repair.notModelled",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "nothing on this install models part failures",
    meaning: "Nothing on this install models reliability, so there is nothing to repair.",
  },
  {
    id: "repair.noSuchPart",
    kind: "refusal",
    refines: "notFound",
    origin: null,
    sentence: "no part aboard needs that repair",
    meaning: "No part on the vessel carries that id, or it carries nothing repairable.",
  },
  {
    id: "repair.unrepairable",
    kind: "refusal",
    refines: "capabilityMismatch",
    origin: null,
    sentence: "that failure cannot be repaired",
    meaning: "The provider models this failure and states that it cannot be repaired at all: TestFlight's `ITestFlightFailure.CanAttemptRepair()` is false for an exploded part, a fired docking clamp and a snapped solar mechanism, whatever crew are aboard and whatever they carry.\n\nDeliberately NOT `RepairRefusal.NotModelled`. The model is present and working; this is its answer.",
  },
];
