//     This code was generated by the Sitrep contract frame codegen
//     (Sitrep.Contract.RtConfig.EmitFrameMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepFrame]-tagged property in
// Sitrep.Contract. A field ABSENT here declares no frame. See ../field-frames.ts.

/** One field's declared frame, and the per-tick switch when its axes change. */
export interface GeneratedFrameDeclaration {
  readonly frame: string;
  readonly whenSet?: string;
  readonly selectedBy?: string;
}

export const GENERATED_TOPIC_FRAMES = {
  "vessel.dock": {
    relativePosition: { frame: "subject-relative" },
    relativeVelocity: { frame: "subject-relative" },
  },
  "vessel.orbit.truth": {
    position: { frame: "body-centred-inertial", whenSet: "body-centred-rotating", selectedBy: "frameRotating" },
    velocity: { frame: "body-centred-inertial", whenSet: "body-centred-rotating", selectedBy: "frameRotating" },
  },
  "vessel.target": {
    relativePosition: { frame: "subject-relative" },
    relativeVelocity: { frame: "subject-relative" },
  },
} as const satisfies Record<string, Record<string, GeneratedFrameDeclaration>>;

export const GENERATED_TYPE_FRAMES = {
  "DockAlignment": {
    relativePosition: { frame: "subject-relative" },
    relativeVelocity: { frame: "subject-relative" },
  },
  "PartBounds": {
    center: { frame: "part-local" },
    size: { frame: "part-local" },
  },
  "VesselOrbitTruth": {
    position: { frame: "body-centred-inertial", whenSet: "body-centred-rotating", selectedBy: "frameRotating" },
    velocity: { frame: "body-centred-inertial", whenSet: "body-centred-rotating", selectedBy: "frameRotating" },
  },
  "VesselPart": {
    position: { frame: "vessel-local" },
    up: { frame: "vessel-local" },
  },
  "VesselTarget": {
    relativePosition: { frame: "subject-relative" },
    relativeVelocity: { frame: "subject-relative" },
  },
} as const satisfies Record<string, Record<string, GeneratedFrameDeclaration>>;
