//     This code was generated by the Sitrep contract reckonability codegen
//     (Sitrep.Contract.RtConfig.EmitReckonability, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepReckonable]-tagged property in
// Sitrep.Contract: the property's owning [SitrepTopic] is the topic, the
// camelCased property name is the field, and each declared input is split
// into the topic it names (empty for a path on the value's own payload) and
// the path inside it (empty for a whole payload). A field ABSENT here is a
// value no published model carries forward, which is the default and is a
// statement rather than an omission. See ../reckonability.ts.

/** The closed vocabulary of forward models (Sitrep.Contract.ReckoningBases). */
export type GeneratedReckoningBasis =
  | "kepler-propagation"
  | "linear-dead-reckoning"
  | "rate-integration"
;

/**
 * One published input a declared model needs.
 *
 * `topic` is "" when the input is a path on the value's own payload, and
 * `path` is "" when the input is another Topic's whole payload. Both halves
 * are carried separately so a consumer resolves the dep without parsing, and
 * the contract's own spelling is recoverable for a message an operator reads.
 */
export interface GeneratedReckonableInput {
  readonly topic: string;
  readonly path: string;
}

/** One value the contract declares a model can carry forward. */
export interface GeneratedReckonableValue {
  readonly topic: string;
  readonly field: string;
  readonly basis: GeneratedReckoningBasis;
  readonly inputs: readonly GeneratedReckonableInput[];
}

export const GENERATED_RECKONABLE_VALUES = [
  { topic: "vessel.dock", field: "distance", basis: "linear-dead-reckoning", inputs: [ { topic: "", path: "relativePosition" }, { topic: "", path: "relativeVelocity" } ] },
  { topic: "vessel.dock", field: "relativePosition", basis: "linear-dead-reckoning", inputs: [ { topic: "", path: "relativeVelocity" } ] },
  { topic: "vessel.flight", field: "altitudeAsl", basis: "kepler-propagation", inputs: [ { topic: "vessel.orbit", path: "" }, { topic: "system.bodies", path: "" } ] },
  { topic: "vessel.flight", field: "orbitalSpeed", basis: "kepler-propagation", inputs: [ { topic: "vessel.orbit", path: "" } ] },
  { topic: "vessel.orbit.truth", field: "position", basis: "kepler-propagation", inputs: [ { topic: "", path: "velocity" }, { topic: "", path: "frameRotating" }, { topic: "vessel.orbit", path: "mu" } ] },
  { topic: "vessel.orbit.truth", field: "velocity", basis: "kepler-propagation", inputs: [ { topic: "", path: "position" }, { topic: "", path: "frameRotating" }, { topic: "vessel.orbit", path: "mu" } ] },
  { topic: "vessel.target", field: "relativePosition", basis: "linear-dead-reckoning", inputs: [ { topic: "", path: "relativeVelocity" } ] },
] as const satisfies readonly GeneratedReckonableValue[];

/**
 * The same rows keyed by Topic, as the field-name tuple the SDK turns into a
 * key union. A Topic ABSENT here has no declared model for any of its values.
 */
export const GENERATED_RECKONABLE_FIELDS = {
  "vessel.dock": ["distance", "relativePosition"],
  "vessel.flight": ["altitudeAsl", "orbitalSpeed"],
  "vessel.orbit.truth": ["position", "velocity"],
  "vessel.target": ["relativePosition"],
} as const satisfies Record<string, readonly string[]>;
