//     This code was generated by scripts/gen-test-theme.mjs.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// The theme `@ksp-gonogo/sitrep-sdk/testing`'s `render` mounts. A copy of
// `@ksp-gonogo/theme`'s `defaultDarkTheme`, which owns it.
//
// Copied rather than imported because the sdk is the leaf: it can name neither
// `@ksp-gonogo/theme` (private, so a consumer cannot install it) nor
// `@ksp-gonogo/ui-kit` (imports the sdk, so the edge would cycle). See the
// generator's header for why an accessor or a path-derived Proxy does not work.
//
// Every value here is a `var(--...)` handle or a literal; the numbers behind them
// live in `tokens.css`, which no test loads. So a test asserts on
// `padding: var(--space-8)`, exactly as the app renders it.

export const GENERATED_TEST_THEME = {
  colors: {
    text: {
      primary: "var(--color-text-primary)",
      muted: "var(--color-text-muted)",
      dim: "var(--color-text-dim)",
      faint: "var(--color-text-faint)",
      inverse: "var(--color-text-inverse)",
    },
    surface: {
      app: "var(--color-surface-app)",
      panel: "var(--color-surface-panel)",
      raised: "var(--color-surface-raised)",
      sunken: "var(--color-surface-sunken)",
    },
    border: {
      subtle: "var(--color-border-subtle)",
      strong: "var(--color-border-strong)",
    },
    accent: {
      fg: "var(--color-accent-fg)",
      bg: "var(--color-accent-bg)",
    },
    status: {
      go: {
        fg: "var(--color-status-go-fg)",
        bg: "var(--color-status-go-bg)",
      },
      nogo: {
        fg: "var(--color-status-nogo-fg)",
        bg: "var(--color-status-nogo-bg)",
      },
      warning: {
        fg: "var(--color-status-warning-fg)",
        bg: "var(--color-status-warning-bg)",
      },
      info: {
        fg: "var(--color-status-info-fg)",
        bg: "var(--color-status-info-bg)",
      },
    },
    focus: "var(--color-focus)",
  },
  typography: {
    family: {
      mono: "ui-monospace, \"JetBrains Mono\", \"IBM Plex Mono\", Menlo, Consolas, monospace",
    },
    size: {
      xs: "var(--font-size-xs)",
      sm: "var(--font-size-sm)",
      base: "var(--font-size-base)",
      lg: "var(--font-size-lg)",
    },
    weight: {
      regular: 400,
      bold: 700,
    },
    letterSpacing: {
      tight: "0.05em",
      label: "0.1em",
      wide: "0.15em",
      body: "0",
    },
  },
  space: {
    xs: "var(--space-2)",
    sm: "var(--space-4)",
    md: "var(--space-8)",
    lg: "var(--space-12)",
    xl: "var(--space-16)",
  },
  radii: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    pill: "var(--radius-pill)",
  },
  borders: {
    subtle: "1px solid var(--color-border-subtle)",
    strong: "1px solid var(--color-border-strong)",
  },
} as const;
