//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value — with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.

import type {
  CareerMode,
  CareerStatus,
  CommsConnectivity,
  CommsControlState,
  CommsDataRate,
  CommsDelay,
  CommsLink,
  CommsLinkMargin,
  CommsLinkQuality,
  CommsNetwork,
  CommsPath,
  CommsSignalStrength,
  CrashReport,
  CrewRosterEntry,
  DeployedEntry,
  DockAlignment,
  ExperimentBreakdownEntry,
  ExperimentEntry,
  FlightCurrent,
  FlightEnded,
  FlightStarted,
  FlightVesselChanged,
  GameDlc,
  InstrumentEntry,
  KerbcastCameraEntry,
  KosProcessorInfo,
  LabEntry,
  LaunchSiteEntry,
  PartsPower,
  RecoveryReport,
  RevertAvailability,
  RoboticsAvailability,
  SavedShipEntry,
  ScanScienceEntry,
  ScanningVesselEntry,
  SensorEntry,
  ServoEntry,
  SpaceCenterPartsAvailable,
  SpaceCenterPoiEntry,
  SpaceCenterScene,
  StageDeltaVEntry,
  StageDeltaVSummary,
  SystemBodies,
  SystemVessels,
  VesselAttitude,
  VesselComms,
  VesselControl,
  VesselCrew,
  VesselFlight,
  VesselIdentity,
  VesselManeuver,
  VesselOrbit,
  VesselOrbitTruth,
  VesselParts,
  VesselPhysicsMode,
  VesselPropulsion,
  VesselResources,
  VesselStructure,
  VesselSurface,
  VesselTarget,
  VesselThermal,
  WarpState,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "career.mode": CareerMode;
  "career.status": CareerStatus;
  "comms.connectivity": CommsConnectivity;
  "comms.controlState": CommsControlState;
  "comms.dataRate": CommsDataRate;
  "comms.delay": CommsDelay;
  "comms.link": CommsLink;
  "comms.linkMargin": CommsLinkMargin;
  "comms.linkQuality": CommsLinkQuality;
  "comms.network": CommsNetwork;
  "comms.path": CommsPath;
  "comms.signalStrength": CommsSignalStrength;
  "crash.lastCrash": CrashReport;
  "dv.stages": StageDeltaVEntry[];
  "dv.summary": StageDeltaVSummary;
  "flight.current": FlightCurrent;
  "flight.ended": FlightEnded;
  "flight.started": FlightStarted;
  "flight.vesselChanged": FlightVesselChanged;
  "game.dlc": GameDlc;
  "kerbcast.cameras": KerbcastCameraEntry[];
  "kos.processors": KosProcessorInfo[];
  "ksp.revertAvailability": RevertAvailability;
  "parts.power": PartsPower;
  "parts.robotics": ServoEntry[];
  "recovery.lastSummary": RecoveryReport;
  "robotics.available": RoboticsAvailability;
  "scansat.scanningVessels": ScanningVesselEntry[];
  "scansat.science": ScanScienceEntry[];
  "science.deployed": DeployedEntry[];
  "science.experimentBreakdown": ExperimentBreakdownEntry[];
  "science.experiments": ExperimentEntry[];
  "science.instruments": InstrumentEntry[];
  "science.lab": LabEntry[];
  "science.sensors": SensorEntry[];
  "spaceCenter.crewRoster": CrewRosterEntry[];
  "spaceCenter.launchSites": LaunchSiteEntry[];
  "spaceCenter.partsAvailable": SpaceCenterPartsAvailable;
  "spaceCenter.pois": SpaceCenterPoiEntry[];
  "spaceCenter.savedShips": SavedShipEntry[];
  "spaceCenter.scene": SpaceCenterScene;
  "system.bodies": SystemBodies;
  "system.vessels": SystemVessels;
  "time.warp": WarpState;
  "vessel.attitude": VesselAttitude;
  "vessel.comms": VesselComms;
  "vessel.control": VesselControl;
  "vessel.crew": VesselCrew;
  "vessel.dock": DockAlignment;
  "vessel.flight": VesselFlight;
  "vessel.identity": VesselIdentity;
  "vessel.maneuver": VesselManeuver;
  "vessel.orbit": VesselOrbit;
  "vessel.orbit.truth": VesselOrbitTruth;
  "vessel.parts": VesselParts;
  "vessel.physics.mode": VesselPhysicsMode;
  "vessel.propulsion": VesselPropulsion;
  "vessel.resources": VesselResources;
  "vessel.structure": VesselStructure;
  "vessel.surface": VesselSurface;
  "vessel.target": VesselTarget;
  "vessel.thermal": VesselThermal;
}

export const GENERATED_TOPIC_IDS = [
  "career.mode",
  "career.status",
  "comms.connectivity",
  "comms.controlState",
  "comms.dataRate",
  "comms.delay",
  "comms.link",
  "comms.linkMargin",
  "comms.linkQuality",
  "comms.network",
  "comms.path",
  "comms.signalStrength",
  "crash.lastCrash",
  "dv.stages",
  "dv.summary",
  "flight.current",
  "flight.ended",
  "flight.started",
  "flight.vesselChanged",
  "game.dlc",
  "kerbcast.cameras",
  "kos.processors",
  "ksp.revertAvailability",
  "parts.power",
  "parts.robotics",
  "recovery.lastSummary",
  "robotics.available",
  "scansat.scanningVessels",
  "scansat.science",
  "science.deployed",
  "science.experimentBreakdown",
  "science.experiments",
  "science.instruments",
  "science.lab",
  "science.sensors",
  "spaceCenter.crewRoster",
  "spaceCenter.launchSites",
  "spaceCenter.partsAvailable",
  "spaceCenter.pois",
  "spaceCenter.savedShips",
  "spaceCenter.scene",
  "system.bodies",
  "system.vessels",
  "time.warp",
  "vessel.attitude",
  "vessel.comms",
  "vessel.control",
  "vessel.crew",
  "vessel.dock",
  "vessel.flight",
  "vessel.identity",
  "vessel.maneuver",
  "vessel.orbit",
  "vessel.orbit.truth",
  "vessel.parts",
  "vessel.physics.mode",
  "vessel.propulsion",
  "vessel.resources",
  "vessel.structure",
  "vessel.surface",
  "vessel.target",
  "vessel.thermal",
] as const;
