//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.
//
// THIS IS NOT A LIST OF EVERY TOPIC ON THE WIRE, and it cannot become one.
// A DYNAMIC namespace (`fleet.`, `silence.`, `currency.`, vessel part-actions,
// and an Uplink's own) is registered at RUNTIME through
// `IUplinkHost.RegisterDynamicNamespace` and materialises its topics per
// subject, so no [SitrepTopic]-tagged type exists for reflection to find and
// nothing about it appears below. Asking this file "is there per-vessel X"
// gets a confident no for a topic that has been published all along:
// `fleet.<guid>.orbit` was surveyed as missing that way. To enumerate the
// dynamic half, grep the mod for `RegisterDynamicNamespace` instead.

import type {
  ArchiveEntry,
  AstronautComplexInfo,
  CareerMode,
  CareerStatus,
  CommandCentreEntry,
  CommsConnectivity,
  CommsControlState,
  CommsDelay,
  CommsLink,
  CommsNetwork,
  CommsOcclusion,
  CommsPath,
  CommsSignalStrength,
  CrashReport,
  CrewRosterEntry,
  DeployedEntry,
  DockAlignment,
  ExperimentBreakdownEntry,
  ExperimentEntry,
  FleetSilence,
  FlightCurrent,
  FlightEnded,
  FlightStarted,
  FlightVesselChanged,
  GameDlc,
  InstrumentEntry,
  IsruConverterEntry,
  IsruDrillEntry,
  LabEntry,
  LaunchSiteEntry,
  PartsPower,
  RecoveryReport,
  ReliabilityPartEntry,
  ReliabilitySummary,
  RevertAvailability,
  RoboticsAvailability,
  SavedShipEntry,
  SensorEntry,
  ServoEntry,
  SpaceCenterPartsAvailable,
  SpaceCenterPoiEntry,
  SpaceCenterScene,
  StageDeltaVEntry,
  StageDeltaVSummary,
  SystemBodies,
  SystemVessels,
  TargetAvailable,
  TimeCalendar,
  VesselAttitude,
  VesselComms,
  VesselControl,
  VesselCrew,
  VesselFlight,
  VesselIdentity,
  VesselLanding,
  VesselManeuver,
  VesselOrbit,
  VesselOrbitTruth,
  VesselParts,
  VesselPhysicsMode,
  VesselPropulsion,
  VesselResources,
  VesselStructure,
  VesselSurface,
  VesselTarget,
  VesselThermal,
  WarpState,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "career.mode": CareerMode;
  "career.status": CareerStatus;
  "commandCentre.roster": CommandCentreEntry[];
  "comms.connectivity": CommsConnectivity;
  "comms.controlState": CommsControlState;
  "comms.delay": CommsDelay;
  "comms.link": CommsLink;
  "comms.network": CommsNetwork;
  "comms.occlusion": CommsOcclusion;
  "comms.path": CommsPath;
  "comms.signalStrength": CommsSignalStrength;
  "crash.lastCrash": CrashReport;
  "deployed.bases": DeployedEntry[];
  "dv.stages": StageDeltaVEntry[];
  "dv.summary": StageDeltaVSummary;
  "fleet.silence": FleetSilence;
  "flight.current": FlightCurrent;
  "flight.ended": FlightEnded;
  "flight.started": FlightStarted;
  "flight.vesselChanged": FlightVesselChanged;
  "game.dlc": GameDlc;
  "isru.converters": IsruConverterEntry[];
  "isru.drills": IsruDrillEntry[];
  "ksp.revertAvailability": RevertAvailability;
  "parts.power": PartsPower;
  "recovery.lastSummary": RecoveryReport;
  "reliability.parts": ReliabilityPartEntry[];
  "reliability.summary": ReliabilitySummary;
  "robotics.available": RoboticsAvailability;
  "robotics.servos": ServoEntry[];
  "science.archive": ArchiveEntry[];
  "science.experimentBreakdown": ExperimentBreakdownEntry[];
  "science.experiments": ExperimentEntry[];
  "science.instruments": InstrumentEntry[];
  "science.lab": LabEntry[];
  "science.sensors": SensorEntry[];
  "spaceCenter.astronautComplex": AstronautComplexInfo;
  "spaceCenter.crewRoster": CrewRosterEntry[];
  "spaceCenter.launchSites": LaunchSiteEntry[];
  "spaceCenter.partsAvailable": SpaceCenterPartsAvailable;
  "spaceCenter.pois": SpaceCenterPoiEntry[];
  "spaceCenter.savedShips": SavedShipEntry[];
  "spaceCenter.scene": SpaceCenterScene;
  "system.bodies": SystemBodies;
  "system.vessels": SystemVessels;
  "target.available": TargetAvailable;
  "time.calendar": TimeCalendar;
  "time.warp": WarpState;
  "vessel.attitude": VesselAttitude;
  "vessel.comms": VesselComms;
  "vessel.control": VesselControl;
  "vessel.crew": VesselCrew;
  "vessel.dock": DockAlignment;
  "vessel.flight": VesselFlight;
  "vessel.identity": VesselIdentity;
  "vessel.landing": VesselLanding;
  "vessel.maneuver": VesselManeuver;
  "vessel.orbit": VesselOrbit;
  "vessel.orbit.truth": VesselOrbitTruth;
  "vessel.parts": VesselParts;
  "vessel.physics.mode": VesselPhysicsMode;
  "vessel.propulsion": VesselPropulsion;
  "vessel.resources": VesselResources;
  "vessel.structure": VesselStructure;
  "vessel.surface": VesselSurface;
  "vessel.target": VesselTarget;
  "vessel.thermal": VesselThermal;
}

export const GENERATED_TOPIC_IDS = [
  "career.mode",
  "career.status",
  "commandCentre.roster",
  "comms.connectivity",
  "comms.controlState",
  "comms.delay",
  "comms.link",
  "comms.network",
  "comms.occlusion",
  "comms.path",
  "comms.signalStrength",
  "crash.lastCrash",
  "deployed.bases",
  "dv.stages",
  "dv.summary",
  "fleet.silence",
  "flight.current",
  "flight.ended",
  "flight.started",
  "flight.vesselChanged",
  "game.dlc",
  "isru.converters",
  "isru.drills",
  "ksp.revertAvailability",
  "parts.power",
  "recovery.lastSummary",
  "reliability.parts",
  "reliability.summary",
  "robotics.available",
  "robotics.servos",
  "science.archive",
  "science.experimentBreakdown",
  "science.experiments",
  "science.instruments",
  "science.lab",
  "science.sensors",
  "spaceCenter.astronautComplex",
  "spaceCenter.crewRoster",
  "spaceCenter.launchSites",
  "spaceCenter.partsAvailable",
  "spaceCenter.pois",
  "spaceCenter.savedShips",
  "spaceCenter.scene",
  "system.bodies",
  "system.vessels",
  "target.available",
  "time.calendar",
  "time.warp",
  "vessel.attitude",
  "vessel.comms",
  "vessel.control",
  "vessel.crew",
  "vessel.dock",
  "vessel.flight",
  "vessel.identity",
  "vessel.landing",
  "vessel.maneuver",
  "vessel.orbit",
  "vessel.orbit.truth",
  "vessel.parts",
  "vessel.physics.mode",
  "vessel.propulsion",
  "vessel.resources",
  "vessel.structure",
  "vessel.surface",
  "vessel.target",
  "vessel.thermal",
] as const;
