//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value — with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.

import type {
  CareerMode,
  CareerStatus,
  CommsConnectivity,
  CommsControlState,
  CommsDataRate,
  CommsDelay,
  CommsLinkMargin,
  CommsLinkQuality,
  CommsNetwork,
  CommsPath,
  CommsSignalStrength,
  DeployedEntry,
  DockAlignment,
  ExperimentEntry,
  GameDlc,
  InstrumentEntry,
  KosProcessorInfo,
  LabEntry,
  PartsPower,
  RevertAvailability,
  RoboticsAvailability,
  ScanningVesselEntry,
  SensorEntry,
  ServoEntry,
  SystemBodies,
  SystemVessels,
  VesselAttitude,
  VesselComms,
  VesselControl,
  VesselCrew,
  VesselFlight,
  VesselIdentity,
  VesselManeuver,
  VesselOrbit,
  VesselOrbitTruth,
  VesselPhysicsMode,
  VesselPropulsion,
  VesselResources,
  VesselStructure,
  VesselSurface,
  VesselTarget,
  VesselThermal,
  WarpState,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "career.mode": CareerMode;
  "career.status": CareerStatus;
  "comms.connectivity": CommsConnectivity;
  "comms.controlState": CommsControlState;
  "comms.dataRate": CommsDataRate;
  "comms.delay": CommsDelay;
  "comms.linkMargin": CommsLinkMargin;
  "comms.linkQuality": CommsLinkQuality;
  "comms.network": CommsNetwork;
  "comms.path": CommsPath;
  "comms.signalStrength": CommsSignalStrength;
  "game.dlc": GameDlc;
  "kos.processors": KosProcessorInfo[];
  "ksp.revertAvailability": RevertAvailability;
  "parts.power": PartsPower;
  "parts.robotics": ServoEntry[];
  "robotics.available": RoboticsAvailability;
  "scansat.scanningVessels": ScanningVesselEntry[];
  "science.deployed": DeployedEntry[];
  "science.experiments": ExperimentEntry[];
  "science.instruments": InstrumentEntry[];
  "science.lab": LabEntry[];
  "science.sensors": SensorEntry[];
  "system.bodies": SystemBodies;
  "system.vessels": SystemVessels;
  "time.warp": WarpState;
  "vessel.attitude": VesselAttitude;
  "vessel.comms": VesselComms;
  "vessel.control": VesselControl;
  "vessel.crew": VesselCrew;
  "vessel.dock": DockAlignment;
  "vessel.flight": VesselFlight;
  "vessel.identity": VesselIdentity;
  "vessel.maneuver": VesselManeuver;
  "vessel.orbit": VesselOrbit;
  "vessel.orbit.truth": VesselOrbitTruth;
  "vessel.physics.mode": VesselPhysicsMode;
  "vessel.propulsion": VesselPropulsion;
  "vessel.resources": VesselResources;
  "vessel.structure": VesselStructure;
  "vessel.surface": VesselSurface;
  "vessel.target": VesselTarget;
  "vessel.thermal": VesselThermal;
}

export const GENERATED_TOPIC_IDS = [
  "career.mode",
  "career.status",
  "comms.connectivity",
  "comms.controlState",
  "comms.dataRate",
  "comms.delay",
  "comms.linkMargin",
  "comms.linkQuality",
  "comms.network",
  "comms.path",
  "comms.signalStrength",
  "game.dlc",
  "kos.processors",
  "ksp.revertAvailability",
  "parts.power",
  "parts.robotics",
  "robotics.available",
  "scansat.scanningVessels",
  "science.deployed",
  "science.experiments",
  "science.instruments",
  "science.lab",
  "science.sensors",
  "system.bodies",
  "system.vessels",
  "time.warp",
  "vessel.attitude",
  "vessel.comms",
  "vessel.control",
  "vessel.crew",
  "vessel.dock",
  "vessel.flight",
  "vessel.identity",
  "vessel.maneuver",
  "vessel.orbit",
  "vessel.orbit.truth",
  "vessel.physics.mode",
  "vessel.propulsion",
  "vessel.resources",
  "vessel.structure",
  "vessel.surface",
  "vessel.target",
  "vessel.thermal",
] as const;
