//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/** The closed unit vocabulary (Sitrep.Contract.Units). */
export type SitrepUnit =
  | "1"
  | "K"
  | "bit/s"
  | "dB"
  | "g"
  | "kN"
  | "kPa"
  | "kW"
  | "kg/m³"
  | "m"
  | "m/s"
  | "m³/s²"
  | "rad"
  | "ratio"
  | "s"
  | "t"
  | "°"
;

/** Declared units for one payload shape, keyed by camelCased field name. */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "CommsDataRate": {
    downBitsPerSec: "bit/s",
    upBitsPerSec: "bit/s",
  },
  "CommsDelay": {
    oneWaySeconds: "s",
  },
  "CommsHop": {
    bandRateBitsPerSec: "bit/s",
    distanceMeters: "m",
  },
  "CommsLinkMargin": {
    decibelMargin: "dB",
  },
  "CommsLinkQuality": {
    value: "ratio",
  },
  "CommsSignalStrength": {
    value: "ratio",
  },
  "OrbitPatch": {
    apA: "m",
    argPe: "°",
    ecc: "1",
    endUt: "s",
    epoch: "s",
    inc: "°",
    lan: "°",
    meanAnomalyAtEpoch: "rad",
    peA: "m",
    period: "s",
    semiLatusRectum: "m",
    semiMinorAxis: "m",
    sma: "m",
    startUt: "s",
  },
  "StageDeltaVEntry": {
    burnTime: "s",
    dryMass: "t",
    dvActual: "m/s",
    dvAsl: "m/s",
    dvVac: "m/s",
    endMass: "t",
    fuelMass: "t",
    startMass: "t",
    thrustActual: "kN",
    thrustAsl: "kN",
    thrustVac: "kN",
    twrActual: "1",
    twrAsl: "1",
    twrVac: "1",
  },
  "StageDeltaVSummary": {
    totalBurnTime: "s",
    totalDvActual: "m/s",
    totalDvAsl: "m/s",
    totalDvVac: "m/s",
  },
  "ThermalHottestPart": {
    internalTemp: "K",
    maxTemp: "K",
    skinMaxTemp: "K",
    skinTemp: "K",
  },
  "VesselFlight": {
    altitudeAsl: "m",
    altitudeTerrain: "m",
    atmDensity: "kg/m³",
    atmosphericTemperature: "K",
    dynamicPressureKPa: "kPa",
    externalTemperature: "K",
    gForce: "g",
    latitude: "°",
    longitude: "°",
    mach: "1",
    orbitalSpeed: "m/s",
    surfaceSpeed: "m/s",
    verticalSpeed: "m/s",
  },
  "VesselLanding": {
    atmosphericTimeToImpact: "s",
    predictedLatitude: "°",
    predictedLongitude: "°",
    predictedRoughness: "m",
    predictedSlopeAngle: "°",
    predictedSlopeHeading: "°",
    predictedTerrainElevation: "m",
    projectedTouchdownSpeed: "m/s",
    roughnessFootprintMeters: "m",
    slopeAngleUnderVessel: "°",
    slopeSampleRadiusMeters: "m",
    terminalVelocity: "m/s",
    terrainElevationUnderVessel: "m",
    terrainPatchExtentMeters: "m",
  },
  "VesselOrbit": {
    argPe: "°",
    ecc: "1",
    epoch: "s",
    inc: "°",
    lan: "°",
    meanAnomalyAtEpoch: "rad",
    mu: "m³/s²",
    sma: "m",
  },
  "VesselPart": {
    currentTemp: "K",
    dryMass: "t",
    maxTemp: "K",
    skinMaxTemp: "K",
    skinTemp: "K",
  },
  "VesselSurface": {
    heightFromTerrain: "m",
  },
  "VesselThermal": {
    heatShieldFlux: "kW",
    heatShieldTemp: "K",
    hottestEngineMaxTemp: "K",
    hottestEngineTemp: "K",
    hottestEngineTempRatio: "ratio",
    maxInternalTempRatio: "ratio",
    maxSkinTempRatio: "ratio",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "comms.dataRate": {
    downBitsPerSec: "bit/s",
    upBitsPerSec: "bit/s",
  },
  "comms.delay": {
    oneWaySeconds: "s",
  },
  "comms.linkMargin": {
    decibelMargin: "dB",
  },
  "comms.linkQuality": {
    value: "ratio",
  },
  "comms.signalStrength": {
    value: "ratio",
  },
  "dv.stages": {
    burnTime: "s",
    dryMass: "t",
    dvActual: "m/s",
    dvAsl: "m/s",
    dvVac: "m/s",
    endMass: "t",
    fuelMass: "t",
    startMass: "t",
    thrustActual: "kN",
    thrustAsl: "kN",
    thrustVac: "kN",
    twrActual: "1",
    twrAsl: "1",
    twrVac: "1",
  },
  "dv.summary": {
    totalBurnTime: "s",
    totalDvActual: "m/s",
    totalDvAsl: "m/s",
    totalDvVac: "m/s",
  },
  "vessel.flight": {
    altitudeAsl: "m",
    altitudeTerrain: "m",
    atmDensity: "kg/m³",
    atmosphericTemperature: "K",
    dynamicPressureKPa: "kPa",
    externalTemperature: "K",
    gForce: "g",
    latitude: "°",
    longitude: "°",
    mach: "1",
    orbitalSpeed: "m/s",
    surfaceSpeed: "m/s",
    verticalSpeed: "m/s",
  },
  "vessel.landing": {
    atmosphericTimeToImpact: "s",
    predictedLatitude: "°",
    predictedLongitude: "°",
    predictedRoughness: "m",
    predictedSlopeAngle: "°",
    predictedSlopeHeading: "°",
    predictedTerrainElevation: "m",
    projectedTouchdownSpeed: "m/s",
    roughnessFootprintMeters: "m",
    slopeAngleUnderVessel: "°",
    slopeSampleRadiusMeters: "m",
    terminalVelocity: "m/s",
    terrainElevationUnderVessel: "m",
    terrainPatchExtentMeters: "m",
  },
  "vessel.orbit": {
    argPe: "°",
    ecc: "1",
    epoch: "s",
    inc: "°",
    lan: "°",
    meanAnomalyAtEpoch: "rad",
    mu: "m³/s²",
    sma: "m",
  },
  "vessel.surface": {
    heightFromTerrain: "m",
  },
  "vessel.thermal": {
    heatShieldFlux: "kW",
    heatShieldTemp: "K",
    hottestEngineMaxTemp: "K",
    hottestEngineTemp: "K",
    hottestEngineTempRatio: "ratio",
    maxInternalTempRatio: "ratio",
    maxSkinTempRatio: "ratio",
  },
};
