//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface RealFuelsEngineEntry
{
	partId?: number;
	partName?: string;
	ignitionsRemaining?: Value<"count">;
	ignitionsUnlimited?: boolean;
	groundIgnitionOnly?: boolean;
	literalZeroIgnitions?: boolean;
	ullageModelled?: boolean;
	ullageStability?: Value<"ratio">;
	ignitionProbability?: Value<"ratio">;
	pressureFed?: boolean;
	feedPressureOk?: boolean;
	ratedBurnTimeSeconds?: Value<"s">;
	ratedContinuousBurnTimeSeconds?: Value<"s">;
	predictedMaximumResiduals?: Value<"ratio">;
}
export interface RealFuelsEngines
{
	ignitionsLimited?: boolean;
	ullageSimulated?: boolean;
	engines?: RealFuelsEngineEntry[];
}
export interface RealFuelsBoiloff
{
	boiloffRate?: Value<"kg/s">;
	cryogenicTankCount?: Value<"count">;
}
