// comm-signal.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["comms.commandCentre", "comms.path", "vessel.identity"],
  optionalChannelFamilies: [],
  commands: [],
} as const;
