// fleet-roster.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [],
  optionalChannelFamilies: [
    "fleet.<guid>.contact",
    "fleet.<guid>.delay",
    "silence.<guid>.state",
  ],
  commands: [],
} as const;
