//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// THIS IS NOT A LIST OF EVERY COMMAND ON THE WIRE, for the same reason the
// topic map is not one: a command in a DYNAMIC namespace is addressed per
// subject at runtime and has no tagged type to find. What is below is every
// command that can be named before the game is running.

import type {
  Rp1BuildRepeatArgs,
  Rp1BuildStartArgs,
  Rp1ComplexDismantleArgs,
  Rp1ComplexModifyArgs,
  Rp1ComplexNewArgs,
  Rp1ComplexRenameArgs,
  Rp1ComplexRushArgs,
  Rp1ContractPayloadArgs,
  Rp1FacilityUpgradeArgs,
  Rp1FundTargetSetArgs,
  Rp1HireTargetSetArgs,
  Rp1PadDismantleArgs,
  Rp1PadNewArgs,
  Rp1PadRenameArgs,
  Rp1PersonnelAssignArgs,
  Rp1RolloutArgs,
  Rp1StrategyActivateArgs,
  Rp1TargetCancelArgs,
  Rp1TechResearchArgs,
  Rp1ToolAllArgs,
  Rp1ToolingRefitArgs,
  Rp1TrainingEnrolArgs,
  Rp1TrainingLeaveArgs,
  Rp1VehicleArgs,
  Rp1WarpArgs,
} from "./contract.js";
import type {
  CommandResult,
  CommandResultOf,
} from "@ksp-gonogo/sitrep-sdk";

export interface GeneratedCommandArgsMap {
  "rp1.build.repeat": Rp1BuildRepeatArgs;
  "rp1.build.start": Rp1BuildStartArgs;
  "rp1.complex.dismantle": Rp1ComplexDismantleArgs;
  "rp1.complex.modify": Rp1ComplexModifyArgs;
  "rp1.complex.new": Rp1ComplexNewArgs;
  "rp1.complex.rename": Rp1ComplexRenameArgs;
  "rp1.complex.rush": Rp1ComplexRushArgs;
  "rp1.contracts.setPayload": Rp1ContractPayloadArgs;
  "rp1.facility.upgrade": Rp1FacilityUpgradeArgs;
  "rp1.fundTarget.cancel": Rp1TargetCancelArgs;
  "rp1.fundTarget.set": Rp1FundTargetSetArgs;
  "rp1.hireTarget.cancel": Rp1TargetCancelArgs;
  "rp1.hireTarget.set": Rp1HireTargetSetArgs;
  "rp1.pad.dismantle": Rp1PadDismantleArgs;
  "rp1.pad.new": Rp1PadNewArgs;
  "rp1.pad.rename": Rp1PadRenameArgs;
  "rp1.personnel.assign": Rp1PersonnelAssignArgs;
  "rp1.strategy.activate": Rp1StrategyActivateArgs;
  "rp1.tech.research": Rp1TechResearchArgs;
  "rp1.tooling.refit": Rp1ToolingRefitArgs;
  "rp1.tooling.toolAll": Rp1ToolAllArgs;
  "rp1.training.cancel": Rp1TrainingLeaveArgs;
  "rp1.training.enrol": Rp1TrainingEnrolArgs;
  "rp1.training.remove": Rp1TrainingLeaveArgs;
  "rp1.vehicle.rollback": Rp1VehicleArgs;
  "rp1.vehicle.rollout": Rp1RolloutArgs;
  "rp1.vehicle.scrap": Rp1VehicleArgs;
  "rp1.warp.toComplete": Rp1WarpArgs;
  "rp1.warp.toFundTarget": Rp1WarpArgs;
}

export interface GeneratedCommandReplyMap {
  "rp1.build.repeat": CommandResult;
  "rp1.build.start": CommandResult;
  "rp1.complex.dismantle": CommandResultOf<Record<string, unknown>>;
  "rp1.complex.modify": CommandResultOf<Record<string, unknown>>;
  "rp1.complex.new": CommandResultOf<Record<string, unknown>>;
  "rp1.complex.rename": CommandResult;
  "rp1.complex.rush": CommandResult;
  "rp1.contracts.setPayload": CommandResultOf<Record<string, unknown>>;
  "rp1.facility.upgrade": CommandResultOf<Record<string, unknown>>;
  "rp1.fundTarget.cancel": CommandResult;
  "rp1.fundTarget.set": CommandResult;
  "rp1.hireTarget.cancel": CommandResult;
  "rp1.hireTarget.set": CommandResult;
  "rp1.pad.dismantle": CommandResult;
  "rp1.pad.new": CommandResultOf<Record<string, unknown>>;
  "rp1.pad.rename": CommandResult;
  "rp1.personnel.assign": CommandResult;
  "rp1.strategy.activate": CommandResult;
  "rp1.tech.research": CommandResult;
  "rp1.tooling.refit": CommandResult;
  "rp1.tooling.toolAll": CommandResult;
  "rp1.training.cancel": CommandResult;
  "rp1.training.enrol": CommandResult;
  "rp1.training.remove": CommandResult;
  "rp1.vehicle.rollback": CommandResult;
  "rp1.vehicle.rollout": CommandResult;
  "rp1.vehicle.scrap": CommandResult;
  "rp1.warp.toComplete": CommandResult;
  "rp1.warp.toFundTarget": CommandResult;
}

export const GENERATED_COMMAND_IDS = [
  "rp1.build.repeat",
  "rp1.build.start",
  "rp1.complex.dismantle",
  "rp1.complex.modify",
  "rp1.complex.new",
  "rp1.complex.rename",
  "rp1.complex.rush",
  "rp1.contracts.setPayload",
  "rp1.facility.upgrade",
  "rp1.fundTarget.cancel",
  "rp1.fundTarget.set",
  "rp1.hireTarget.cancel",
  "rp1.hireTarget.set",
  "rp1.pad.dismantle",
  "rp1.pad.new",
  "rp1.pad.rename",
  "rp1.personnel.assign",
  "rp1.strategy.activate",
  "rp1.tech.research",
  "rp1.tooling.refit",
  "rp1.tooling.toolAll",
  "rp1.training.cancel",
  "rp1.training.enrol",
  "rp1.training.remove",
  "rp1.vehicle.rollback",
  "rp1.vehicle.rollout",
  "rp1.vehicle.scrap",
  "rp1.warp.toComplete",
  "rp1.warp.toFundTarget",
] as const;
