//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface Rp1CentreEntry
{
	kscName?: string;
	isActive?: boolean;
	engineers?: Value<"count">;
	unassignedEngineers?: Value<"count">;
	launchComplexCount?: Value<"count">;
	anyOperational?: boolean;
	groundStation?: string;
}
export interface Rp1ComplexEntry
{
	kscName?: string;
	lcId?: string;
	name?: string;
	lcType?: string;
	isOperational?: boolean;
	isRushing?: boolean;
	engineers?: Value<"count">;
	maxEngineers?: Value<"count">;
	efficiency?: Value<"ratio">;
	canIntegrate?: boolean;
	rate?: Value<"bp/s">;
	humanRated?: boolean;
	massMin?: Value<"t">;
	massMax?: Value<"t">;
}
export interface Rp1BuildItemEntry
{
	kscName?: string;
	lcId?: string;
	shipName?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1WarehouseItemEntry
{
	kscName?: string;
	lcId?: string;
	shipName?: string;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1PadEntry
{
	kscName?: string;
	lcId?: string;
	padId?: string;
	name?: string;
	launchSiteName?: string;
	level?: Value<"count">;
	fractionalLevel?: Value<"ratio">;
	state?: string;
}
export interface Rp1OperationEntry
{
	kscName?: string;
	lcId?: string;
	launchPadId?: string;
	type?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	associatedVesselId?: string;
}
export interface Rp1ResearchEntry
{
	techId?: string;
	techName?: string;
	scienceCost?: Value<"count">;
	progress?: Value<"count">;
	progressRatio?: Value<"ratio">;
	workRate?: Value<"ratio">;
	rate?: Value<"count">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	startYear?: Value<"count">;
	endYear?: Value<"count">;
}
export interface Rp1Personnel
{
	totalEngineers?: Value<"count">;
	researchers?: Value<"count">;
	applicants?: Value<"count">;
}
export interface Rp1Confidence
{
	confidence?: Value<"confidence">;
	earned?: Value<"confidence">;
}
