//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface Rp1BuildRepeatArgs
{
	id?: string;
}
export interface Rp1RolloutArgs
{
	id?: string;
	pad?: string;
}
export interface Rp1VehicleArgs
{
	id?: string;
}
export interface Rp1ComplexRushArgs
{
	lcId?: string;
	rushing?: boolean;
}
export interface Rp1PersonnelAssignArgs
{
	lcId?: string;
	engineers?: number;
}
export interface Rp1BuildStartArgs
{
	craftFile?: string;
	facility?: number;
	lcId?: string;
}
export interface Rp1FacilityUpgradeArgs
{
	facility?: string;
}
export interface Rp1TechResearchArgs
{
	techId?: string;
}
export interface Rp1TargetCancelArgs
{
}
export interface Rp1HireTargetSetArgs
{
	targetCount?: number;
	reserveFunds?: number;
	lcId?: string;
}
export interface Rp1FundTargetSetArgs
{
	targetFunds?: number;
}
export interface Rp1TrainingEnrolArgs
{
	templateId?: string;
	crew?: string[];
}
export interface Rp1TrainingLeaveArgs
{
	crewName?: string;
}
export interface Rp1ComplexSizeArgs
{
	sizeMaxWidth?: number;
	sizeMaxHeight?: number;
	sizeMaxDepth?: number;
}
export interface Rp1ComplexNewArgs
{
	kscName?: string;
	name?: string;
	massMax?: number;
	size?: Rp1ComplexSizeArgs;
	humanRated?: boolean;
	resources?: { [key:string]: number };
	assignEngineersOnComplete?: boolean;
}
export interface Rp1ComplexModifyArgs
{
	lcId?: string;
	massMax?: number;
	size?: Rp1ComplexSizeArgs;
	humanRated?: boolean;
	resources?: { [key:string]: number };
	assignEngineersOnComplete?: boolean;
}
export interface Rp1ComplexRenameArgs
{
	lcId?: string;
	name?: string;
}
export interface Rp1ComplexDismantleArgs
{
	lcId?: string;
}
export interface Rp1PadNewArgs
{
	lcId?: string;
	name?: string;
}
export interface Rp1PadRenameArgs
{
	lcId?: string;
	padId?: string;
	name?: string;
}
export interface Rp1PadDismantleArgs
{
	lcId?: string;
	padId?: string;
}
export interface Rp1WarpArgs
{
}
export interface Rp1ToolAllArgs
{
}
export interface Rp1ToolingRefitArgs
{
	partId?: string;
	diameter?: number;
	length?: number;
	rfType?: string;
}
export interface Rp1ContractPayloadArgs
{
	commsPayload?: number;
	weatherPayload?: number;
}
export interface Rp1CentreEntry
{
	kscName?: string;
	kscDisplayName?: string;
	isActive?: boolean;
	engineers?: Value<"count">;
	unassignedEngineers?: Value<"count">;
	launchComplexCount?: Value<"count">;
	anyOperational?: boolean;
	groundStation?: string;
	salaryPerDay?: Value<"f/day">;
	idleSalaryPerDay?: Value<"f/day">;
	upkeepPerDay?: Value<"f/day">;
}
export interface Rp1ComplexEntry
{
	kscName?: string;
	kscDisplayName?: string;
	lcId?: string;
	name?: string;
	lcType?: string;
	isOperational?: boolean;
	isRushing?: boolean;
	engineers?: Value<"count">;
	maxEngineers?: Value<"count">;
	efficiency?: Value<"ratio">;
	efficiencySharedWith?: string[];
	canIntegrate?: boolean;
	rate?: Value<"bp/s">;
	humanRated?: boolean;
	launchPadCount?: Value<"count">;
	massMin?: Value<"t">;
	massMax?: Value<"t">;
	massOrig?: Value<"t">;
	sizeMaxHeight?: Value<"m">;
	sizeMaxWidth?: Value<"m">;
	sizeMaxDepth?: Value<"m">;
	resourcesHandled?: string[];
	salaryPerDay?: Value<"f/day">;
	upkeepPerDay?: Value<"f/day">;
}
export interface Rp1BuildItemEntry
{
	id?: string;
	shipId?: string;
	kscName?: string;
	lcId?: string;
	shipName?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1WarehouseItemEntry
{
	id?: string;
	shipId?: string;
	rolloutRefusals?: string[];
	kscName?: string;
	lcId?: string;
	shipName?: string;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1PadEntry
{
	kscName?: string;
	lcId?: string;
	padId?: string;
	name?: string;
	launchSiteName?: string;
	level?: Value<"count">;
	fractionalLevel?: Value<"ratio">;
	state?: string;
	isOperational?: boolean;
	hasVesselWaiting?: boolean;
	waitingVesselName?: string;
}
export interface Rp1OperationEntry
{
	kscName?: string;
	lcId?: string;
	launchPadId?: string;
	type?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	blockingPeers?: Value<"count">;
	cost?: Value<"funds">;
	associatedVesselId?: string;
}
export interface Rp1ConstructionEntry
{
	kscName?: string;
	lcId?: string;
	kind?: string;
	name?: string;
	facilityType?: string;
	currentLevel?: Value<"count">;
	targetLevel?: Value<"count">;
	isModify?: boolean;
	engineersToReadd?: Value<"count">;
	padId?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	workRate?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	spentCost?: Value<"funds">;
	spentRushCost?: Value<"funds">;
}
export interface Rp1ResearchEntry
{
	techId?: string;
	techName?: string;
	scienceCost?: Value<"count">;
	progress?: Value<"count">;
	progressRatio?: Value<"ratio">;
	workRate?: Value<"ratio">;
	rate?: Value<"count">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	startYear?: Value<"count">;
	endYear?: Value<"count">;
}
export interface Rp1Personnel
{
	totalEngineers?: Value<"count">;
	researchers?: Value<"count">;
	applicants?: Value<"count">;
	engineerSalaryPerDay?: Value<"f/day">;
	researcherSalaryPerDay?: Value<"f/day">;
	engineerSalaryPerYear?: Value<"funds">;
	researcherSalaryPerYear?: Value<"funds">;
	idleSalaryMult?: Value<"ratio">;
	hireTarget?: Rp1HireTarget;
}
export interface Rp1RushTerms
{
	rateMult?: Value<"ratio">;
	salaryMult?: Value<"ratio">;
}
export interface Rp1Confidence
{
	confidence?: Value<"confidence">;
	earned?: Value<"confidence">;
}
export interface Rp1ProgramEntry
{
	name?: string;
	title?: string;
	state?: string;
	speed?: string;
	slots?: Value<"count">;
	isHumanSpaceflight?: boolean;
	nominalDurationSeconds?: Value<"s">;
	acceptedUt?: Value<"ut">;
	deadlineUt?: Value<"ut">;
	objectivesCompletedUt?: Value<"ut">;
	completedUt?: Value<"ut">;
	lastPaymentUt?: Value<"ut">;
	fracElapsed?: Value<"ratio">;
	totalFunding?: Value<"funds">;
	fundsPaidOut?: Value<"funds">;
	fundsRemaining?: Value<"funds">;
	fundingCurve?: string;
	confidenceCost?: Value<"confidence">;
	repDeltaOnCompletePerYearEarly?: Value<"rep">;
	repPenaltyPerYearLate?: Value<"rep">;
	repPenaltyAssessed?: Value<"rep">;
	requirementsMet?: boolean;
	objectivesMet?: boolean;
	canAccept?: boolean;
	canComplete?: boolean;
	requirementsText?: string;
	objectivesText?: string;
	durationSeconds?: Value<"s">;
	speedOptions?: Rp1ProgramSpeedOption[];
	programsToDisableOnAccept?: string[];
	fundingPayments?: Rp1ProgramPaymentEntry[];
}
export interface Rp1ProgramSlots
{
	maxSlots?: Value<"count">;
	usedSlots?: Value<"count">;
	freeSlots?: Value<"count">;
	activeCount?: Value<"count">;
	completedCount?: Value<"count">;
}
export interface Rp1ProgramSpeedOption
{
	speed?: string;
	confidenceCost?: Value<"confidence">;
	durationSeconds?: Value<"s">;
}
export interface Rp1ProgramPaymentEntry
{
	year?: Value<"count">;
	funds?: Value<"funds">;
	cumulativeFunds?: Value<"funds">;
}
export interface Rp1FundingCurveKey
{
	frac?: Value<"ratio">;
	paidFraction?: Value<"ratio">;
	inTangent?: Value<"1">;
	outTangent?: Value<"1">;
}
export interface Rp1FundingCurveEntry
{
	name?: string;
	isDefault?: boolean;
	keys?: Rp1FundingCurveKey[];
}
export interface Rp1CrewEntry
{
	name?: string;
	retired?: boolean;
	retiresAtUt?: Value<"ut">;
	latestRetiresAtUt?: Value<"ut">;
	retirementExtensionUsedSeconds?: Value<"s">;
	trainingCourse?: string;
	trainingType?: string;
	trainingTarget?: string;
	trainingStarted?: boolean;
	trainingFractionComplete?: Value<"ratio">;
	trainingFinishesAtUt?: Value<"ut">;
	nextTrainingExpiryUt?: Value<"ut">;
	nextTrainingExpiryTarget?: string;
	trainingExpiryCount?: Value<"count">;
}
export interface Rp1CrewProgram
{
	retirementEnabled?: boolean;
	crewRnREnabled?: boolean;
	missionTrainingEnabled?: boolean;
	proficiencyTrainingRate?: Value<"1">;
	missionTrainingRate?: Value<"1">;
	retirementExtensionCapSeconds?: Value<"s">;
	courses?: Value<"count">;
	coursesStarted?: Value<"count">;
	crewInTraining?: Value<"count">;
}
export interface Rp1BuildableCraftEntry
{
	craftFile?: string;
	shipName?: string;
	facility?: number;
	partCount?: Value<"count">;
	mass?: Value<"t">;
	cost?: Value<"funds">;
	missingParts?: string[];
	lockedParts?: string[];
	unpurchasedParts?: string[];
	complexes?: Rp1BuildableComplex[];
}
export interface Rp1BuildableComplex
{
	lcId?: string;
	name?: string;
	kscName?: string;
	kscDisplayName?: string;
	eligible?: boolean;
	refusals?: string[];
}
export interface Rp1HireTarget
{
	active?: boolean;
	targetCount?: Value<"count">;
	currentCount?: Value<"count">;
	leftToHire?: Value<"count">;
	isResearch?: boolean;
	lcId?: string;
	timeLeft?: Value<"s">;
}
export interface Rp1FundTarget
{
	active?: boolean;
	targetFunds?: Value<"funds">;
	originalFunds?: Value<"funds">;
	timeLeft?: Value<"s">;
}
export interface Rp1TrainingCourseEntry
{
	id?: string;
	name?: string;
	description?: string;
	type?: string;
	target?: string;
	students?: string[];
	seatMin?: Value<"count">;
	seatMax?: Value<"count">;
	started?: boolean;
	completed?: boolean;
	completesAtUt?: Value<"ut">;
	studentsAvailableAtUt?: Value<"ut">;
	isTemporary?: boolean;
}
export interface Rp1TrainingTemplateEntry
{
	id?: string;
	name?: string;
	description?: string;
	type?: string;
	target?: string;
	baseTime?: Value<"s">;
	seatMin?: Value<"count">;
	seatMax?: Value<"count">;
	unlocked?: boolean;
	isTemporary?: boolean;
}
export interface Rp1ToolingEntry
{
	partTitle?: string;
	toolingType?: string;
	toolingTypeTitle?: string;
	parameterSummary?: string;
	tooled?: boolean;
	toolingCost?: Value<"funds">;
	untooledSurcharge?: Value<"funds">;
	partId?: string;
	symmetryCounterparts?: Value<"count">;
	refittable?: boolean;
}
export interface Rp1Tooling
{
	toolAllCost?: Value<"funds">;
	untooledCount?: Value<"count">;
	parts?: Rp1ToolingEntry[];
}
export interface Rp1BuildCost
{
	vehicleCost?: Value<"funds">;
	untooledSurcharge?: Value<"funds">;
	toolingCost?: Value<"funds">;
	unlockCost?: Value<"funds">;
	rolloutCost?: Value<"funds">;
	requiredTechs?: string[];
}
export interface Rp1CareerEventEntry
{
	ut?: Value<"ut">;
	kind?: string;
	name?: string;
	detail?: string;
	launchId?: string;
	repChange?: Value<"rep">;
	cost?: Value<"funds">;
	isAdd?: boolean;
	builtAt?: string;
}
export interface Rp1CareerEvents
{
	enabled?: boolean;
	events?: Rp1CareerEventEntry[];
}
export interface Rp1StrategyActivateArgs
{
	strategyId?: string;
	factor?: number;
}
export interface Rp1LeaderEntry
{
	strategyId?: string;
	setupFunds?: Value<"funds">;
	setupScience?: Value<"science">;
	setupReputation?: Value<"rep">;
	setupConfidence?: Value<"confidence">;
	deactivateReputation?: Value<"rep">;
	removeOnDeactivate?: boolean;
	reactivateCooldown?: Value<"s">;
	canRemoveFromUt?: Value<"ut">;
	freeToRemoveFromUt?: Value<"ut">;
}
