//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface Rp1BuildRepeatArgs
{
	id?: string;
}
export interface Rp1CentreEntry
{
	kscName?: string;
	isActive?: boolean;
	engineers?: Value<"count">;
	unassignedEngineers?: Value<"count">;
	launchComplexCount?: Value<"count">;
	anyOperational?: boolean;
	groundStation?: string;
}
export interface Rp1ComplexEntry
{
	kscName?: string;
	lcId?: string;
	name?: string;
	lcType?: string;
	isOperational?: boolean;
	isRushing?: boolean;
	engineers?: Value<"count">;
	maxEngineers?: Value<"count">;
	efficiency?: Value<"ratio">;
	canIntegrate?: boolean;
	rate?: Value<"bp/s">;
	humanRated?: boolean;
	massMin?: Value<"t">;
	massMax?: Value<"t">;
}
export interface Rp1BuildItemEntry
{
	id?: string;
	kscName?: string;
	lcId?: string;
	shipName?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1WarehouseItemEntry
{
	id?: string;
	kscName?: string;
	lcId?: string;
	shipName?: string;
	cost?: Value<"funds">;
	mass?: Value<"t">;
	humanRated?: boolean;
	launchSite?: string;
	projectType?: string;
}
export interface Rp1PadEntry
{
	kscName?: string;
	lcId?: string;
	padId?: string;
	name?: string;
	launchSiteName?: string;
	level?: Value<"count">;
	fractionalLevel?: Value<"ratio">;
	state?: string;
}
export interface Rp1OperationEntry
{
	kscName?: string;
	lcId?: string;
	launchPadId?: string;
	type?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	blockingPeers?: Value<"count">;
	cost?: Value<"funds">;
	associatedVesselId?: string;
}
export interface Rp1ConstructionEntry
{
	kscName?: string;
	lcId?: string;
	kind?: string;
	name?: string;
	facilityType?: string;
	currentLevel?: Value<"count">;
	targetLevel?: Value<"count">;
	isModify?: boolean;
	engineersToReadd?: Value<"count">;
	padId?: string;
	progress?: Value<"bp">;
	totalPoints?: Value<"bp">;
	progressRatio?: Value<"ratio">;
	workRate?: Value<"ratio">;
	rate?: Value<"bp/s">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	cost?: Value<"funds">;
	spentCost?: Value<"funds">;
	spentRushCost?: Value<"funds">;
}
export interface Rp1ResearchEntry
{
	techId?: string;
	techName?: string;
	scienceCost?: Value<"count">;
	progress?: Value<"count">;
	progressRatio?: Value<"ratio">;
	workRate?: Value<"ratio">;
	rate?: Value<"count">;
	timeLeftSeconds?: Value<"s">;
	stalled?: boolean;
	startYear?: Value<"count">;
	endYear?: Value<"count">;
}
export interface Rp1Personnel
{
	totalEngineers?: Value<"count">;
	researchers?: Value<"count">;
	applicants?: Value<"count">;
}
export interface Rp1Confidence
{
	confidence?: Value<"confidence">;
	earned?: Value<"confidence">;
}
export interface Rp1ProgramEntry
{
	name?: string;
	title?: string;
	state?: string;
	speed?: string;
	slots?: Value<"count">;
	isHumanSpaceflight?: boolean;
	nominalDurationSeconds?: Value<"s">;
	acceptedUt?: Value<"ut">;
	deadlineUt?: Value<"ut">;
	objectivesCompletedUt?: Value<"ut">;
	completedUt?: Value<"ut">;
	lastPaymentUt?: Value<"ut">;
	fracElapsed?: Value<"ratio">;
	totalFunding?: Value<"funds">;
	fundsPaidOut?: Value<"funds">;
	fundsRemaining?: Value<"funds">;
	fundingCurve?: string;
	confidenceCost?: Value<"confidence">;
	repDeltaOnCompletePerYearEarly?: Value<"rep">;
	repPenaltyPerYearLate?: Value<"rep">;
	repPenaltyAssessed?: Value<"rep">;
	requirementsMet?: boolean;
	objectivesMet?: boolean;
	canAccept?: boolean;
	canComplete?: boolean;
	requirementsText?: string;
	objectivesText?: string;
	durationSeconds?: Value<"s">;
	speedOptions?: Rp1ProgramSpeedOption[];
	programsToDisableOnAccept?: string[];
	fundingPayments?: Rp1ProgramPaymentEntry[];
}
export interface Rp1ProgramSlots
{
	maxSlots?: Value<"count">;
	usedSlots?: Value<"count">;
	freeSlots?: Value<"count">;
	activeCount?: Value<"count">;
	completedCount?: Value<"count">;
}
export interface Rp1ProgramSpeedOption
{
	speed?: string;
	confidenceCost?: Value<"confidence">;
	durationSeconds?: Value<"s">;
}
export interface Rp1ProgramPaymentEntry
{
	year?: Value<"count">;
	funds?: Value<"funds">;
	cumulativeFunds?: Value<"funds">;
}
export interface Rp1FundingCurveKey
{
	frac?: Value<"ratio">;
	paidFraction?: Value<"ratio">;
	inTangent?: Value<"1">;
	outTangent?: Value<"1">;
}
export interface Rp1FundingCurveEntry
{
	name?: string;
	isDefault?: boolean;
	keys?: Rp1FundingCurveKey[];
}
export interface Rp1CrewEntry
{
	name?: string;
	retired?: boolean;
	retiresAtUt?: Value<"ut">;
	latestRetiresAtUt?: Value<"ut">;
	retirementExtensionUsedSeconds?: Value<"s">;
	trainingCourse?: string;
	trainingType?: string;
	trainingTarget?: string;
	trainingStarted?: boolean;
	trainingFractionComplete?: Value<"ratio">;
	trainingFinishesAtUt?: Value<"ut">;
	nextTrainingExpiryUt?: Value<"ut">;
	nextTrainingExpiryTarget?: string;
	trainingExpiryCount?: Value<"count">;
}
export interface Rp1CrewProgram
{
	retirementEnabled?: boolean;
	crewRnREnabled?: boolean;
	missionTrainingEnabled?: boolean;
	proficiencyTrainingRate?: Value<"1">;
	missionTrainingRate?: Value<"1">;
	retirementExtensionCapSeconds?: Value<"s">;
	courses?: Value<"count">;
	coursesStarted?: Value<"count">;
	crewInTraining?: Value<"count">;
}
