//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.
//
// THIS IS NOT A LIST OF EVERY TOPIC ON THE WIRE, and it cannot become one.
// A DYNAMIC namespace (`fleet.`, `silence.`, `currency.`, vessel part-actions,
// and an Uplink's own) is registered at RUNTIME through
// `IUplinkHost.RegisterDynamicNamespace` and materialises its topics per
// subject, so no [SitrepTopic]-tagged type exists for reflection to find and
// nothing about it appears below. Asking this file "is there per-vessel X"
// gets a confident no for a topic that has been published all along:
// `fleet.<guid>.orbit` was surveyed as missing that way. To enumerate the
// dynamic half, grep the mod for `RegisterDynamicNamespace` instead.

import type {
  Rp1BuildItemEntry,
  Rp1CentreEntry,
  Rp1ComplexEntry,
  Rp1Confidence,
  Rp1OperationEntry,
  Rp1PadEntry,
  Rp1Personnel,
  Rp1ProgramEntry,
  Rp1ProgramSlots,
  Rp1ResearchEntry,
  Rp1WarehouseItemEntry,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "rp1.buildQueue": Rp1BuildItemEntry[];
  "rp1.centres": Rp1CentreEntry[];
  "rp1.complexes": Rp1ComplexEntry[];
  "rp1.confidence": Rp1Confidence;
  "rp1.operations": Rp1OperationEntry[];
  "rp1.pads": Rp1PadEntry[];
  "rp1.personnel": Rp1Personnel;
  "rp1.programSlots": Rp1ProgramSlots;
  "rp1.programs": Rp1ProgramEntry[];
  "rp1.research": Rp1ResearchEntry[];
  "rp1.warehouse": Rp1WarehouseItemEntry[];
}

export const GENERATED_TOPIC_IDS = [
  "rp1.buildQueue",
  "rp1.centres",
  "rp1.complexes",
  "rp1.confidence",
  "rp1.operations",
  "rp1.pads",
  "rp1.personnel",
  "rp1.programSlots",
  "rp1.programs",
  "rp1.research",
  "rp1.warehouse",
] as const;
