//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/** Every token first-party payloads use (Sitrep.Contract.Units). */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "K"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "bp"
  | "bp/s"
  | "confidence"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "h"
  | "id"
  | "isp"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete, and a typo in first-party
 * code is still caught at codegen time by the catalog check. The open arm
 * exists because a third-party Uplink CANNOT add to Sitrep.Contract.Units:
 * it is a const-string class compiled into the contract assembly. Closing
 * this union would therefore have meant an Uplink could never declare a
 * unit at all, which contradicts third parties being first-class.
 *
 * A consumer teaches the client what an unknown symbol MEANS by calling
 * registerUnit from @ksp-gonogo/ui-kit. Until it does, the value still
 * renders, bare and unscaled.
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/** Declared units for one payload shape, keyed by camelCased field name. */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "Rp1BuildItemEntry": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    progress: "bp",
    progressRatio: "ratio",
    projectType: "enum",
    rate: "bp/s",
    shipId: "id",
    shipName: "text",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
  },
  "Rp1BuildRepeatArgs": {
    id: "id",
  },
  "Rp1BuildStartArgs": {
    craftFile: "id",
    facility: "enum",
    lcId: "id",
  },
  "Rp1BuildableComplex": {
    eligible: "flag",
    kscDisplayName: "text",
    kscName: "id",
    lcId: "id",
    name: "text",
    refusals: "text",
  },
  "Rp1BuildableCraftEntry": {
    cost: "funds",
    craftFile: "id",
    facility: "enum",
    lockedParts: "text",
    mass: "t",
    missingParts: "text",
    partCount: "count",
    shipName: "text",
    unpurchasedParts: "text",
  },
  "Rp1CentreEntry": {
    anyOperational: "flag",
    engineers: "count",
    groundStation: "id",
    idleSalaryPerDay: "f/day",
    isActive: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchComplexCount: "count",
    salaryPerDay: "f/day",
    unassignedEngineers: "count",
    upkeepPerDay: "f/day",
  },
  "Rp1ComplexEntry": {
    canIntegrate: "flag",
    efficiency: "ratio",
    efficiencySharedWith: "id",
    engineers: "count",
    humanRated: "flag",
    isOperational: "flag",
    isRushing: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchPadCount: "count",
    lcId: "id",
    lcType: "enum",
    massMax: "t",
    massMin: "t",
    massOrig: "t",
    maxEngineers: "count",
    name: "text",
    rate: "bp/s",
    resourcesHandled: "id",
    salaryPerDay: "f/day",
    sizeMaxDepth: "m",
    sizeMaxHeight: "m",
    sizeMaxWidth: "m",
    upkeepPerDay: "f/day",
  },
  "Rp1ComplexRushArgs": {
    lcId: "id",
    rushing: "flag",
  },
  "Rp1Confidence": {
    confidence: "confidence",
    earned: "confidence",
  },
  "Rp1ConstructionEntry": {
    cost: "funds",
    currentLevel: "count",
    engineersToReadd: "count",
    facilityType: "enum",
    isModify: "flag",
    kind: "enum",
    kscName: "id",
    lcId: "id",
    name: "text",
    padId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    spentCost: "funds",
    spentRushCost: "funds",
    stalled: "flag",
    targetLevel: "count",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    workRate: "ratio",
  },
  "Rp1CrewEntry": {
    latestRetiresAtUt: "ut",
    name: "id",
    nextTrainingExpiryTarget: "text",
    nextTrainingExpiryUt: "ut",
    retired: "flag",
    retirementExtensionUsedSeconds: "s",
    retiresAtUt: "ut",
    trainingCourse: "text",
    trainingExpiryCount: "count",
    trainingFinishesAtUt: "ut",
    trainingFractionComplete: "ratio",
    trainingStarted: "flag",
    trainingTarget: "text",
    trainingType: "text",
  },
  "Rp1CrewProgram": {
    courses: "count",
    coursesStarted: "count",
    crewInTraining: "count",
    crewRnREnabled: "flag",
    missionTrainingEnabled: "flag",
    missionTrainingRate: "1",
    proficiencyTrainingRate: "1",
    retirementEnabled: "flag",
    retirementExtensionCapSeconds: "s",
  },
  "Rp1FundingCurveEntry": {
    isDefault: "flag",
    name: "id",
  },
  "Rp1FundingCurveKey": {
    frac: "ratio",
    inTangent: "1",
    outTangent: "1",
    paidFraction: "ratio",
  },
  "Rp1OperationEntry": {
    associatedVesselId: "id",
    blockingPeers: "count",
    cost: "funds",
    kscName: "id",
    launchPadId: "id",
    lcId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    type: "enum",
  },
  "Rp1PadEntry": {
    fractionalLevel: "ratio",
    hasVesselWaiting: "flag",
    kscName: "id",
    launchSiteName: "id",
    lcId: "id",
    level: "count",
    name: "text",
    padId: "id",
    state: "enum",
    waitingVesselName: "text",
  },
  "Rp1Personnel": {
    applicants: "count",
    engineerSalaryPerDay: "f/day",
    engineerSalaryPerYear: "funds",
    idleSalaryMult: "ratio",
    researcherSalaryPerDay: "f/day",
    researcherSalaryPerYear: "funds",
    researchers: "count",
    totalEngineers: "count",
  },
  "Rp1PersonnelAssignArgs": {
    engineers: "count",
    lcId: "id",
  },
  "Rp1ProgramEntry": {
    acceptedUt: "ut",
    canAccept: "flag",
    canComplete: "flag",
    completedUt: "ut",
    confidenceCost: "confidence",
    deadlineUt: "ut",
    durationSeconds: "s",
    fracElapsed: "ratio",
    fundingCurve: "text",
    fundsPaidOut: "funds",
    fundsRemaining: "funds",
    isHumanSpaceflight: "flag",
    lastPaymentUt: "ut",
    name: "id",
    nominalDurationSeconds: "s",
    objectivesCompletedUt: "ut",
    objectivesMet: "flag",
    objectivesText: "text",
    programsToDisableOnAccept: "id",
    repDeltaOnCompletePerYearEarly: "rep",
    repPenaltyAssessed: "rep",
    repPenaltyPerYearLate: "rep",
    requirementsMet: "flag",
    requirementsText: "text",
    slots: "count",
    speed: "enum",
    state: "enum",
    title: "text",
    totalFunding: "funds",
  },
  "Rp1ProgramPaymentEntry": {
    cumulativeFunds: "funds",
    funds: "funds",
    year: "count",
  },
  "Rp1ProgramSlots": {
    activeCount: "count",
    completedCount: "count",
    freeSlots: "count",
    maxSlots: "count",
    usedSlots: "count",
  },
  "Rp1ProgramSpeedOption": {
    confidenceCost: "confidence",
    durationSeconds: "s",
    speed: "enum",
  },
  "Rp1ResearchEntry": {
    endYear: "count",
    progress: "count",
    progressRatio: "ratio",
    rate: "count",
    scienceCost: "count",
    stalled: "flag",
    startYear: "count",
    techId: "id",
    techName: "text",
    timeLeftSeconds: "s",
    workRate: "ratio",
  },
  "Rp1RolloutArgs": {
    id: "id",
    pad: "id",
  },
  "Rp1RushTerms": {
    rateMult: "ratio",
    salaryMult: "ratio",
  },
  "Rp1StrategyActivateArgs": {
    strategyId: "id",
  },
  "Rp1VehicleArgs": {
    id: "id",
  },
  "Rp1WarehouseItemEntry": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    projectType: "enum",
    rolloutRefusals: "text",
    shipId: "id",
    shipName: "text",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "rp1.buildQueue": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    progress: "bp",
    progressRatio: "ratio",
    projectType: "enum",
    rate: "bp/s",
    shipId: "id",
    shipName: "text",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
  },
  "rp1.buildable": {
    cost: "funds",
    craftFile: "id",
    facility: "enum",
    lockedParts: "text",
    mass: "t",
    missingParts: "text",
    partCount: "count",
    shipName: "text",
    unpurchasedParts: "text",
  },
  "rp1.centres": {
    anyOperational: "flag",
    engineers: "count",
    groundStation: "id",
    idleSalaryPerDay: "f/day",
    isActive: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchComplexCount: "count",
    salaryPerDay: "f/day",
    unassignedEngineers: "count",
    upkeepPerDay: "f/day",
  },
  "rp1.complexes": {
    canIntegrate: "flag",
    efficiency: "ratio",
    efficiencySharedWith: "id",
    engineers: "count",
    humanRated: "flag",
    isOperational: "flag",
    isRushing: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchPadCount: "count",
    lcId: "id",
    lcType: "enum",
    massMax: "t",
    massMin: "t",
    massOrig: "t",
    maxEngineers: "count",
    name: "text",
    rate: "bp/s",
    resourcesHandled: "id",
    salaryPerDay: "f/day",
    sizeMaxDepth: "m",
    sizeMaxHeight: "m",
    sizeMaxWidth: "m",
    upkeepPerDay: "f/day",
  },
  "rp1.confidence": {
    confidence: "confidence",
    earned: "confidence",
  },
  "rp1.constructions": {
    cost: "funds",
    currentLevel: "count",
    engineersToReadd: "count",
    facilityType: "enum",
    isModify: "flag",
    kind: "enum",
    kscName: "id",
    lcId: "id",
    name: "text",
    padId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    spentCost: "funds",
    spentRushCost: "funds",
    stalled: "flag",
    targetLevel: "count",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    workRate: "ratio",
  },
  "rp1.crew": {
    latestRetiresAtUt: "ut",
    name: "id",
    nextTrainingExpiryTarget: "text",
    nextTrainingExpiryUt: "ut",
    retired: "flag",
    retirementExtensionUsedSeconds: "s",
    retiresAtUt: "ut",
    trainingCourse: "text",
    trainingExpiryCount: "count",
    trainingFinishesAtUt: "ut",
    trainingFractionComplete: "ratio",
    trainingStarted: "flag",
    trainingTarget: "text",
    trainingType: "text",
  },
  "rp1.crewProgram": {
    courses: "count",
    coursesStarted: "count",
    crewInTraining: "count",
    crewRnREnabled: "flag",
    missionTrainingEnabled: "flag",
    missionTrainingRate: "1",
    proficiencyTrainingRate: "1",
    retirementEnabled: "flag",
    retirementExtensionCapSeconds: "s",
  },
  "rp1.operations": {
    associatedVesselId: "id",
    blockingPeers: "count",
    cost: "funds",
    kscName: "id",
    launchPadId: "id",
    lcId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    type: "enum",
  },
  "rp1.pads": {
    fractionalLevel: "ratio",
    hasVesselWaiting: "flag",
    kscName: "id",
    launchSiteName: "id",
    lcId: "id",
    level: "count",
    name: "text",
    padId: "id",
    state: "enum",
    waitingVesselName: "text",
  },
  "rp1.personnel": {
    applicants: "count",
    engineerSalaryPerDay: "f/day",
    engineerSalaryPerYear: "funds",
    idleSalaryMult: "ratio",
    researcherSalaryPerDay: "f/day",
    researcherSalaryPerYear: "funds",
    researchers: "count",
    totalEngineers: "count",
  },
  "rp1.programFundingCurves": {
    isDefault: "flag",
    name: "id",
  },
  "rp1.programSlots": {
    activeCount: "count",
    completedCount: "count",
    freeSlots: "count",
    maxSlots: "count",
    usedSlots: "count",
  },
  "rp1.programs": {
    acceptedUt: "ut",
    canAccept: "flag",
    canComplete: "flag",
    completedUt: "ut",
    confidenceCost: "confidence",
    deadlineUt: "ut",
    durationSeconds: "s",
    fracElapsed: "ratio",
    fundingCurve: "text",
    fundsPaidOut: "funds",
    fundsRemaining: "funds",
    isHumanSpaceflight: "flag",
    lastPaymentUt: "ut",
    name: "id",
    nominalDurationSeconds: "s",
    objectivesCompletedUt: "ut",
    objectivesMet: "flag",
    objectivesText: "text",
    programsToDisableOnAccept: "id",
    repDeltaOnCompletePerYearEarly: "rep",
    repPenaltyAssessed: "rep",
    repPenaltyPerYearLate: "rep",
    requirementsMet: "flag",
    requirementsText: "text",
    slots: "count",
    speed: "enum",
    state: "enum",
    title: "text",
    totalFunding: "funds",
  },
  "rp1.research": {
    endYear: "count",
    progress: "count",
    progressRatio: "ratio",
    rate: "count",
    scienceCost: "count",
    stalled: "flag",
    startYear: "count",
    techId: "id",
    techName: "text",
    timeLeftSeconds: "s",
    workRate: "ratio",
  },
  "rp1.rushTerms": {
    rateMult: "ratio",
    salaryMult: "ratio",
  },
  "rp1.warehouse": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    projectType: "enum",
    rolloutRefusals: "text",
    shipId: "id",
    shipName: "text",
  },
};

/** The nested payload shape each complex field holds, by its interface name. */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * An entry names the ELEMENT type and says how many of it the field holds:
 * a bare name is one, a leading `*` a string-keyed DICTIONARY of them, and
 * a trailing `[]` a LIST of them. The element is what a consumer indexes
 * into either way, which is the same convention the topic unit map follows
 * for an array Topic.
 *
 * The plural markers are what separate a path something can SAMPLE from a
 * path that only names a field of an element. `contracts.active.agent` is
 * the second kind: `career.status.contracts.active` is an array, so no
 * sample reaches an `agent` under it.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "Rp1BuildableCraftEntry": {
    complexes: "Rp1BuildableComplex[]",
  },
  "Rp1FundingCurveEntry": {
    keys: "Rp1FundingCurveKey[]",
  },
  "Rp1ProgramEntry": {
    fundingPayments: "Rp1ProgramPaymentEntry[]",
    speedOptions: "Rp1ProgramSpeedOption[]",
  },
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "rp1.buildable": {
    complexes: "Rp1BuildableComplex[]",
  },
  "rp1.programFundingCurves": {
    keys: "Rp1FundingCurveKey[]",
  },
  "rp1.programs": {
    fundingPayments: "Rp1ProgramPaymentEntry[]",
    speedOptions: "Rp1ProgramSpeedOption[]",
  },
};
