// contract-manager.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [],
  optionalChannelFamilies: [],
  commands: [
    "career.contract.accept",
    "career.contract.cancel",
    "career.contract.decline",
  ],
} as const;
