//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';
import { PayloadMeta } from '@ksp-gonogo/sitrep-sdk';

export interface CommsLinkQuality
{
	value: Value<"ratio">;
	meta: PayloadMeta;
}
export interface CommsDataRate
{
	upBitsPerSec: Value<"bit/s">;
	downBitsPerSec: Value<"bit/s">;
	meta: PayloadMeta;
}
export interface CommsLinkMargin
{
	decibelMargin: Value<"dB">;
	closesLink: boolean;
	meta: PayloadMeta;
}
export interface RealAntennasHopExt
{
	band?: string;
	techLevel?: Value<"count">;
	modulationBits?: Value<"count">;
	encoder?: string;
	codingRate?: Value<"ratio">;
	requiredEbN0?: Value<"dB">;
	beamwidth?: Value<"°">;
	powerDrawEc?: Value<"units/s">;
	reverseBitsPerSec?: Value<"bit/s">;
}
export interface RealAntennasHopRate
{
	fromNodeId: string;
	toNodeId: string;
	bitsPerSec: Value<"bit/s">;
}
