// GENERATED by scripts/gen-version.mjs from this package's package.json.
// Do not edit by hand — the version is single-sourced from the manifest so
// the exported marker can never drift from the published version. The
// version.gate.test.ts alongside it fails CI if this file goes stale.
export const CLIENT_VERSION = "0.0.1";
