import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { ServerMessage } from "@ksp-gonogo/sitrep-sdk";
import { describe, expect, it, vi } from "vitest";
import { makeMeta } from "./stub-transport";
import {
  type BinaryFrameInfo,
  type StreamFrameInfo,
  type WebSocketLike,
  WebSocketTransport,
} from "./websocket-transport";

/**
 * The BINARY LANE at the transport seam: which lane a frame lands on, what the
 * budget seams see, and what happens to a frame that cannot be read.
 *
 * The frames are the ones the C# writer actually produced
 * (`mod/golden-fixtures/binary-frame.json`, generated by
 * `Sitrep.Core.Tests.BinaryFrameFixtureTests`), not bytes assembled here. This
 * file is one of three places pinned to that artefact, and the only one that
 * puts it through the real transport.
 *
 * A hand-driven socket rather than MSW, because what is under test is the
 * decode branch on `event.data`, and that means handing the transport an
 * `ArrayBuffer` deliberately. MSW's `ws` link is the right tool for the
 * handshake and reconnect tests next door; here it would only stand between
 * the bytes and the branch.
 */

interface FixtureCase {
  name: string;
  topic: string;
  frameBase64: string;
  segmentsBase64: string[];
}

/**
 * Walk up from the test's working directory rather than resolving against
 * `import.meta.url`: this suite runs under jsdom, where `import.meta.url` is
 * an `http:` URL and `fileURLToPath` refuses it.
 */
function fixturePath(): string {
  let directory = process.cwd();
  for (;;) {
    const candidate = resolve(
      directory,
      "mod/golden-fixtures/binary-frame.json",
    );
    if (existsSync(candidate)) return candidate;
    const parent = dirname(directory);
    if (parent === directory) {
      throw new Error(
        `could not find mod/golden-fixtures/binary-frame.json walking up from ${process.cwd()}`,
      );
    }
    directory = parent;
  }
}

/* Narrowed rather than asserted: a golden fixture that has drifted out of shape
   fails HERE, naming the case, instead of surfacing as an unrelated assertion
   failure inside whichever test happens to read the missing field. `in` on an
   object-narrowed unknown is what lets this be written without an assertion. */
function isFixtureCase(value: unknown): value is FixtureCase {
  return (
    typeof value === "object" &&
    value !== null &&
    "name" in value &&
    typeof value.name === "string" &&
    "topic" in value &&
    typeof value.topic === "string" &&
    "frameBase64" in value &&
    typeof value.frameBase64 === "string" &&
    "segmentsBase64" in value &&
    Array.isArray(value.segmentsBase64) &&
    value.segmentsBase64.every((s) => typeof s === "string")
  );
}

function readFixtureCases(json: unknown): FixtureCase[] {
  if (typeof json !== "object" || json === null || !("cases" in json)) {
    throw new Error(`${fixturePath()}: no "cases" key`);
  }
  const { cases } = json;
  if (!Array.isArray(cases)) {
    throw new Error(`${fixturePath()}: "cases" is not an array`);
  }
  return cases.map((entry, i) => {
    if (!isFixtureCase(entry)) {
      throw new Error(`${fixturePath()}: case ${i} is not a FixtureCase`);
    }
    return entry;
  });
}

const FIXTURE = {
  cases: readFixtureCases(JSON.parse(readFileSync(fixturePath(), "utf8"))),
};

function caseNamed(name: string): FixtureCase {
  const found = FIXTURE.cases.find((c) => c.name === name);
  if (!found) throw new Error(`fixture case ${name} is missing`);
  return found;
}

function bytesOf(base64: string): Uint8Array {
  return Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
}

/**
 * UTF-8 bytes in THIS realm's `Uint8Array`.
 *
 * Not `new TextEncoder().encode(...)`, which is Node's under jsdom and returns
 * a buffer from Node's realm: `buffer instanceof ArrayBuffer` is then false
 * against jsdom's global and the transport's `data instanceof ArrayBuffer`
 * branch misses it. That is a property of this test environment, not of the
 * transport (a browser socket delivers a same-realm buffer), but a test that
 * tripped over it would be measuring the realm rather than the decode.
 */
function utf8(text: string): Uint8Array {
  const encoded = new TextEncoder().encode(text);
  const copy = new Uint8Array(encoded.byteLength);
  copy.set(encoded);
  return copy;
}

/** A socket the test drives directly, so `event.data` can be exactly what a real one delivers. */
function makeDrivableSocket() {
  const listeners = new Map<
    string,
    Array<(event: { data: unknown }) => void>
  >();
  let deliver: (data: unknown) => void = () => {};

  class DrivableSocket implements WebSocketLike {
    static readonly OPEN = 1;
    readyState = 1;
    binaryType = "blob";
    readonly sent: string[] = [];
    constructor(_url: string) {
      deliver = (data) => {
        for (const l of listeners.get("message") ?? []) l({ data });
      };
    }
    send(data: string): void {
      this.sent.push(data);
    }
    close(): void {
      this.readyState = 3;
    }
    /* The real overloads, not one widened signature: `WebSocketLike` promises a
       "message" listener an `{ data }` event, and a handler typed to accept
       `unknown` cannot stand in for that. The open/close/error listeners take
       nothing, so the event handed to them is ignored. */
    addEventListener(type: "open", listener: () => void): void;
    addEventListener(type: "close", listener: () => void): void;
    addEventListener(type: "error", listener: () => void): void;
    addEventListener(
      type: "message",
      listener: (event: { data: unknown }) => void,
    ): void;
    addEventListener(
      type: string,
      listener: (event: { data: unknown }) => void,
    ): void {
      const bucket = listeners.get(type) ?? [];
      bucket.push(listener);
      listeners.set(type, bucket);
      if (type === "open") listener({ data: undefined });
    }
  }

  return {
    ctor: DrivableSocket,
    deliver: (data: unknown) => deliver(data),
  };
}

function mountTransport() {
  const socket = makeDrivableSocket();
  const messages: ServerMessage[] = [];
  const streamFrames: StreamFrameInfo[] = [];
  const binaryFrames: BinaryFrameInfo[] = [];
  const transport = new WebSocketTransport({
    url: "ws://localhost:8090",
    WebSocketImpl: socket.ctor,
    onStreamFrame: (info) => streamFrames.push(info),
    onBinaryFrame: (info) => binaryFrames.push(info),
  });
  transport.onMessage((m) => messages.push(m));
  return { transport, socket, messages, streamFrames, binaryFrames };
}

describe("WebSocketTransport on the binary lane", () => {
  it("delivers a C#-written frame as a stream-binary message with its segments", () => {
    const fixture = caseNamed("batch-of-three");
    const { transport, socket, messages } = mountTransport();

    socket.deliver(bytesOf(fixture.frameBase64).buffer);

    expect(messages).toHaveLength(1);
    const message = messages[0];
    expect(message.type).toBe("stream-binary");
    if (message.type !== "stream-binary") return;
    expect(message.topic).toBe(fixture.topic);
    expect(
      message.segments.map((s) => btoa(String.fromCharCode(...s))),
    ).toEqual(fixture.segmentsBase64);

    transport.dispose();
  });

  it("marks the topic carried, the same as a JSON delivery does", () => {
    const fixture = caseNamed("batch-of-three");
    const { transport, socket } = mountTransport();

    expect(transport.carriedChannels).not.toContain(fixture.topic);
    socket.deliver(bytesOf(fixture.frameBase64).buffer);
    expect(transport.carriedChannels).toContain(fixture.topic);

    transport.dispose();
  });

  /**
   * The two budget seams stay separate, and this is the assertion that keeps
   * them so. Folding the lane into `onStreamFrame` would cost nothing to write
   * and would make both numbers meaningless: that one is sized against a ~1 Hz
   * state stream, and media traffic would spend headroom measured for a
   * reconnect storm.
   */
  it("reports a binary frame on its own seam and never on the stream-frame one", () => {
    const fixture = caseNamed("batch-of-three");
    const { transport, socket, streamFrames, binaryFrames } = mountTransport();

    socket.deliver(bytesOf(fixture.frameBase64).buffer);

    expect(streamFrames).toEqual([]);
    expect(binaryFrames).toHaveLength(1);
    expect(binaryFrames[0].topic).toBe(fixture.topic);
    expect(binaryFrames[0].segments).toBe(fixture.segmentsBase64.length);
    // A REAL byte count, unlike StreamFrameInfo.byteLength's UTF-16 length.
    const expectedBytes = fixture.segmentsBase64
      .map((s) => bytesOf(s).byteLength)
      .reduce((a, b) => a + b, 0);
    expect(binaryFrames[0].byteLength).toBe(expectedBytes);

    transport.dispose();
  });

  /**
   * PLANTED CONTROL: the JSON lane still works, and reports on its own seam.
   * A discriminator that sent everything down the binary branch would pass
   * every assertion above and break the whole telemetry stream.
   */
  it("still decodes an ordinary JSON frame delivered as bytes", () => {
    const { transport, socket, messages, streamFrames, binaryFrames } =
      mountTransport();
    const json = JSON.stringify({
      type: "stream-data",
      topic: "vessel.state",
      payload: { altitude: 1 },
      meta: makeMeta({ validAt: 1, deliveredAt: 1 }),
    });

    socket.deliver(utf8(json).buffer);

    expect(messages).toHaveLength(1);
    expect(messages[0].type).toBe("stream-data");
    expect(streamFrames).toHaveLength(1);
    expect(binaryFrames).toEqual([]);

    transport.dispose();
  });

  /**
   * Absence discipline at the receiving end, and the reason the unreadable arm
   * exists at all. A truncated frame is dropped rather than delivered
   * half-read, and it is SAID: at every layer above this, a dropped frame and
   * a quiet channel are the same thing, so the console line is the only place
   * the difference is ever visible.
   */
  it("drops a truncated frame, delivers nothing, and says why", () => {
    const fixture = caseNamed("batch-of-three");
    const { transport, socket, messages, binaryFrames } = mountTransport();
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});

    const full = bytesOf(fixture.frameBase64);
    socket.deliver(full.subarray(0, full.length - 2));

    expect(messages).toEqual([]);
    expect(binaryFrames).toEqual([]);
    expect(warn).toHaveBeenCalledWith(
      expect.stringContaining("segment table sums to"),
    );

    warn.mockRestore();
    transport.dispose();
  });

  it("drops a frame on an unknown lane and names the lane", () => {
    const fixture = caseNamed("batch-of-three");
    const { transport, socket, messages } = mountTransport();
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});

    const frame = bytesOf(fixture.frameBase64);
    frame[1] = 0x42;
    socket.deliver(frame.buffer);

    expect(messages).toEqual([]);
    expect(warn).toHaveBeenCalledWith(
      expect.stringContaining("unknown binary lane 0x42"),
    );

    warn.mockRestore();
    transport.dispose();
  });

  /**
   * Zero segments is a real delivery: the producer had nothing to say this
   * tick. It must reach a subscriber, because a listener that never hears it
   * cannot tell a quiet transmitter from a dead channel, which is the same
   * conflation the truncation test rules out from the other side.
   */
  it("delivers a frame with no segments rather than dropping it", () => {
    const fixture = caseNamed("no-segments");
    const { transport, socket, messages, binaryFrames } = mountTransport();

    socket.deliver(bytesOf(fixture.frameBase64).buffer);

    expect(messages).toHaveLength(1);
    expect(messages[0].type).toBe("stream-binary");
    expect(binaryFrames).toHaveLength(1);
    expect(binaryFrames[0].segments).toBe(0);
    expect(binaryFrames[0].byteLength).toBe(0);

    transport.dispose();
  });
});
