// launch-director.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "career.mode",
    "career.status",
    "crash.hasRecent",
    "crash.lastCrash",
    "spaceCenter.crewRoster",
    "spaceCenter.launchSites",
    "spaceCenter.savedShips",
    "spaceCenter.scene",
    "spaceCenter.state",
    "system.bodies",
    "system.vessels",
    "target.available",
    "vessel.flight",
    "vessel.identity",
  ],
  optionalChannelFamilies: [],
  commands: [
    "ksp.launch",
    "ksp.recover",
    "ksp.revertToEditor",
    "ksp.revertToLaunch",
    "ksp.switchVessel",
    "ksp.toSpaceCenter",
    "ksp.toTrackingStation",
  ],
} as const;
