/**
 * Bake one Uplink's client-bundle hash into the C# const its DLL vouches with.
 *
 * Usage: bake-uplink-hash.ts <GonogoXUplink> [--out <ExpectedClientHash.g.cs>]
 *
 * ## Why this lives in the app rather than in `mod/`
 *
 * The hash has to be of the bundle that SHIPS, and the bundle that ships is the
 * one the app's build writes into `public/uplinks/`. So this builds it with the
 * app's own bundler (`uplink-bundle.ts`, the same function `vite.config.ts`
 * calls) rather than a second one of its own. A release that hashed a
 * differently-built bundle would make the mod vouch for bytes nobody serves,
 * and a hash that cannot match is worse than no hash: it fails as tampering, on
 * every load, for a correctly installed mod.
 *
 * ## Order, which is not the caller's to remember
 *
 * The bundle must exist and be hashed BEFORE the DLL compiles, or the DLL
 * vouches for bytes that are not the ones shipped. `_build-uplink-mod.yml` runs
 * this immediately before `dotnet build` for that reason, and asserts the result
 * with `scripts/client-hash-armed.mjs --require <id>`.
 *
 * ## The generated value IS committed, and that is a commitment
 *
 * A committed hash is stale the moment the client source moves, and a stale hash
 * is not a stale artifact: it is a loader refusal for every operator running
 * that mod, against the correct bundle, reading as tampering. So it is committed
 * only because `bakedClientHash.test.ts` re-runs this command on every CI push
 * and fails on the first byte of drift. Arm an Uplink and you take that on;
 * leaving it at `Value = ""` (which reads as "vouches for nothing") keeps the
 * two-way fallback and no obligation.
 */

import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildUplinkClientBundle } from "../uplink-bundle";
import { UPLINK_BUNDLE_TARGETS } from "../uplink-bundle-targets";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

const die: (message: string) => never = (message) => {
  console.error(`✖ bake-uplink-hash: ${message}`);
  process.exit(1);
};

const [uplinkId, ...rest] = process.argv.slice(2);
if (!uplinkId || uplinkId.startsWith("-")) {
  die("usage: bake-uplink-hash.ts <GonogoXUplink> [--out <path>]");
}

const uplinkDir = join(ROOT, "mod", uplinkId);
const clientDir = join(uplinkDir, "client");
const target = UPLINK_BUNDLE_TARGETS.find((t) => t.clientDir === clientDir);
if (!target) {
  die(
    `${uplinkId} is not one of the clients this build bundles.\n` +
      "  Only a bundle the app emits can be the one an operator fetches, so hashing anything\n" +
      "  else would bake a value the loader can never match. Add it to uplink-bundle-targets.ts\n" +
      "  first, or leave the Uplink unarmed.",
  );
}

/*
 * The scaffold is the opt-in, and its ABSENCE is not a quiet skip.
 *
 * An Uplink whose C# never reads `ExpectedClientHash.Value` would get a .g.cs
 * compiled into the assembly and read by nothing: a mod that reports a null hash
 * while a release step claims to have armed it. That is the exact shape this
 * whole check exists to stop, so it fails instead.
 */
const outPath = resolve(
  rest.includes("--out")
    ? (rest[rest.indexOf("--out") + 1] ?? "")
    : join(uplinkDir, "ExpectedClientHash.g.cs"),
);
if (!existsSync(outPath)) {
  die(
    `${uplinkId} has no ExpectedClientHash.g.cs scaffold at ${outPath}.\n` +
      "  Writing one here would compile a const the Uplink's manifest never reads, so the mod\n" +
      '  would still report no hash while this step reported success. Add the scaffold (Value = "")\n' +
      "  and the `ExpectedClientHash = ...` line to the UplinkManifest first.",
  );
}

const csproj = join(uplinkDir, `${uplinkId}.csproj`);
if (!existsSync(csproj)) die(`${csproj} does not exist`);
const namespace = readFileSync(csproj, "utf8").match(
  /<RootNamespace>([^<]+)<\/RootNamespace>/,
)?.[1];
if (!namespace) {
  die(
    `${csproj} declares no <RootNamespace>, so the generated const would land in a namespace\n` +
      "  the Uplink's own sources cannot see and the build would fail on a name it never wrote.",
  );
}

const stagingDir = mkdtempSync(join(tmpdir(), "gonogo-uplink-bake-"));
const { integrity } = await buildUplinkClientBundle({
  clientDir,
  outFile: join(stagingDir, `${target.id}.client.js`),
});

writeFileSync(
  outPath,
  `// <auto-generated> Written by packages/app/scripts/bake-uplink-hash.ts. DO NOT EDIT.
//
// The sha256 of the client bundle the app's build emits for this Uplink. Empty
// means the DLL vouches for nothing: Manifest.ExpectedClientHash stays null and the
// loader records the mod-hash arm as pending (two-way index==bytes fallback).
//
// A non-empty value is held current by bakedClientHash.test.ts, because one that
// has fallen behind its client source refuses the real bundle on every load:
//   pnpm --filter @ksp-gonogo/app bake-uplink-hash ${uplinkId}
namespace ${namespace}
{
    internal static class ExpectedClientHash
    {
        public const string Value = "${integrity}";
    }
}
`,
);
console.log(`baked ${integrity} -> ${outPath}`);
