#!/usr/bin/env python3
"""
Cut the JetBrains Mono "symbols" faces fonts.css self-hosts beside @fontsource's.

@fontsource ships JetBrains Mono split by script (latin, greek, cyrillic, ...),
and none of its subsets carry the arrows, maths operators, subscripts,
geometric shapes or dingbats the widgets draw (→ ≥ ₂ ▶ ○ ✓), so without these
faces those glyphs are drawn in a system font. This takes every codepoint the
upstream release carries that no @fontsource subset's unicode-range claims,
writes one woff2 per weight fonts.css asks for, and writes the @font-face rules
for them with exactly that unicode-range, so a browser still picks the
@fontsource face for everything @fontsource covers.

Needs fontTools with brotli (`pip install fonttools brotli`). Takes the
unpacked upstream release zip (github.com/JetBrains/JetBrainsMono/releases):

    python3 packages/app/scripts/gen-jetbrains-mono-symbols.py <release-dir>
"""

import re
import shutil
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[3]
STYLES = ROOT / "packages/app/src/styles"
OUT_DIR = STYLES / "fonts"
OUT_CSS = OUT_DIR / "jetbrains-mono-symbols.css"
FONTSOURCE = ROOT / "packages/app/node_modules/@fontsource/jetbrains-mono"

WEIGHTS = {400: "Regular", 600: "SemiBold", 700: "Bold"}


def parse_ranges(css: str) -> list[tuple[int, int]]:
    out = []
    for decl in re.findall(r"unicode-range:\s*([^;]+);", css):
        for part in decl.split(","):
            lo, _, hi = part.strip()[2:].partition("-")
            out.append((int(lo, 16), int(hi or lo, 16)))
    return out


def to_ranges(codepoints: list[int]) -> str:
    runs = []
    for cp in codepoints:
        if runs and runs[-1][1] == cp - 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return ", ".join(
        f"U+{lo:04X}" if lo == hi else f"U+{lo:04X}-{hi:04X}" for lo, hi in runs
    )


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    release = Path(sys.argv[1])
    claimed = parse_ranges((FONTSOURCE / "400.css").read_text())
    if not claimed:
        sys.exit(f"no unicode-range found in {FONTSOURCE / '400.css'}")

    def unclaimed(font: TTFont) -> set[int]:
        return {
            cp
            for cp in font.getBestCmap()
            if cp > 0x20 and not any(lo <= cp <= hi for lo, hi in claimed)
        }

    # Only codepoints every weight carries, so one unicode-range is true of all three.
    sources = {
        w: release / "fonts/ttf" / f"JetBrainsMono-{name}.ttf"
        for w, name in WEIGHTS.items()
    }
    codepoints = sorted(set.intersection(*(unclaimed(TTFont(p)) for p in sources.values())))
    ranges = to_ranges(codepoints)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rules = []
    for weight, path in sources.items():
        name = f"jetbrains-mono-symbols-{weight}-normal.woff2"
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.notdef_outline = True
        font = subset.load_font(str(path), options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=codepoints)
        subsetter.subset(font)
        subset.save_font(font, str(OUT_DIR / name), options)
        rules.append(
            "@font-face {\n"
            '  font-family: "JetBrains Mono";\n'
            "  font-style: normal;\n"
            "  font-display: swap;\n"
            f"  font-weight: {weight};\n"
            f'  src: url(./{name}) format("woff2");\n'
            f"  unicode-range:\n    {ranges};\n"
            "}\n"
        )
    shutil.copyfile(release / "OFL.txt", OUT_DIR / "OFL.txt")
    OUT_CSS.write_text(
        "/* Generated by packages/app/scripts/gen-jetbrains-mono-symbols.py. */\n"
        + "\n".join(rules)
    )
    print(f"{len(codepoints)} codepoints, {len(sources)} weights -> {OUT_DIR}")


if __name__ == "__main__":
    main()
