/**
 * The banner-comment matcher, and the tree scan that applies it.
 *
 * Pure module: no vitest, no allowlist, nothing but node builtins. Same reason
 * `banner-comments.allowlist.ts` is split out, and one more besides. The
 * allowlist is split so its DATA can be read at a git ref; this is split so its
 * LOGIC can be. When the matcher is widened, the ratchet loads the previous
 * matcher at the base revision and re-runs it over the current tree, which is
 * what tells a reseed caused by the gate learning to see a new spelling from a
 * reseed laundering banners somebody just wrote. See `MATCHER_REVISION`.
 *
 * WHAT A BANNER IS, generally: a comment block whose first and last lines are a
 * bare rule and whose interior is a short title. It has exactly two spellings
 * and they are the same object, one collapsed and one spread:
 *
 *     // --- Registration ---            <- collapsed onto one line
 *
 *     // ---------------                 <- spread over three
 *     // Registration
 *     // ---------------
 *
 * The first version of this gate saw only the collapsed spelling, and the tree
 * writes the spread one 175 times. The fix before it had the same shape: the
 * version before THAT matched `[-=*]` alone and could not see a banner drawn
 * with box-drawing characters. Both were special cases of one thing, so both
 * missed the next spelling. Hence a definition here that names the object
 * rather than a pattern, and a matcher built from that definition.
 *
 * WHAT IT DELIBERATELY DOES NOT MATCH, because these are not the defect:
 *
 *   - a bare rule with no title: the `// -----` wrap that opens or closes a
 *     doc-comment block. 664 lines in this tree carry that shape, and none of
 *     them label anything. A whole-tree review counted those 664 as banners and
 *     reported the population as ~672; that number is the loose count, not this
 *     one
 *   - a comment paragraph that merely opens with rule characters and runs on
 *     with no closing rule. Prose, not a banner
 *   - a PROSE BLOCK bracketed top and bottom by rules. The shape is a banner's
 *     but the content is an essay, so `TITLE_MAX_LINES` cuts it off. The tree's
 *     interior-length histogram makes the cut for us rather than taste: 179
 *     banners have a one-line title, 18 have two and 12 have three (a title too
 *     long for one line, wrapped), and then it collapses to a flat tail of
 *     6-to-8-per-length running out to a 64-line interior. Everything past
 *     three reads as paragraphs on inspection
 *   - a title interrupted by a blank comment line. A title does not have
 *     paragraphs; a bracketed essay does, and that is how the longest ones
 *     announce themselves inside the three-line cut
 *   - a generated file, by path and by header marker
 */

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Rule characters. Box-drawing runs count, not only ASCII: the version of this
 * that matched `[-=*]` alone could not see a banner drawn with U+2500 or
 * U+2550, which is 134 files, a larger population than the one it was guarding.
 */
export const RULE_CHARS = "-=*─━┄┅┈┉╌╍═";

/**
 * Comment leads that can carry the shape: `//`, C#'s doc `///`, and the `*`
 * continuation line inside a block comment. The `*` lead is not decoration
 * here, it is how four of the tree's banners are actually written.
 */
const LEAD = String.raw`(?:\/\/\/?|\*)`;

/** Rule characters, a title with at least one letter, rule characters again. */
const ONE_LINE_RE = new RegExp(
  `^[ \t]*${LEAD}[ \t]*[${RULE_CHARS}]{3,}(?=.*[A-Za-z]).*[${RULE_CHARS}]{3,}[ \t]*$`,
);

/** A comment line whose whole content is a run of rule characters. */
const RULE_ONLY_RE = new RegExp(
  `^[ \t]*${LEAD}[ \t]*[${RULE_CHARS}]{3,}[ \t]*$`,
);

/** Any comment line at all, a block-comment opener included. */
const COMMENT_RE = new RegExp(`^[ \t]*(?:${LEAD}|\\/\\*)`);

/** A comment line with no content. What separates a title from a paragraph. */
const BLANK_COMMENT_RE = new RegExp(`^[ \t]*${LEAD}[ \t]*$`);

/** How many lines a title may wrap onto before the block is read as prose. */
export const TITLE_MAX_LINES = 3;

/** Languages whose line comment is `//`. Nothing else can carry the shape. */
export const SOURCE_RE = /\.(ts|tsx|js|jsx|mjs|cjs|cs)$/;

/** Generated by path. A codegen template's dividers are not anyone's to fix. */
export const GENERATED_PATH_RE = /(?:\.(?:g|generated)\.[a-z]+|\/generated\/)/;

/** Generated by header, for output whose filename gives nothing away. */
export const GENERATED_HEADER_RE = /<auto-?generated|@generated|DO NOT EDIT/i;

/**
 * Every banner in one file's lines, as the title text, in source order.
 *
 * The spread form consumes its closing rule, so two banners stacked back to
 * back cannot share a rule line and be counted three times.
 */
export function bannersIn(lines: readonly string[]): string[] {
  const found: string[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (ONE_LINE_RE.test(lines[i])) {
      found.push(lines[i].trim());
      continue;
    }
    if (!RULE_ONLY_RE.test(lines[i])) continue;
    let end = i + 1;
    while (
      end < lines.length &&
      COMMENT_RE.test(lines[end]) &&
      !RULE_ONLY_RE.test(lines[end]) &&
      !BLANK_COMMENT_RE.test(lines[end]) &&
      end - i - 1 < TITLE_MAX_LINES
    ) {
      end++;
    }
    const title = lines.slice(i + 1, end);
    if (
      end < lines.length &&
      title.length > 0 &&
      RULE_ONLY_RE.test(lines[end]) &&
      title.some((l) => /[A-Za-z]/.test(l))
    ) {
      found.push(title.map((l) => l.trim()).join(" "));
      i = end;
    }
  }
  return found;
}

export interface BannerScan {
  /** Hand-written source files actually read. */
  scanned: number;
  /** Files skipped as generated, by path and by header together. */
  generated: number;
  /** Path to banner count, for every file carrying at least one. */
  counts: Map<string, number>;
  /** Path to the banner titles themselves, for the failure messages. */
  titles: Map<string, string[]>;
}

function repoRoot(): string {
  return execFileSync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  }).trim();
}

/**
 * Tracked files AND untracked-but-not-ignored ones. The untracked half is
 * load-bearing: a banner written into a brand new file is exactly the case this
 * is meant to catch, and a tracked-only listing would report it clean until the
 * commit after the one that introduced it.
 */
function sourceFiles(root: string): { kept: string[]; generated: number } {
  const all = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  )
    .split("\n")
    .filter((f) => SOURCE_RE.test(f));
  const kept = all.filter((f) => !GENERATED_PATH_RE.test(f));
  return { kept, generated: all.length - kept.length };
}

/**
 * Every hand-written source file in the checkout, as repo-relative paths.
 *
 * Exported because the re-seed check re-runs a PREVIOUS matcher over the same
 * listing: only the matching is versioned, the enumeration is not.
 */
export function handWrittenSources(): string[] {
  const root = repoRoot();
  return sourceFiles(root).kept.filter((file) => {
    try {
      const head = readFileSync(join(root, file), "utf8")
        .split("\n")
        .slice(0, 5);
      return !GENERATED_HEADER_RE.test(head.join("\n"));
    } catch {
      return false;
    }
  });
}

/** Apply `bannersIn` to every hand-written source file in the checkout. */
export function scanBanners(): BannerScan {
  const root = repoRoot();
  const counts = new Map<string, number>();
  const titles = new Map<string, string[]>();
  const listing = sourceFiles(root);
  let scanned = 0;
  let generated = listing.generated;
  for (const file of listing.kept) {
    let source: string;
    try {
      source = readFileSync(join(root, file), "utf8");
    } catch {
      continue;
    }
    const fileLines = source.split("\n");
    if (GENERATED_HEADER_RE.test(fileLines.slice(0, 5).join("\n"))) {
      generated++;
      continue;
    }
    scanned++;
    const hits = bannersIn(fileLines);
    if (hits.length > 0) {
      counts.set(file, hits.length);
      titles.set(file, hits);
    }
  }
  return { scanned, generated, counts, titles };
}
