/**
 * Data for the banner-comment ratchet (`styleguide-banner-comments.test.ts`).
 * Pure data module, no test logic, so the shrink-only half of the check can load
 * this file's content at an arbitrary git ref without pulling in vitest or the
 * scan machinery. Same split-module shape as `uplink-isolation.allowlist.ts`.
 *
 * A BANNER COMMENT is a `//` line whose whole content is three or more `-`, `=`
 * or `*` rule characters, then a title, then three or more rule characters
 * again: `// --- Registration ---`, `// ---- recorded calls ----`,
 * `// --- Samples ------------`. CLAUDE.md forbids one above an obvious call,
 * because the decoration adds nothing the code below it does not already say.
 *
 * WHAT THE SHAPE DELIBERATELY DOES NOT MATCH, because these are not the defect:
 *
 *   - a bare rule with no title, the `// -----------------` wrap that closes or
 *     separates a doc-comment block. 665 of the repo's 1,092 rule-shaped lines
 *     are this, and none of them label anything
 *   - a comment paragraph that merely opens with rule characters and wraps onto
 *     the next line, e.g. an annotated entry in another ratchet's debt list.
 *     It has no closing rule, so it is prose, not a banner. 86 lines
 *   - a generated file, excluded by path (`*.g.cs`, `*.generated.ts`,
 *     anything under a `generated/` directory) and by an `@generated` /
 *     `<auto-generated>` / `DO NOT EDIT` marker in its first five lines
 *
 * DECORATION VERSUS DIVISION is the whole judgement, and the shape alone cannot
 * make it. A file carrying `SCHEME_MIN` banners or more is dividing a long
 * table or a long test into named sections, which is not what the rule is aimed
 * at, and is tolerated under `SECTIONED_CEILINGS`. A file carrying one or two is
 * decorating, and belongs in `BANNER_COMMENT_DEBT`.
 *
 * The debt list is consulted BEFORE the scheme rule, so the scheme rule cannot
 * be used to escape the debt list: adding a third banner to a two-banner debt
 * file fails on the count rather than promoting the file out of debt.
 *
 * The debt counts are EXACT, not ceilings. The scan is a static regex over a
 * file, so the number is deterministic and there is no measurement noise to
 * absorb, and exactness is what makes the list self-cleaning: clean a banner and
 * the build tells you to lower the number in the same commit, which is the only
 * way a debt list reaches zero by attrition rather than by somebody auditing it.
 *
 * The tolerated population is a bare ceiling with no file names in it, which is
 * deliberate. Naming the files would put two legacy schema paths in this source
 * file, and those paths carry a vendor name that `vendor-name.test.ts` is
 * separately ratcheting out of the tree. A gate that has to grow another gate's
 * debt to exist is the wrong gate.
 */

/**
 * Files carrying an isolated banner comment. SHRINK-ONLY, and the target is
 * zero: delete the banner, or replace it with a sentence that says something the
 * code does not, then lower or remove the entry here in the same commit.
 *
 * Never add a line. A new entry means new code just created the violation, and
 * the rule has been in CLAUDE.md the whole time.
 *
 * Seeded 2026-08-22 at 43 files / 64 banners, measured across 2,784 hand-written
 * source files. The nine days before that had taken the population from 22 files
 * to 32 by the narrower count a feature-recovery inventory was using, which is
 * why this exists.
 */
export const BANNER_COMMENT_DEBT: Record<string, number> = {
  "mod/Gonogo.KSP.Tests/CurrencyDelay/StockCurrencyStateMachineTests.cs": 2,
  "mod/Gonogo.KSP/KspHost.cs": 1,
  "mod/Gonogo.KSP/KspVesselActuator.cs": 1,
  "mod/GonogoDevTools/GonogoDevKerbalismDump.cs": 1,
  "mod/GonogoKerbalismUplink.Tests/FakeKerbalismFileActuator.cs": 2,
  "mod/GonogoKerbalismUplink/KerbalismFileCommandProvider.cs": 1,
  "mod/GonogoKosUplink.Tests/KosComputeAccumulatorTests.cs": 1,
  "mod/GonogoKosUplink.Tests/KosExtensionOnPrintTests.cs": 1,
  "mod/GonogoKosUplink.Tests/KosTerminalManagerTests.cs": 2,
  "mod/GonogoKosUplink/KosTerminalManager.cs": 2,
  "mod/GonogoPrincipiaUplink.Tests/SettingsTests.cs": 1,
  "mod/Sitrep.Host.IntegrationTests/ReplayToWebSocketEndToEndTests.cs": 1,
  "mod/Sitrep.Host.IntegrationTests/TestUplinks.cs": 1,
  "mod/Sitrep.Host.Tests/FakeCareerActuator.cs": 2,
  "mod/Sitrep.Host.Tests/FakeFlightOpsActuator.cs": 2,
  "mod/Sitrep.Host.Tests/FakePartActionActuator.cs": 2,
  "mod/Sitrep.Host.Tests/FakeRoboticsActuator.cs": 2,
  "mod/Sitrep.Host.Tests/FakeScienceActuator.cs": 2,
  "mod/Sitrep.Host.Tests/FakeVesselActuator.cs": 2,
  "mod/Sitrep.Host.Tests/PartActionsViewProviderTests.cs": 1,
  "mod/Sitrep.Host.Tests/UplinkDiscoveryTests.cs": 1,
  "mod/Sitrep.Host/RecordedSessionCodec.cs": 2,
  "mod/Sitrep.Host/ScienceCommandProvider.cs": 1,
  "mod/Sitrep.Host/VesselViewProvider.cs": 2,
  "mod/sitrep-sdk/src/api/command-rejection.test-d.ts": 2,
  "mod/sitrep-sdk/src/flight/BufferedDataSource.test.ts": 1,
  "mod/sitrep-sdk/src/flight/flightDetector.ts": 1,
  "mod/sitrep-sdk/src/flight/storage/Store.ts": 2,
  "mod/sitrep-sdk/src/spine/use-command.ts": 1,
  "packages/app/src/components/SignalLossIndicator.stream.test.tsx": 2,
  "packages/app/src/settings/SitrepConnection.tsx": 1,
  "packages/components/scripts/unfed-snapshot-gate.ts": 1,
  "packages/serial/src/mocks/mockWebSerial.ts": 1,
  "packages/serial/src/transports/GamepadTransport.ts": 1,
  "packages/sitrep-client/src/websocket-transport.ts": 1,
  "tests/playwright/sitrep-stream-server.mjs": 2,
};

/**
 * A file carrying at least this many banners is treated as a sectioning scheme
 * rather than a decoration, and is tolerated. The number is a judgement, read
 * off the data: at three or more, every such file in the tree turned out to be a
 * long declaration table or a long test divided into named sections, and none
 * was a single decorated statement.
 *
 * The debt list is consulted FIRST, so this cannot be used to escape it. Adding
 * a third banner to a two-banner debt file would otherwise promote that file out
 * of the debt list, and the ratchet would report the change as a cleanup.
 */
export const SCHEME_MIN = 3;

/**
 * Ceilings on the tolerated population, so the exemption cannot spread. Without
 * them, writing three banners into a clean file in one commit is invisible: the
 * file clears `SCHEME_MIN` on arrival and no other check has an opinion.
 *
 * Ceilings rather than exact counts, unlike the debt list, because nothing
 * expects this population to reach zero and a cleanup here should not have to
 * touch this file. Slack left behind by a cleanup is the known cost, and it is
 * bounded by having to fit under BOTH numbers at once.
 *
 * Note what happens when a scheme file is cleaned down to one or two banners
 * rather than none: it drops out of this population and lands as an unlisted
 * decoration, which fails. That is correct rather than a wrinkle, because the
 * two banners left behind are exactly the shape the rule forbids.
 */
export const SECTIONED_CEILINGS = {
  /** Files carrying `SCHEME_MIN` or more banners. 35 at seed time. */
  files: 35,
  /** Banner lines across those files. 277 at seed time. */
  banners: 277,
} as const;

/**
 * What the scan expects to see when it is working. Floors, not equalities: the
 * point is to fail LOUDLY when the enumeration breaks, and a broken enumeration
 * produces a small number, never a large one.
 *
 * A scan that walks zero files finds zero banners and passes every assertion in
 * the ratchet, so without this the whole file could go green on a renamed
 * directory, a changed `git ls-files` invocation, or a cwd that is not the repo
 * root. `styleguide-earth-day` shipped in exactly that state for weeks.
 */
export const SCAN_FLOORS = {
  /** Hand-written source files walked. 2,784 at seed time. */
  files: 2000,
  /** Files carrying at least one banner. 78 at seed time. */
  filesWithBanner: 60,
  /** Banner lines found. 341 at seed time. */
  banners: 250,
} as const;
