import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The scan behind `styleguide-comment-stacks.test.ts`, in its own module so the
 * gate and the debt generator cannot drift apart. `banner-comments` keeps its
 * scan inside the test and regenerates its list by hand; that works there
 * because the shape is one line, and it would not work here because the shape
 * spans lines and depends on sentence detection that is easy to re-implement
 * slightly differently.
 *
 * THE RULE, from CLAUDE.md: a genuinely multi-line thought uses proper
 * multi-line formatting, a `/** *\/` block or a real paragraph, and never one
 * long sentence mashed into a stack of single-line `//` fragments. A merely-long
 * single comment stays one line and relies on editor wrapping.
 *
 * So the defect is specifically ONE SENTENCE spread over three or more `//`
 * lines. A stack of several complete sentences is the "real paragraph" the rule
 * permits and is NOT counted. That distinction is the whole difference between a
 * gate worth having and one that forbids the tree's entire comment style: a loose
 * scan for three consecutive prose `//` lines finds 5197 blocks across 1301
 * files, and this narrower rule finds 1610 across 732. Re-running the loose
 * regex and getting a bigger number is not evidence this scan is broken.
 */

/**
 * JS/TS only, deliberately, though `.cs` shares the `//` line comment and the
 * banner ratchet beside this one does scan it.
 *
 * A stack of `//` lines is ordinary, idiomatic .NET: C# has `///` for the doc
 * form, so a plain `//` paragraph above a member is the normal way to write an
 * aside there, and gating it would be imposing a JS convention on a language
 * that does not share it. In JS/TS the block comment is the doc form and the
 * stack has no such standing.
 */
const SOURCE_RE = /\.(ts|tsx|js|jsx|mjs|cjs)$/;

/** Generated by path. A codegen template's comment style is not anyone's to fix. */
const GENERATED_PATH_RE =
  /(?:\.(?:g|generated)\.[a-z]+|\/(?:generated|__generated__)\/)/;

/** Generated by header, for output whose filename gives nothing away. */
const GENERATED_HEADER_RE = /<auto-?generated|@generated|DO NOT EDIT/i;

/**
 * A tool directive rather than a thought: pragmas, disables, environment
 * selectors. These legitimately stack and rewriting them as a block comment
 * would stop them working.
 */
const DIRECTIVE_RE =
  /^\s*(?:eslint|biome|prettier|@ts-|@vitest-|c8 |v8 |istanbul|oxlint|type-coverage|deno-lint|@license|@preserve|SPDX-)/;

/**
 * Commented-out code, which is a different defect with a different fix. A
 * trailing brace, semicolon or arrow is the cheap tell, and it is worth being
 * generous here: a false NEGATIVE costs one uncaught comment, a false POSITIVE
 * puts a line in the debt list that no rewrite can ever clear.
 */
const CODE_LIKE_RE =
  /[;{}]\s*$|=>|\bfunction\s|\bconst\s|\breturn\s|\bimport\s/;

/** Prose needs at least two adjacent word-shaped tokens somewhere in it. */
const PROSE_RE = /[a-z]{3,}\s+[a-z]{3,}/;

/**
 * An internal sentence boundary: terminal punctuation, optionally closing a
 * quote or bracket, then whitespace, then something that starts a new sentence.
 * Its ABSENCE is what makes a stack a single mashed sentence.
 */
const SENTENCE_BREAK_RE = /[.!?]["'’)\]]?\s+["'“(`[]?[A-Z0-9]/;

/** The smallest stack that can be a violation. Two lines is ordinary wrapping. */
export const MIN_STACK_LINES = 3;

export interface CommentStack {
  /** 1-indexed line of the stack's first `//`. */
  line: number;
  /** How many `//` lines the stack spans. */
  span: number;
  /** The joined comment text, for the failure message. */
  text: string;
}

/**
 * Every single-sentence `//` stack in one file's source. Exported on its own so
 * the matcher can be exercised against literal strings in the test without
 * touching the filesystem, which is what lets the test prove the regex still
 * matches something.
 */
export function stacksIn(source: string): CommentStack[] {
  const lines = source.split("\n");
  const found: CommentStack[] = [];
  let run: string[] = [];
  let start = 0;

  const flush = (): void => {
    if (run.length >= MIN_STACK_LINES) {
      const text = run.join(" ").trim();
      const isViolation =
        PROSE_RE.test(text) &&
        !CODE_LIKE_RE.test(text) &&
        // Strip a single trailing terminator before looking for an INTERNAL
        // break, so a stack ending in a full stop is not read as containing one.
        !SENTENCE_BREAK_RE.test(text.replace(/[.!?]\s*$/, ""));
      if (isViolation) found.push({ line: start + 1, span: run.length, text });
    }
    run = [];
  };

  for (const [i, raw] of lines.entries()) {
    const trimmed = raw.trim();
    // `///` is a doc comment (C# XML docs, TS triple-slash directives) and is
    // already the proper multi-line form, so it never counts.
    const isLineComment =
      trimmed.startsWith("//") &&
      !trimmed.startsWith("///") &&
      !DIRECTIVE_RE.test(trimmed.slice(2));
    if (isLineComment) {
      if (run.length === 0) start = i;
      run.push(trimmed.slice(2).trim());
    } else {
      flush();
    }
  }
  flush();
  return found;
}

export interface CommentStackScan {
  /** Hand-written source files actually read. */
  scanned: number;
  /** Files skipped as generated, by path and by header together. */
  generated: number;
  /** Path to stack count, for every file carrying at least one. */
  counts: Map<string, number>;
  /** Path to the stacks themselves, for the failure messages. */
  stacks: Map<string, CommentStack[]>;
}

function repoRoot(): string {
  return execFileSync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  }).trim();
}

/**
 * Tracked files AND untracked-but-not-ignored ones. The untracked half is
 * load-bearing: a stack written into a brand new file is exactly the case this
 * is meant to catch, and a tracked-only listing would report it clean until the
 * commit after the one that introduced it.
 */
export function scanCommentStacks(): CommentStackScan {
  const root = repoRoot();
  const counts = new Map<string, number>();
  const stacks = new Map<string, CommentStack[]>();
  const all = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  )
    .split("\n")
    .filter((f) => SOURCE_RE.test(f));
  const kept = all.filter((f) => !GENERATED_PATH_RE.test(f));
  let generated = all.length - kept.length;
  let scanned = 0;

  for (const file of kept) {
    let source: string;
    try {
      source = readFileSync(join(root, file), "utf8");
    } catch {
      continue;
    }
    if (GENERATED_HEADER_RE.test(source.split("\n").slice(0, 5).join("\n"))) {
      generated++;
      continue;
    }
    scanned++;
    const hits = stacksIn(source);
    if (hits.length > 0) {
      counts.set(file, hits.length);
      stacks.set(file, hits);
    }
  }
  return { scanned, generated, counts, stacks };
}
