/**
 * Which matcher the numbers in this file were measured with.
 *
 * Every number below is a measurement, and a measurement means nothing without
 * the instrument that took it. Widening the matcher is the one change that
 * legitimately RAISES a shrink-only number, and a bare shrink-only check cannot
 * tell that from somebody laundering stacks they just wrote. So the revision is
 * the declaration: bump it in the same commit as the matcher change and the
 * ratchet re-seeds, leave it alone and every number is shrink-only as before.
 *
 * It is not an escape hatch, because a bump is not taken on trust. The ratchet
 * loads `comment-stacks.scan.ts` AS IT STOOD at the base revision, runs that
 * older matcher over the CURRENT tree, and requires the older numbers to still
 * hold. A re-seed therefore proves that everything newly counted is something
 * the old matcher could not see. Same mechanism as
 * `banner-comments.allowlist.ts`.
 *
 * 1: a three-line floor, and a run broken only by a non-comment line.
 * 2: a two-line floor, and a divider or an empty comment line ends a run.
 */
export const MATCHER_REVISION = 2;

/**
 * Files carrying a single-sentence `//` comment stack, with how many each has.
 *
 * SHRINK-ONLY. Entries may be lowered or removed, never added or raised. A new
 * entry means new code just created the violation, which is the thing the gate
 * exists to stop; fix the comment instead.
 *
 * Regenerate after a cleanup with:
 *
 *   node scripts/comment-stack-debt.mjs --update
 *
 * See `styleguide-comment-stacks.test.ts` for what counts as a violation and
 * `comment-stacks.scan.ts` for the matcher itself.
 */
export const COMMENT_STACK_DEBT: Record<string, number> = {
  "mod/golden-fixtures/gen/serialization.gen.ts": 2,
  "mod/sitrep-kernel/src/broker.test.ts": 1,
  "mod/sitrep-kernel/src/registry.test.ts": 2,
  "mod/sitrep-kernel/src/registry.ts": 2,
  "mod/sitrep-sdk/src/api/alarm-request.ts": 1,
  "mod/sitrep-sdk/src/api/api-shape.gate.test.ts": 2,
  "mod/sitrep-sdk/src/api/contribution-slots.ts": 2,
  "mod/sitrep-sdk/src/api/coverage/CoverageMaskCache.test.ts": 1,
  "mod/sitrep-sdk/src/api/coverage/CoverageMaskStore.ts": 1,
  "mod/sitrep-sdk/src/api/index.ts": 1,
  "mod/sitrep-sdk/src/api/logger.test.ts": 1,
  "mod/sitrep-sdk/src/api/plots.ts": 1,
  "mod/sitrep-sdk/src/api/registry.ts": 1,
  "mod/sitrep-sdk/src/api/settings-registry.test-d.ts": 3,
  "mod/sitrep-sdk/src/api/slots.ts": 4,
  "mod/sitrep-sdk/src/api/types.ts": 1,
  "mod/sitrep-sdk/src/burn-clock.test.ts": 2,
  "mod/sitrep-sdk/src/cli/index.ts": 1,
  "mod/sitrep-sdk/src/commands.test-d.ts": 1,
  "mod/sitrep-sdk/src/commands.ts": 2,
  "mod/sitrep-sdk/src/delay-roles.ts": 1,
  "mod/sitrep-sdk/src/descent.test.ts": 1,
  "mod/sitrep-sdk/src/extensions.test.ts": 1,
  "mod/sitrep-sdk/src/extensions.ts": 2,
  "mod/sitrep-sdk/src/flight/BufferedDataSource.test.ts": 3,
  "mod/sitrep-sdk/src/flight/flightDetector.ts": 1,
  "mod/sitrep-sdk/src/flight/storage/MemoryStore.ts": 1,
  "mod/sitrep-sdk/src/flight/types.ts": 1,
  "mod/sitrep-sdk/src/frame-qualifier.ts": 1,
  "mod/sitrep-sdk/src/generated.test.ts": 1,
  "mod/sitrep-sdk/src/index.ts": 1,
  "mod/sitrep-sdk/src/media/delayed-playout-buffer.block-colour.test.ts": 2,
  "mod/sitrep-sdk/src/media/delayed-playout-buffer.test.ts": 4,
  "mod/sitrep-sdk/src/media/encoded-frame-delay.test.ts": 3,
  "mod/sitrep-sdk/src/media/frame-delay.block-colour.test.ts": 1,
  "mod/sitrep-sdk/src/media/frame-delay.ts": 2,
  "mod/sitrep-sdk/src/media/shared-delayed-streams.ts": 1,
  "mod/sitrep-sdk/src/media/worker/delay-worker-client.ts": 2,
  "mod/sitrep-sdk/src/media/worker/presentation-pacer.test.ts": 4,
  "mod/sitrep-sdk/src/media/worker/presentation-pacer.ts": 1,
  "mod/sitrep-sdk/src/media/worker/time-base.test.ts": 1,
  "mod/sitrep-sdk/src/media/worker/worker-delay-clock.test.ts": 1,
  "mod/sitrep-sdk/src/perf/PerfBudget.ts": 1,
  "mod/sitrep-sdk/src/registry/index.ts": 1,
  "mod/sitrep-sdk/src/spine/client-timeline.ts": 1,
  "mod/sitrep-sdk/src/spine/client.ts": 1,
  "mod/sitrep-sdk/src/spine/context.tsx": 2,
  "mod/sitrep-sdk/src/spine/delta-v-budget.ts": 2,
  "mod/sitrep-sdk/src/spine/lagrange.test.ts": 2,
  "mod/sitrep-sdk/src/spine/lagrange.ts": 1,
  "mod/sitrep-sdk/src/spine/never-reckonable.ts": 1,
  "mod/sitrep-sdk/src/spine/orbit-trajectory.test.ts": 1,
  "mod/sitrep-sdk/src/spine/orbit-trajectory.ts": 1,
  "mod/sitrep-sdk/src/spine/past-track.test.ts": 1,
  "mod/sitrep-sdk/src/spine/propagation-horizon.test.ts": 1,
  "mod/sitrep-sdk/src/spine/replay-transport.ts": 2,
  "mod/sitrep-sdk/src/spine/timeline-store.ts": 1,
  "mod/sitrep-sdk/src/spine/use-data-sources.ts": 2,
  "mod/sitrep-sdk/src/spine/use-stream-event.ts": 1,
  "mod/sitrep-sdk/src/spine/use-telemetry.ts": 1,
  "mod/sitrep-sdk/src/testing/index.ts": 1,
  "mod/sitrep-sdk/src/testing/install-real-test-host.ts": 1,
  "mod/sitrep-sdk/src/topic-fields.test.ts": 2,
  "mod/sitrep-sdk/src/topics.test-d.ts": 1,
  "mod/sitrep-sdk/src/topics.test.ts": 2,
  "mod/sitrep-sdk/src/unit-system/algebra.test-d.ts": 2,
  "mod/sitrep-sdk/src/unit-system/calendar.test.ts": 1,
  "mod/sitrep-sdk/src/unit-system/definitions.ts": 3,
  "mod/sitrep-sdk/src/unit-system/guards.test-d.ts": 1,
  "mod/sitrep-sdk/src/unit-system/registry.test.ts": 1,
  "mod/sitrep-sdk/src/unit-system/value.test-d.ts": 4,
  "mod/sitrep-sdk/src/unit-system/value.test.ts": 1,
  "mod/sitrep-sdk/src/unit-system/value.ts": 1,
  "mod/sitrep-sdk/src/units.test-d.ts": 1,
  "mod/sitrep-sdk/src/units.test.ts": 1,
  "mod/sitrep-sdk/src/wrap-units.test.ts": 1,
  "mod/sitrep-sdk/src/wrap-units.ts": 1,
  "mod/sitrep-server/src/archive.test.ts": 1,
  "mod/sitrep-server/src/courier-transport.ts": 1,
  "mod/sitrep-server/src/courier.test.ts": 1,
  "mod/sitrep-server/src/courier.ts": 2,
  "packages/app/scripts/minsize-gate.ts": 1,
  "packages/app/scripts/probe/commcast-probe-entry.tsx": 1,
  "packages/app/scripts/render-settings.ts": 1,
  "packages/app/src/__tests__/action-group.test.tsx": 1,
  "packages/app/src/__tests__/dashboard-mobile.test.tsx": 1,
  "packages/app/src/__tests__/gonogo-host-service.test.ts": 1,
  "packages/app/src/__tests__/kos-execute-tunnel.test.ts": 1,
  "packages/app/src/__tests__/maneuver-trigger-roundtrip.test.ts": 2,
  "packages/app/src/__tests__/peer-broadcast-benchmark.test.ts": 3,
  "packages/app/src/__tests__/peer-client-data-source.test.ts": 1,
  "packages/app/src/__tests__/peer-client-service.test.ts": 1,
  "packages/app/src/__tests__/peer-data-sources.test.ts": 1,
  "packages/app/src/__tests__/peer-roundtrip.test.ts": 1,
  "packages/app/src/__tests__/peer-use-data-series.test.tsx": 1,
  "packages/app/src/__tests__/pushed-dashboard-overlay.test.tsx": 1,
  "packages/app/src/__tests__/relay-host-discovery-client.test.ts": 1,
  "packages/app/src/__tests__/relay-host-discovery-host.test.ts": 2,
  "packages/app/src/__tests__/scansat-coverage-roundtrip.test.tsx": 1,
  "packages/app/src/__tests__/scene-change-banner.test.tsx": 1,
  "packages/app/src/__tests__/screens-smoke.test.tsx": 1,
  "packages/app/src/__tests__/serial-to-sitrep-command.test.tsx": 2,
  "packages/app/src/__tests__/sitrep-station-forwarding.test.tsx": 2,
  "packages/app/src/__tests__/sitrep-stream-wire.test.tsx": 1,
  "packages/app/src/__tests__/telemetry-components.test.tsx": 4,
  "packages/app/src/__tests__/testing-entries-surface.test.ts": 1,
  "packages/app/src/__tests__/topic-cs-sync.test.ts": 1,
  "packages/app/src/__tests__/uplink-widget-declarations.test.ts": 1,
  "packages/app/src/alarms/AlarmBanner.tsx": 2,
  "packages/app/src/alarms/AlarmHostService.test.ts": 3,
  "packages/app/src/alarms/AlarmHostService.ts": 3,
  "packages/app/src/alarms/AlarmsModal.test.tsx": 4,
  "packages/app/src/alarms/AlarmsModal.tsx": 5,
  "packages/app/src/alarms/AlarmsModal.undefined.characterise.test.tsx": 1,
  "packages/app/src/backup/BackupManager.tsx": 1,
  "packages/app/src/commcast/radio/webaudio.ts": 3,
  "packages/app/src/components/Dashboard/MobileDashboard.tsx": 1,
  "packages/app/src/components/Dashboard/shared.tsx": 1,
  "packages/app/src/components/FlightOutcomeBanner.tsx": 2,
  "packages/app/src/components/SceneChangeBanner.tsx": 1,
  "packages/app/src/components/SceneChangeBanner.undefined.characterise.test.tsx": 3,
  "packages/app/src/components/SignalLossIndicator.stream.test.tsx": 1,
  "packages/app/src/components/SignalLossIndicator.test.tsx": 1,
  "packages/app/src/components/SignalLossIndicator.tsx": 1,
  "packages/app/src/components/SignalLossIndicator.undefined.characterise.test.tsx": 5,
  "packages/app/src/components/StationLinkFab.tsx": 1,
  "packages/app/src/components/VantageControl.station.test.tsx": 1,
  "packages/app/src/components/VantageControl.undefined.characterise.test.tsx": 4,
  "packages/app/src/dataSources/sitrep.ts": 1,
  "packages/app/src/goNoGo/CountdownAnnouncer.test.tsx": 1,
  "packages/app/src/goNoGo/GoNoGoComponent.tsx": 2,
  "packages/app/src/logs/LogsManager.test.tsx": 2,
  "packages/app/src/main.tsx": 4,
  "packages/app/src/maneuverTriggers/ManeuverTriggerHostService.ts": 3,
  "packages/app/src/missionProfiles/MissionProfilesModal.tsx": 1,
  "packages/app/src/missionProfiles/MissionProfilesService.ts": 1,
  "packages/app/src/notes/TagAutocomplete.tsx": 2,
  "packages/app/src/notes/templating.ts": 1,
  "packages/app/src/peer/PeerBroadcastingDataSource.ts": 1,
  "packages/app/src/peer/PeerClientDataSource.ts": 2,
  "packages/app/src/peer/PeerClientService.ts": 6,
  "packages/app/src/peer/PeerHostService.bundleFetch.test.ts": 1,
  "packages/app/src/peer/PeerHostService.ts": 9,
  "packages/app/src/peer/PeerHostService.uplinkRelay.test.ts": 1,
  "packages/app/src/peer/RelayRegistration.ts": 1,
  "packages/app/src/peer/protocol.ts": 6,
  "packages/app/src/peer/typedListeners.ts": 1,
  "packages/app/src/screens/StationScreen.tsx": 3,
  "packages/app/src/screens/isStationRoute.ts": 1,
  "packages/app/src/settings/SettingsModal.test.tsx": 1,
  "packages/app/src/settings/SettingsModal.tsx": 6,
  "packages/app/src/settings/registry.ts": 1,
  "packages/app/src/telemetry/AugmentAvailabilityFeeder.undefined.characterise.test.tsx": 2,
  "packages/app/src/telemetry/KspCalendarObserver.tsx": 1,
  "packages/app/src/telemetry/KspCalendarObserver.undefined.characterise.test.tsx": 1,
  "packages/app/src/telemetry/ModalTelemetryBridge.test.tsx": 1,
  "packages/app/src/telemetry/PeerTransport.test.ts": 2,
  "packages/app/src/telemetry/PeerTransport.ts": 1,
  "packages/app/src/telemetry/SitrepPeerRelay.tsx": 2,
  "packages/app/src/telemetry/SitrepTelemetryProvider.tsx": 1,
  "packages/app/src/telemetry/StationParity.characterise.test.tsx": 1,
  "packages/app/src/trajectory/TrajectoryCurrencyBridge.tsx": 1,
  "packages/app/src/uplinks/StationUplinkLoader.test.tsx": 1,
  "packages/app/src/uplinks/StationUplinkLoader.tsx": 1,
  "packages/app/src/uplinks/consentModal.tsx": 1,
  "packages/app/src/uplinks/externals/ext-sitrep-sdk-frames.ts": 1,
  "packages/app/src/uplinks/hostCompat.ts": 3,
  "packages/app/src/uplinks/identity.ts": 1,
  "packages/app/src/uplinks/loader.ts": 1,
  "packages/app/src/uplinks/rosterProbe.test.ts": 3,
  "packages/app/vite.config.ts": 5,
  "packages/app/vitest.config.ts": 1,
  "packages/components/scripts/banner-probe/banner-probe-entry.tsx": 2,
  "packages/components/scripts/crew-avatar-probe/crew-avatar-probe-entry.tsx": 2,
  "packages/components/scripts/crew-badge-probe/crew-badge-probe-entry.tsx": 2,
  "packages/components/scripts/gen-landing-status-fixtures.ts": 1,
  "packages/components/scripts/probe/capture-entry.tsx": 1,
  "packages/components/scripts/probe/probe-entry.tsx": 2,
  "packages/components/scripts/render-alarm-banner.ts": 1,
  "packages/components/scripts/render-crew-status-avatar.ts": 1,
  "packages/components/scripts/render-crew-status-panel-badge.ts": 1,
  "packages/components/scripts/render-delay-rail.ts": 2,
  "packages/components/scripts/render-systemview-traffic-video.ts": 5,
  "packages/components/scripts/render-vantage-control.ts": 3,
  "packages/components/scripts/synthesize-landing-descent.ts": 1,
  "packages/components/scripts/unfed-snapshot-gate.ts": 1,
  "packages/components/scripts/visual-gate.ts": 1,
  "packages/components/scripts/widgetRenderHarness.ts": 4,
  "packages/components/scripts/widgets.ts": 4,
  "packages/core/scan-tests.mjs": 2,
  "packages/core/src/actionGroups.ts": 1,
  "packages/core/src/augments.test-d.ts": 1,
  "packages/core/src/augments.ts": 1,
  "packages/core/src/calc/transfer.ts": 1,
  "packages/core/src/chromeProviders.test.tsx": 1,
  "packages/core/src/contributionsRuntime.test.tsx": 6,
  "packages/core/src/fixture-gated-suites.test.ts": 1,
  "packages/core/src/hooks/gameModeTable.test.ts": 1,
  "packages/core/src/hooks/useDataStreamStatus.ts": 1,
  "packages/core/src/hooks/useGameContext.test.tsx": 1,
  "packages/core/src/hooks/useTelemetry.shim.test.tsx": 8,
  "packages/core/src/logger/ErrorBoundary.test.tsx": 1,
  "packages/core/src/orbital.ts": 1,
  "packages/core/src/published-doc-reachability.test.ts": 1,
  "packages/core/src/ratchet-base-ref.test.ts": 1,
  "packages/core/src/ratchetBaseRef.ts": 1,
  "packages/core/src/reckoning-candidates.test.ts": 3,
  "packages/core/src/replay-fixture-conformance.test.ts": 2,
  "packages/core/src/sdk-facade.conformance.test-d.ts": 3,
  "packages/core/src/searchTags.test.ts": 1,
  "packages/core/src/settings/registry.test.ts": 1,
  "packages/core/src/styleguide-banner-comments.test.ts": 1,
  "packages/core/src/styleguide-cleanup.test.ts": 1,
  "packages/core/src/styleguide-delay-ux.test.ts": 2,
  "packages/core/src/styleguide-generated-null-unions.test.ts": 1,
  "packages/core/src/styleguide-magnitude-canonical.test.ts": 1,
  "packages/core/src/styleguide-styled-components.test.ts": 3,
  "packages/core/src/styleguide-token-refs.test.ts": 1,
  "packages/core/src/styleguide-type-tests-gated.test.ts": 1,
  "packages/core/src/styleguide.test.ts": 1,
  "packages/core/src/test/helpers.ts": 1,
  "packages/core/src/typecheck-coverage.test.ts": 1,
  "packages/core/src/uplink-boundary.test.ts": 1,
  "packages/core/src/uplink-isolation.test.ts": 1,
  "packages/core/src/uplink-mod-build-coverage.test.ts": 1,
  "packages/core/src/uplink-tsconfig-parity.test.ts": 1,
  "packages/core/src/uplinkClients.test.ts": 1,
  "packages/core/src/vitest-timeout-convention.test.ts": 1,
  "packages/data/src/FlightsManager/AutoRecordController.test.tsx": 3,
  "packages/data/src/FlightsManager/AutoRecordController.tsx": 4,
  "packages/data/src/FlightsManager/FlightGraph.test.tsx": 1,
  "packages/data/src/FlightsManager/FlightGraph.tsx": 1,
  "packages/data/src/FlightsManager/MissionHistorySource.test.ts": 1,
  "packages/data/src/FlightsManager/MissionHistorySource.ts": 1,
  "packages/data/src/FlightsManager/index.test.tsx": 1,
  "packages/data/src/hooks/deltaVBudget.stream.test.tsx": 2,
  "packages/data/src/hooks/useDataSeries.shim.test.tsx": 2,
  "packages/data/src/hooks/useDataSeries.test.tsx": 2,
  "packages/data/src/hooks/useDataSeries.ts": 3,
  "packages/data/src/hooks/useFlight.test.tsx": 1,
  "packages/data/src/hooks/useOptionalVesselIdentity.ts": 1,
  "packages/data/src/hooks/usePartsLive.undefined.characterise.test.tsx": 2,
  "packages/data/src/hooks/useTopology.undefined.characterise.test.tsx": 2,
  "packages/data/src/hooks/vesselPartsAdapter.ts": 1,
  "packages/data/src/schema/builtinDerivedKeys.ts": 1,
  "packages/data/src/schema/topicFieldCatalog.ts": 1,
  "packages/data/src/schema/uplinkFieldCatalog.test.tsx": 1,
  "packages/data/vitest.config.ts": 1,
  "packages/logger/src/index.ts": 1,
  "packages/logger/src/logger.test.ts": 1,
  "packages/logger/src/ringBuffer.ts": 1,
  "packages/relay/src/index.ts": 2,
  "packages/serial/src/InputMappingTab.test.tsx": 1,
  "packages/serial/src/InputMappingTab.tsx": 2,
  "packages/serial/src/SerialDeviceService.test.ts": 2,
  "packages/serial/src/SerialDeviceService.ts": 1,
  "packages/serial/src/SerialDevicesMenu/CalibrateWizard.test.tsx": 1,
  "packages/serial/src/SerialDevicesMenu/DeviceEditor.tsx": 1,
  "packages/serial/src/SerialDevicesMenu/GamepadLearnWizard.test.tsx": 3,
  "packages/serial/src/SerialDevicesMenu/GamepadLearnWizard.tsx": 2,
  "packages/serial/src/SerialDevicesMenu/SelfDescribingAddWizard.tsx": 1,
  "packages/serial/src/SerialDevicesMenu/index.test.tsx": 1,
  "packages/serial/src/SerialDevicesMenu/index.tsx": 3,
  "packages/serial/src/SerialFab.tsx": 1,
  "packages/serial/src/detectGamepadPack.ts": 2,
  "packages/serial/src/gamepadGlyphs.ts": 2,
  "packages/serial/src/gamepadRoles.ts": 1,
  "packages/serial/src/gamepadShape.ts": 1,
  "packages/serial/src/parsers/analogShaping.ts": 1,
  "packages/serial/src/parsers/jsonState.ts": 1,
  "packages/serial/src/seeds.ts": 1,
  "packages/serial/src/transports/DeviceTransport.ts": 1,
  "packages/serial/src/transports/GamepadPoller.ts": 1,
  "packages/serial/src/transports/GamepadTransport.test.ts": 3,
  "packages/serial/src/transports/GamepadTransport.ts": 4,
  "packages/serial/src/transports/KeyboardTransport.ts": 1,
  "packages/serial/src/transports/WebSerialTransport.ts": 1,
  "packages/serial/vitest.config.ts": 1,
  "packages/sitrep-client/src/auto-command.hook.test.tsx": 2,
  "packages/sitrep-client/src/auto-command.test.ts": 1,
  "packages/sitrep-client/src/bridge.test.tsx": 2,
  "packages/sitrep-client/src/carried-channels-provider.test.tsx": 1,
  "packages/sitrep-client/src/client.test.ts": 2,
  "packages/sitrep-client/src/confirmed-predicted.test.ts": 4,
  "packages/sitrep-client/src/connectivity-history.test.ts": 1,
  "packages/sitrep-client/src/context.test.tsx": 1,
  "packages/sitrep-client/src/control-stream-model.test.ts": 2,
  "packages/sitrep-client/src/currency-events.test.tsx": 2,
  "packages/sitrep-client/src/delay-authority.test.ts": 1,
  "packages/sitrep-client/src/delayed-integration.test.tsx": 1,
  "packages/sitrep-client/src/fleet-position.test.ts": 1,
  "packages/sitrep-client/src/fleet-silence-roster.test.ts": 1,
  "packages/sitrep-client/src/full-history-replay.test.ts": 2,
  "packages/sitrep-client/src/full-history-replay.ts": 1,
  "packages/sitrep-client/src/index.ts": 3,
  "packages/sitrep-client/src/kepler.test.ts": 2,
  "packages/sitrep-client/src/map-topic.test.ts": 1,
  "packages/sitrep-client/src/media/delayed-playout-buffer.viewclock.integration.test.ts": 2,
  "packages/sitrep-client/src/never-reckonable.test.ts": 1,
  "packages/sitrep-client/src/orbit-patches.test.ts": 1,
  "packages/sitrep-client/src/processorEvaluator.test.ts": 2,
  "packages/sitrep-client/src/reckoning-field-scope.test.ts": 2,
  "packages/sitrep-client/src/reckoning-gaps.test.ts": 2,
  "packages/sitrep-client/src/reference-wire-fixture.test.ts": 6,
  "packages/sitrep-client/src/replay-recorder.test.ts": 1,
  "packages/sitrep-client/src/shared-processors.test.ts": 2,
  "packages/sitrep-client/src/timeline-store-raw-fields.test.ts": 1,
  "packages/sitrep-client/src/timeline-store-reading.test.ts": 1,
  "packages/sitrep-client/src/timeline-store-sample-derived-range.test.ts": 1,
  "packages/sitrep-client/src/timeline-store-status.test.ts": 3,
  "packages/sitrep-client/src/timeline-store.test.ts": 5,
  "packages/sitrep-client/src/topic-ownership-reading.test.ts": 1,
  "packages/sitrep-client/src/uplink-health.test.ts": 1,
  "packages/sitrep-client/src/use-command.test.tsx": 6,
  "packages/sitrep-client/src/use-control-stream.test.tsx": 4,
  "packages/sitrep-client/src/use-control-stream.tsx": 2,
  "packages/sitrep-client/src/use-observed-vantage.test.tsx": 1,
  "packages/sitrep-client/src/use-processor.test.tsx": 2,
  "packages/sitrep-client/src/use-route-commands.test.tsx": 2,
  "packages/sitrep-client/src/use-stream.test.tsx": 1,
  "packages/sitrep-client/src/view-clock.test.ts": 1,
  "packages/sitrep-client/src/websocket-transport.test.ts": 2,
  "packages/sitrep-client/vitest.config.ts": 1,
  "packages/ui-kit/tsup.config.ts": 2,
  "packages/ui/vitest.config.ts": 1,
  "packages/uplink-tools/src/render-probe.tsx": 5,
  "packages/uplink-tools/src/render/docs.ts": 1,
  "packages/uplink-tools/src/render/driver.ts": 3,
  "packages/uplink-tools/src/render/minFit.ts": 2,
  "packages/uplink-tools/src/render/render.test.ts": 2,
  "packages/uplink-tools/src/render/scenes.ts": 1,
  "playwright.config.ts": 4,
  "scripts/asyncapi-doc.mjs": 1,
  "scripts/asyncapi/json-schema.mjs": 1,
  "scripts/asyncapi/prose-hygiene.mjs": 1,
  "scripts/decode-bug-report.mjs": 1,
  "scripts/emdash-audit.mjs": 2,
  "scripts/palette-audit.mjs": 1,
  "scripts/release.mjs": 2,
  "scripts/uplink-matrix.mjs": 1,
  "scripts/verify-package-artifact.mjs": 1,
  "tests/playwright/helpers.ts": 1,
  "tests/playwright/main-station.spec.ts": 2,
  "tests/playwright/notes-roundtrip.spec.ts": 2,
  "tests/playwright/serial-degradation.spec.ts": 2,
  "tests/playwright/sitrep-stream-mirror.spec.ts": 1,
  "tests/playwright/sitrep-stream-server-topology.mjs": 1,
  "tests/playwright/sitrep-stream-server.mjs": 1,
  "tests/playwright/uplink-loader.spec.ts": 3,
  "tests/playwright/widget-dom-mirror.spec.ts": 2,
  "tests/playwright/widgets/data-source-status.spec.ts": 1,
  "tests/playwright/widgets/fuel-status.spec.ts": 1,
  "tests/playwright/widgets/panel-header-aside.spec.ts": 2,
};

/**
 * The instrument check. Every other assertion in the gate is
 * `expect(offenders).toEqual([])`, and a scan that walks zero files satisfies
 * all of them: a wrong cwd, a renamed root or a `git ls-files` that errored into
 * an empty string each look exactly like a clean repo.
 *
 * It counts files WALKED, and only that. What the scan FOUND is the debt, which
 * falls as it is paid, so a floor on it would fail the gate for the one outcome
 * it exists to produce; the census is printed beside the verdict instead.
 */
export const SCAN_FLOORS = {
  files: 1302,
} as const;
