/**
 * Every suite in this repo that runs only when a LOCAL-ONLY fixture is on
 * disk, declared so that the set is countable and cannot grow by accident.
 *
 * ## Why this register exists
 *
 * `describe.skipIf(!fixtureExists)` is the right mechanism and each of these
 * suites uses it correctly. What it cannot do is be seen. A skipped suite
 * prints as skipped, which is what a deliberately-skipped suite also prints,
 * so a run whose entire recorded-wire coverage did not execute reads exactly
 * like a run where it did. `pnpm test` reports "passed" either way.
 *
 * All three of these are gated on
 * `local_docs/telemetry-mod/recordings/reference-wire-fixture.json`, which is
 * generated by `mod/Sitrep.Host.IntegrationTests/WireFixtureGeneratorTests.cs`
 * from `reference-session-2026-07-07.json`, a captured KSP session. `local_docs/`
 * is blanket-gitignored, so the fixture is never in CI by construction: these
 * suites CANNOT run there, and saying so once, here, is the honest version of
 * that fact.
 *
 * The generator skips the same way when the recording is absent, so the chain
 * is three links long and every link is silent about being broken.
 *
 * ## What to do when you add one
 *
 * Add the entry. `fixture-gated-suites.test.ts` fails on an unregistered
 * `skipIf` suite and on a registered one whose `tests` count has drifted, so
 * the register cannot quietly stop describing the code. If your suite can run
 * off a fixture that could live in the repo, put the fixture in the repo
 * instead and do not add an entry: a suite that runs is worth more than a
 * suite that is well documented.
 */
export interface FixtureGatedSuite {
  /** Repo-relative path to the test file. */
  file: string;
  /** Repo-relative path to the fixture whose presence gates it. */
  fixture: string;
  /**
   * Number of real `it(...)` bodies inside the gated describe, EXCLUDING the
   * one-line "SKIPPED: ..." placeholder each suite registers so the skip is
   * visible in a reporter. This is the coverage that does not run.
   */
  tests: number;
  /** What is lost while the fixture is absent, in one line. */
  covers: string;
}

export const FIXTURE_GATED_SUITES: readonly FixtureGatedSuite[] = [
  {
    file: "packages/sitrep-client/src/reference-wire-fixture.test.ts",
    fixture: "local_docs/telemetry-mod/recordings/reference-wire-fixture.json",
    tests: 2,
    covers:
      "the full TS SDK replayed against genuine engine output: derived channels, epoch/ghost handling, staleness and certainty, the ViewClock estimator",
  },
  {
    file: "packages/components/src/WarpControl/dual-run.test.tsx",
    fixture: "local_docs/telemetry-mod/recordings/reference-wire-fixture.json",
    tests: 1,
    covers:
      "WarpControl's render golden taken off a real recording's wire, across the recording's three rewinds",
  },
];

/** Total `it()` bodies that do not run when the fixtures are absent. */
export function fixtureGatedTestCount(): number {
  return FIXTURE_GATED_SUITES.reduce((sum, suite) => sum + suite.tests, 0);
}
