import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { styleguideScanRoots } from "./styleguideScanRoots";

/**
 * The scan behind `styleguide-panel-body.test.ts`, in its own module so the gate
 * and the debt generator cannot drift apart. Same split, and for the same
 * reason, as `comment-stacks.scan.ts`.
 *
 * THE RULE: a widget gives its `Panel` a body by passing `sections`, not by
 * passing children. `sections` is what lets Panel own the wide-layout decision,
 * which is the thing a widget cannot make for itself: it cannot see the width it
 * was given, so a widget composing its own body runs every group down one column
 * and wastes the width of a landscape tile.
 *
 * So the population this counts is `<Panel>` elements that render CHILDREN. A
 * converted panel is self-closing, which is what makes the rule cheap to state
 * and impossible to half-satisfy: you cannot pass `sections` and keep a body and
 * have the scan call it done.
 *
 * ONE exception, and it already had its own prop before this gate existed:
 * `floatingHeader`, the widget that is wholly a drawing. Its content IS the
 * panel rather than a section of it, the header floats over the content and the
 * body bleeds to the chrome. A map or a globe keeps its children.
 */

/** JSX only. A `.ts` file cannot contain a `<Panel>` element. */
const SOURCE_RE = /\.tsx$/;

/**
 * Tests are outside the population, and deliberately so.
 *
 * The children path is not going away: `floatingHeader` uses it, and so does
 * every hand-composed `Panel.Container` / `Panel.Body` arrangement. Panel's own
 * suite has to be able to render it, and a gate that forbade that would be
 * asking the kit to stop testing its own API. What the gate is about is WIDGETS,
 * and a widget does not live in a test file.
 */
const TEST_RE = /\.(test|spec)\.tsx$/;

/** Generated by path. A codegen template's JSX is not anyone's to convert. */
const GENERATED_PATH_RE =
  /(?:\.(?:g|generated)\.[a-z]+|\/(?:generated|__generated__)\/)/;

/** Generated by header, for output whose filename gives nothing away. */
const GENERATED_HEADER_RE = /<auto-?generated|@generated|DO NOT EDIT/i;

export interface PanelBodyUse {
  /** 1-indexed line of the `<Panel`. */
  line: number;
  /** The opening tag's attribute text, for the failure message. */
  attrs: string;
}

/**
 * Source with its comments blanked out, preserving every byte offset and every
 * newline so reported line numbers still point at the real line.
 *
 * Not cosmetic. Two of the first three hits a comment-blind version of this scan
 * produced were prose: Panel's own doc comment says "the `<Panel>` it returns",
 * and `GridItemContent` repeats the sentence. A ratchet whose seeded list names
 * a comment is one nobody can ever clear.
 */
export function stripComments(source: string): string {
  let out = "";
  let i = 0;
  const n = source.length;
  while (i < n) {
    const c = source[i];
    const next = source[i + 1];
    if (c === "/" && next === "/") {
      while (i < n && source[i] !== "\n") {
        out += " ";
        i++;
      }
      continue;
    }
    if (c === "/" && next === "*") {
      while (i < n && !(source[i] === "*" && source[i + 1] === "/")) {
        out += source[i] === "\n" ? "\n" : " ";
        i++;
      }
      out += "  ";
      i += 2;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") {
      const quote = c;
      out += c;
      i++;
      while (i < n && source[i] !== quote) {
        if (source[i] === "\\") {
          out += source[i];
          i++;
          if (i < n) {
            out += source[i];
            i++;
          }
          continue;
        }
        out += source[i];
        i++;
      }
      if (i < n) {
        out += source[i];
        i++;
      }
      continue;
    }
    out += c;
    i++;
  }
  return out;
}

/**
 * Every `<Panel …>` opening tag in one file, with whether it closed itself.
 *
 * A hand-written walk rather than a regex because the attribute list routinely
 * contains a `>` that is not the tag's: `panelAside={<Badge />}` and
 * `onPick={(a) => set(a)}` both appear in the widget set. Braces and strings are
 * tracked so only a `>` at brace depth zero ends the tag.
 */
export function panelTagsIn(source: string): {
  line: number;
  attrs: string;
  selfClosing: boolean;
}[] {
  const found: { line: number; attrs: string; selfClosing: boolean }[] = [];
  const needle = "<Panel";
  let from = 0;
  for (;;) {
    const at = source.indexOf(needle, from);
    if (at === -1) break;
    // `<PanelBody`, `<PanelSplit`, `<Panel.Header` and friends are the
    // hand-composed parts, which this gate says nothing about.
    const after = source[at + needle.length];
    if (after !== undefined && /[A-Za-z0-9_$.]/.test(after)) {
      from = at + needle.length;
      continue;
    }
    let i = at + needle.length;
    let depth = 0;
    let end = -1;
    while (i < source.length) {
      const c = source[i];
      if (c === '"' || c === "'" || c === "`") {
        const quote = c;
        i++;
        while (i < source.length && source[i] !== quote) {
          if (source[i] === "\\") i++;
          i++;
        }
        i++;
        continue;
      }
      if (c === "{") {
        depth++;
        i++;
        continue;
      }
      if (c === "}") {
        depth--;
        i++;
        continue;
      }
      if (c === ">" && depth === 0) {
        end = i;
        break;
      }
      i++;
    }
    if (end === -1) break;
    let back = end - 1;
    while (back > at && /\s/.test(source[back])) back--;
    found.push({
      line: source.slice(0, at).split("\n").length,
      attrs: source.slice(at + needle.length, end),
      selfClosing: source[back] === "/",
    });
    from = end + 1;
  }
  return found;
}

/** The `<Panel>`s in one file's source that still carry a body. */
export function panelBodiesIn(source: string): PanelBodyUse[] {
  return panelTagsIn(stripComments(source))
    .filter((tag) => !tag.selfClosing && !/\bfloatingHeader\b/.test(tag.attrs))
    .map(({ line, attrs }) => ({ line, attrs: attrs.trim() }));
}

export interface PanelBodyScan {
  /** Widget-side `.tsx` files actually read. */
  scanned: number;
  /** Files skipped as a test or as generated. */
  skipped: number;
  /**
   * Every `<Panel …>` opening tag seen, bodies and converted ones alike.
   *
   * The instrument-check number, and the reason it counts TAGS rather than
   * bodies: converting a widget turns a body into a self-closing tag, so this
   * total does not fall as the debt is cleared. A floor on the debt population
   * itself would have been a floor the work is trying to walk through, and the
   * shrink-only guard refuses to lower a floor, so finishing the job would have
   * meant fighting the gate.
   */
  tags: number;
  /** Path to body count, for every file carrying at least one. */
  counts: Map<string, number>;
  /** Path to the uses themselves, for the failure messages. */
  uses: Map<string, PanelBodyUse[]>;
}

function repoRoot(): string {
  return execFileSync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  }).trim();
}

/**
 * Tracked files AND untracked-but-not-ignored ones, the same listing the comment
 * ratchet uses and for the same reason: a `<Panel>` body written into a brand
 * new widget is exactly the case this exists to catch, and a tracked-only
 * listing would report it clean until the commit after the one that added it.
 */
export function scanPanelBodies(): PanelBodyScan {
  const root = repoRoot();
  const roots = styleguideScanRoots(root).map((r) => `${r}/`);
  const counts = new Map<string, number>();
  const uses = new Map<string, PanelBodyUse[]>();
  let tags = 0;
  const all = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  )
    .split("\n")
    .filter((f) => SOURCE_RE.test(f) && roots.some((r) => f.startsWith(r)));
  const kept = all.filter(
    (f) => !TEST_RE.test(f) && !GENERATED_PATH_RE.test(f),
  );
  let skipped = all.length - kept.length;
  let scanned = 0;

  for (const file of kept) {
    let source: string;
    try {
      source = readFileSync(join(root, file), "utf8");
    } catch {
      continue;
    }
    if (GENERATED_HEADER_RE.test(source.split("\n").slice(0, 5).join("\n"))) {
      skipped++;
      continue;
    }
    scanned++;
    const stripped = stripComments(source);
    tags += panelTagsIn(stripped).length;
    const hits = panelBodiesIn(source);
    if (hits.length > 0) {
      counts.set(file, hits.length);
      uses.set(file, hits);
    }
  }
  return { scanned, skipped, tags, counts, uses };
}
