// @vitest-environment node
//
// Node realm rather than the package's jsdom default, matching
// `uplink-isolation.test.ts`: the shrink-only half transpiles the allowlist at a
// git ref through esbuild, which asserts a real TextEncoder/Uint8Array realm.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { transformSync } from "esbuild";
import { describe, expect, it } from "vitest";
import {
  BANNER_COMMENT_DEBT,
  SCAN_FLOORS,
  SCHEME_MIN,
  SECTIONED_CEILINGS,
} from "./banner-comments.allowlist";

/**
 * Banner-comment ratchet. CLAUDE.md has always said "no banner comments above an
 * obvious call" and nothing enforced it, so the population grew for months.
 *
 * THE DEFINITION, in one sentence: a banner comment is a `//` line whose whole
 * content is three or more `-`, `=` or `*` rule characters, a title, then three
 * or more rule characters again, in a hand-written source file, and it is a
 * DEFECT unless its file carries `SCHEME_MIN` or more of them, in which case the
 * banners are dividing a long table or a long test into real sections.
 *
 * TWO NUMBERS, AND THEY DISAGREE ON PURPOSE. A loose scan for "a comment line
 * starting with three rule characters" finds 1,092 lines across 216 files. This
 * ratchet counts 341 lines across 78 files, of which 64 across 43 files are
 * graded as debt. Neither number is wrong, they measure different things: 665 of
 * the loose scan's hits are a bare `// ------------` with no title at all, which
 * is a doc-comment separator and labels nothing, and another 86 are a comment
 * paragraph that merely opens with rule characters and runs on. Re-running the
 * loose regex and finding 1,092 is not evidence that this ratchet is broken.
 *
 * The rule this enforces is about DECORATION, not about section structure. See
 * `banner-comments.allowlist.ts` for the full statement of what the shape
 * deliberately does not match and how the two are told apart.
 *
 * Lives in `packages/core` because core holds this repo's cross-package
 * ratchets, and because `pnpm test` in core is the `test` job CI actually runs.
 * A type-level check would gate nothing: `pnpm typecheck` is not a CI job.
 */

const BASE_REF = process.env.RATCHET_BASE_REF ?? "origin/staging";
const ALLOWLIST_PATH = "packages/core/src/banner-comments.allowlist.ts";

/**
 * Rule characters, a title containing at least one letter, rule characters
 * again. The lookahead is what separates a banner from a doc-comment separator:
 * without it, `[-=*]{3,}.*[-=*]{3,}` matches a bare `// ---------` by splitting
 * the run of dashes in two, and the count goes from 341 to over a thousand.
 */
// Box-drawing runs count as rule characters, not only ASCII. The first version
// of this matched `[-=*]` alone and so could not see `// -- Title --` written
// with U+2500 or U+2550, which is 134 files: a larger population than the one it
// was guarding. A gate blind to the commonest spelling of the thing it forbids
// reports a clean repo, and planting an ASCII banner to prove it fires shares
// the blindness, so it proves nothing about the shape it cannot match.
const RULE_CHARS = "-=*\u2500\u2501\u2504\u2505\u2508\u2509\u254c\u254d\u2550";
const BANNER_RE = new RegExp(
  `^[ \t]*//[ \t]*[${RULE_CHARS}]{3,}(?=.*[A-Za-z]).*[${RULE_CHARS}]{3,}[ \t]*$`,
);

/** Languages whose line comment is `//`. Nothing else can carry the shape. */
const SOURCE_RE = /\.(ts|tsx|js|jsx|mjs|cjs|cs)$/;

/** Generated by path. A codegen template's dividers are not anyone's to fix. */
const GENERATED_PATH_RE = /(?:\.(?:g|generated)\.[a-z]+|\/generated\/)/;

/** Generated by header, for output whose filename gives nothing away. */
const GENERATED_HEADER_RE = /<auto-?generated|@generated|DO NOT EDIT/i;

function repoRoot(): string {
  return execFileSync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  }).trim();
}

/**
 * Tracked files AND untracked-but-not-ignored ones. The untracked half is
 * load-bearing: a banner written into a brand new file is exactly the case this
 * is meant to catch, and a tracked-only listing would report it clean until the
 * commit after the one that introduced it.
 */
function sourceFiles(root: string): { kept: string[]; generated: number } {
  const all = execFileSync(
    "git",
    ["ls-files", "--cached", "--others", "--exclude-standard"],
    { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  )
    .split("\n")
    .filter((f) => SOURCE_RE.test(f));
  const kept = all.filter((f) => !GENERATED_PATH_RE.test(f));
  return { kept, generated: all.length - kept.length };
}

interface Scan {
  /** Hand-written source files actually read. */
  scanned: number;
  /** Files skipped as generated, by path and by header together. */
  generated: number;
  /** Path to banner count, for every file carrying at least one. */
  counts: Map<string, number>;
  /** Path to the banner lines themselves, for the failure messages. */
  lines: Map<string, string[]>;
}

function scan(): Scan {
  const root = repoRoot();
  const counts = new Map<string, number>();
  const lines = new Map<string, string[]>();
  const listing = sourceFiles(root);
  let scanned = 0;
  let generated = listing.generated;
  for (const file of listing.kept) {
    let source: string;
    try {
      source = readFileSync(join(root, file), "utf8");
    } catch {
      continue;
    }
    const fileLines = source.split("\n");
    if (GENERATED_HEADER_RE.test(fileLines.slice(0, 5).join("\n"))) {
      generated++;
      continue;
    }
    scanned++;
    const hits = fileLines.filter((l) => BANNER_RE.test(l));
    if (hits.length > 0) {
      counts.set(file, hits.length);
      lines.set(
        file,
        hits.map((l) => l.trim()),
      );
    }
  }
  return { scanned, generated, counts, lines };
}

const RESULT = scan();

describe("banner comments", () => {
  /**
   * The instrument check, before any assertion that can pass by finding
   * nothing. Every other test in this file is `expect(offenders).toEqual([])`,
   * and a scan that walks zero files satisfies all of them. A wrong cwd, a
   * renamed root, a `git ls-files` that errors into an empty string: each looks
   * exactly like a clean repo.
   *
   * The floors are far below the seeded numbers rather than equal to them, so
   * ordinary churn does not touch this and only a broken enumeration does.
   */
  it("actually scanned the source tree", () => {
    const banners = [...RESULT.counts.values()].reduce((a, b) => a + b, 0);
    const summary = [
      `scanned ${RESULT.scanned} files`,
      `${RESULT.generated} skipped as generated`,
      `${RESULT.counts.size} files carry a banner`,
      `${banners} banner lines`,
    ].join(", ");
    // The census, not a boolean. A number in the log is what lets the next
    // person tell "found nothing" from "looked at nothing", and it is only
    // visible under `--reporter=verbose`; the default reporter mutes console
    // output for tests that pass.
    console.info(`[banner-comments] ${summary}`);
    expect(RESULT.scanned, summary).toBeGreaterThanOrEqual(SCAN_FLOORS.files);
    expect(RESULT.counts.size, summary).toBeGreaterThanOrEqual(
      SCAN_FLOORS.filesWithBanner,
    );
    expect(banners, summary).toBeGreaterThanOrEqual(SCAN_FLOORS.banners);
  });

  /**
   * The instrument check for the matcher itself, which the file-count floor
   * above cannot give: `scanned` stays healthy if `BANNER_RE` is edited into
   * something that matches nothing, and the debt assertions then read as a
   * repo that cleaned itself overnight.
   *
   * Both strings are built from pieces so this file contains no line that its
   * own scan would report.
   */
  it("matches a banner and not a doc-comment separator", () => {
    const rule = "-".repeat(3);
    expect(BANNER_RE.test(`// ${rule} Registration ${rule}`)).toBe(true);
    expect(BANNER_RE.test(`  // ${rule}- recorded calls ${rule}-`)).toBe(true);
    expect(BANNER_RE.test(`// ${"=".repeat(4)} Time ${"=".repeat(4)}`)).toBe(
      true,
    );
    expect(BANNER_RE.test(`// ${"-".repeat(60)}`)).toBe(false);
    expect(BANNER_RE.test(`// ${rule} a paragraph that wraps onward`)).toBe(
      false,
    );
    expect(BANNER_RE.test(`// -- a two-dash bullet, not a banner`)).toBe(false);
  });

  /**
   * Growth. A file with a banner and no entry, or a file whose count has gone
   * up, both land here. The count is per file rather than per repo so the
   * message names the file, which is the whole difference between a gate
   * somebody acts on and a gate somebody mutes.
   */
  it("adds no banner comment to a file that is not already carrying one", () => {
    const offenders: string[] = [];
    for (const [file, count] of RESULT.counts) {
      // Debt list FIRST. Consulting the scheme rule first would let a third
      // banner promote a two-banner debt file out of debt, and the ratchet
      // would report that as a cleanup.
      const budget = BANNER_COMMENT_DEBT[file];
      if (budget !== undefined) {
        if (count > budget) {
          offenders.push(
            `${file}: ${count} banner(s), debt list says ${budget}`,
          );
        }
        continue;
      }
      if (count >= SCHEME_MIN) continue;
      offenders.push(
        `${file}: ${count} banner(s), unlisted -> ${RESULT.lines.get(file)?.[0]}`,
      );
    }
    expect(
      offenders,
      [
        "A banner comment appeared where the ratchet was not expecting one.",
        "",
        'CLAUDE.md: no banner comments ("// --- Registration ---") above an',
        "obvious call. Delete the rule characters. If the comment is worth",
        "keeping, keep the sentence and drop the decoration; if it only restates",
        "the call below it, drop the whole line.",
        "",
        "Do NOT add an entry to banner-comments.allowlist.ts. The debt list is",
        "shrink-only and a new entry means new code just created the violation.",
      ].join("\n"),
    ).toEqual([]);
  });

  /**
   * The staleness direction, and the reason the debt counts are exact rather
   * than ceilings. Nothing else notices when a banner is cleaned, so the entry
   * sits there reading as work remaining, and the list can never reach zero by
   * attrition. With this, every cleanup anywhere is an automatic reduction and
   * the next person to touch the file is told to write the smaller number down.
   */
  it("records no banner that is already gone", () => {
    const stale: string[] = [];
    for (const [file, expected] of Object.entries(BANNER_COMMENT_DEBT)) {
      const actual = RESULT.counts.get(file) ?? 0;
      if (actual < expected) {
        stale.push(`${file} says ${expected}, actually ${actual}`);
      }
    }
    expect(
      stale,
      [
        "The debt list claims more banners than the file still has.",
        "",
        "Good news: something cleaned them. Lower the number, or delete the line",
        "when the count reaches 0, so the list keeps telling the truth about what",
        "is left. A debt list that outlives its debt reads as work remaining and",
        "hides how close to zero this is.",
      ].join("\n"),
    ).toEqual([]);
  });

  /**
   * The hole the debt list alone leaves: writing `SCHEME_MIN` banners into a
   * clean file in one commit clears the scheme rule on arrival, and no per-file
   * check has an opinion about it. A population ceiling does.
   *
   * The offending files are computed here rather than stored, so this closes the
   * hole without putting a file list in the allowlist. That matters: two of the
   * files in this population are legacy schema files whose paths carry a vendor
   * name that `vendor-name.test.ts` is separately driving out of the tree.
   */
  it("does not grow the population of files that section with banners", () => {
    const sectioned = [...RESULT.counts].filter(
      ([file, n]) => BANNER_COMMENT_DEBT[file] === undefined && n >= SCHEME_MIN,
    );
    const banners = sectioned.reduce((a, [, n]) => a + n, 0);
    const detail = sectioned
      .map(([file, n]) => `  ${file}: ${n}`)
      .sort()
      .join("\n");
    const message = [
      `${sectioned.length} files section with banners, ${banners} banner lines.`,
      `Ceilings: ${SECTIONED_CEILINGS.files} files, ${SECTIONED_CEILINGS.banners} lines.`,
      "",
      "Dividing a long table into named sections is tolerated; growing the set",
      "of files that do it is not, because that is how the exemption becomes the",
      "rule. Write the section header as a plain sentence instead.",
      "",
      "The full population, so the new one is easy to spot:",
      detail,
    ].join("\n");
    expect(sectioned.length, message).toBeLessThanOrEqual(
      SECTIONED_CEILINGS.files,
    );
    expect(banners, message).toBeLessThanOrEqual(SECTIONED_CEILINGS.banners);
  });

  describe("the debt list only ever shrinks", () => {
    /**
     * The list at `BASE_REF`, or `undefined` when there is no base (first land,
     * shallow clone, detached CI ref) and there is nothing to diff against.
     * Soft-pass in that case, same as the other ratchets do.
     */
    function baseAllowlist(): Record<string, unknown> | undefined {
      let source: string;
      try {
        source = execFileSync(
          "git",
          ["show", `${BASE_REF}:${ALLOWLIST_PATH}`],
          {
            cwd: repoRoot(),
            encoding: "utf8",
            stdio: ["ignore", "pipe", "pipe"],
          },
        );
      } catch {
        return undefined;
      }
      const js = transformSync(source, { loader: "ts", format: "cjs" }).code;
      const module_ = { exports: {} as Record<string, unknown> };
      new Function("module", "exports", js)(module_, module_.exports);
      return module_.exports;
    }

    function additions(
      current: Record<string, number>,
      base: Record<string, number>,
    ): string[] {
      const added: string[] = [];
      for (const [file, count] of Object.entries(current)) {
        const before = base[file];
        if (before === undefined) added.push(`${file} (new entry: ${count})`);
        else if (count > before) added.push(`${file} (${before} -> ${count})`);
      }
      return added;
    }

    it("BANNER_COMMENT_DEBT", () => {
      const base = baseAllowlist();
      if (!base) return;
      const before = base.BANNER_COMMENT_DEBT as
        | Record<string, number>
        | undefined;
      if (!before) return;
      expect(
        additions(BANNER_COMMENT_DEBT, before),
        `Debt entries may only be REMOVED or lowered, never added or raised, vs ${BASE_REF}.`,
      ).toEqual([]);
    });

    /**
     * The ceilings are data in the same file and would otherwise be raisable
     * with a one-digit edit that reads as maintenance. Same rule as the debt
     * list: down only.
     */
    it("SECTIONED_CEILINGS", () => {
      const base = baseAllowlist();
      if (!base) return;
      const before = base.SECTIONED_CEILINGS as
        | { files: number; banners: number }
        | undefined;
      if (!before) return;
      const raised: string[] = [];
      if (SECTIONED_CEILINGS.files > before.files) {
        raised.push(`files (${before.files} -> ${SECTIONED_CEILINGS.files})`);
      }
      if (SECTIONED_CEILINGS.banners > before.banners) {
        raised.push(
          `banners (${before.banners} -> ${SECTIONED_CEILINGS.banners})`,
        );
      }
      expect(
        raised,
        `The tolerated-population ceilings may only be LOWERED, vs ${BASE_REF}.`,
      ).toEqual([]);
    });
  });
});
