/**
 * Writes the widget and extension stories from the render harness's own
 * configs and fixtures: one CSF file per render config, one story per scene
 * (and per install profile the scene declares), into `dist/stories/`.
 *
 * The output is build output, rebuilt by every `storybook`, `build-storybook`
 * and `typecheck` run, so a fixture added, renamed or deleted is reflected the
 * next time anything looks, with no committed copy to fall out of step.
 */
import { mkdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  SizeMode,
  WidgetRenderConfig,
} from "../../components/scripts/widgetRenderHarness";
import { sceneFixtures } from "../../components/scripts/widgetRenderHarness";
import { listWidgets } from "../../components/scripts/widgets";
import { fixtureProfiles } from "../../components/src/test/installProfile";
import { EXTENSION_SCENES, EXTRA_SCENES, UNFIXTURED_WIDGETS } from "./coverage";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../dist/stories");
const SRC = resolve(HERE, "../src");
const REPO = resolve(HERE, "../../..");

/** An identifier a story export can be named: `eva-suit-link-lost` becomes `EvaSuitLinkLost`. */
function exportName(slug: string, taken: Set<string>): string {
  const words = slug.split(/[^A-Za-z0-9]+/).filter(Boolean);
  let name = words.map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  if (/^[0-9]/.test(name)) name = `Scene${name}`;
  let unique = name;
  for (let n = 2; taken.has(unique); n++) unique = `${name}${n}`;
  taken.add(unique);
  return unique;
}

function fileSlug(label: string): string {
  return label.replace(/[^A-Za-z0-9]+/g, "-");
}

function importPath(fromDir: string, file: string): string {
  const rel = relative(fromDir, file);
  return rel.startsWith(".") ? rel : `./${rel}`;
}

/** The mode's per-render extras: what `WidgetScene` takes as `mode`. */
function modeExtras(mode: SizeMode): Record<string, unknown> {
  const extras: Record<string, unknown> = {};
  if (mode.config) extras.config = mode.config;
  if (mode.clicks) extras.clicks = mode.clicks;
  if (mode.hovers) extras.hovers = mode.hovers;
  return extras;
}

function modesFor(config: WidgetRenderConfig, scene: string): SizeMode[] {
  return config.modes.filter(
    (m) => !m.forFixtures || m.forFixtures.includes(scene),
  );
}

interface StoryEntry {
  exportName: string;
  name: string;
  fixtureVar: string;
  profile?: string;
  mode: SizeMode;
  modeNames: string[];
}

const HEADER =
  "// Generated by packages/storybook/scripts/generate-stories.ts.\n";

function metaBlock(opts: {
  title: string;
  widgetId: string;
  modes: SizeMode[];
}): string {
  const modeMap = Object.fromEntries(
    opts.modes
      .filter((m) => Object.keys(modeExtras(m)).length > 0)
      .map((m) => [m.name, modeExtras(m)]),
  );
  const modes =
    Object.keys(modeMap).length > 0
      ? `const MODES = ${JSON.stringify(modeMap, null, 2)};\n\n`
      : "";
  return `${modes}const meta = {
  title: ${JSON.stringify(opts.title)},
  component: WidgetScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  args: { widgetId: ${JSON.stringify(opts.widgetId)} },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    withhold: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
    mode: { control: false },
  },
} satisfies Meta<typeof WidgetScene>;

export default meta;
type Story = StoryObj<typeof meta>;
`;
}

function storyBlock(s: StoryEntry): string {
  const extras = modeExtras(s.mode);
  const args = [
    `fixture: ${s.fixtureVar}`,
    `w: ${s.mode.w}`,
    `h: ${s.mode.h}`,
    Object.keys(extras).length > 0
      ? `mode: MODES[${JSON.stringify(s.mode.name)}]`
      : undefined,
    s.profile ? `profile: ${JSON.stringify(s.profile)}` : undefined,
  ].filter(Boolean);
  return `
/** Sizes this scene renders at in the harness: ${s.modeNames.join(", ")}. */
export const ${s.exportName}: Story = {
  name: ${JSON.stringify(s.name)},
  args: { ${args.join(", ")} },
};
`;
}

async function writeWidgetFile(
  config: WidgetRenderConfig,
): Promise<{ file: string; stories: number }> {
  const label = config.label ?? config.widgetId;
  const file = resolve(OUT, "widgets", `${fileSlug(label)}.stories.tsx`);
  const dir = dirname(file);
  const scenes = await sceneFixtures(config);
  const taken = new Set<string>();
  const imports: string[] = [];
  const stories: StoryEntry[] = [];
  scenes.forEach((scene, i) => {
    const fixtureVar = `scene${i}`;
    imports.push(
      `import ${fixtureVar} from ${JSON.stringify(importPath(dir, scene.file))};`,
    );
    const modes = modesFor(config, scene.name);
    if (modes.length === 0) return;
    const profiles = fixtureProfiles(scene.data);
    const installs = profiles.length > 0 ? profiles : [undefined];
    for (const profile of installs) {
      const name = profile ? `${scene.name} @ ${profile}` : scene.name;
      stories.push({
        exportName: exportName(name, taken),
        name,
        fixtureVar,
        profile,
        mode: modes.find((m) => m.name.startsWith("default")) ?? modes[0],
        modeNames: modes.map((m) => m.name),
      });
    }
  });
  if (label === config.widgetId) {
    for (const extra of EXTRA_SCENES.filter(
      (e) => e.widgetId === config.widgetId,
    )) {
      const fixtureVar = `extra${stories.length}`;
      const file = resolve(REPO, extra.fixture);
      imports.push(
        `import ${fixtureVar} from ${JSON.stringify(importPath(dir, file))};`,
      );
      const name = basename(file, ".json");
      stories.push({
        exportName: exportName(name, taken),
        name,
        fixtureVar,
        mode: { name: "extra", w: extra.w, h: extra.h },
        modeNames: [`${extra.w}x${extra.h}, through its own probe`],
      });
    }
  }
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    `import { WidgetScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "WidgetScene")))};`,
    ...imports,
    "",
    metaBlock({
      title: `Widgets/${label}`,
      widgetId: config.widgetId,
      modes: config.modes,
    }),
    ...stories.map(storyBlock),
  ].join("\n");
  await writeFile(file, body);
  return { file, stories: stories.length };
}

async function writeUnfixturedFile(): Promise<number> {
  const file = resolve(OUT, "widgets", "unfixtured.stories.tsx");
  const dir = dirname(file);
  const taken = new Set<string>();
  const stories = UNFIXTURED_WIDGETS.map(
    (w) => `
/** No fixture exists for this widget: it renders unfed. ${w.reason} */
export const ${exportName(w.widgetId, taken)}: Story = {
  name: ${JSON.stringify(w.widgetId)},
  args: { widgetId: ${JSON.stringify(w.widgetId)}, fixture: {}, w: ${w.w}, h: ${w.h} },
};
`,
  );
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    `import { WidgetScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "WidgetScene")))};`,
    "",
    `const meta = {
  title: "Widgets/(unfixtured)",
  component: WidgetScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
  },
} satisfies Meta<typeof WidgetScene>;

export default meta;
type Story = StoryObj<typeof meta>;
`,
    ...stories,
  ].join("\n");
  await writeFile(file, body);
  return stories.length;
}

async function writeExtensionsFile(): Promise<number> {
  const file = resolve(OUT, "extensions", "extensions.stories.tsx");
  const dir = dirname(file);
  const taken = new Set<string>();
  const fixtures = new Map<string, string>();
  const imports: string[] = [];
  const fixtureVar = (path: string): string => {
    const known = fixtures.get(path);
    if (known) return known;
    const name = `scene${fixtures.size}`;
    fixtures.set(path, name);
    imports.push(
      `import ${name} from ${JSON.stringify(importPath(dir, resolve(REPO, path)))};`,
    );
    return name;
  };
  const stories = EXTENSION_SCENES.map(
    (e) => `
/** \`${e.id}\` switched on in \`${e.widgetId}\`. Untick \`enabled\` to see the host without it. */
export const ${exportName(e.id, taken)}: ExtensionStory = {
  name: ${JSON.stringify(e.id)},
  args: {
    widgetId: ${JSON.stringify(e.widgetId)},
    fixture: ${fixtureVar(e.fixture)},
    w: ${e.w},
    h: ${e.h},
    extension: ${JSON.stringify(e.id)},
    enabled: true,
  },
};
`,
  );
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { ExtensionScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "ExtensionScene")))};`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    ...imports,
    "",
    `const meta = {
  title: "Extensions",
  component: ExtensionScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    extension: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
  },
} satisfies Meta<typeof ExtensionScene>;

export default meta;
type ExtensionStory = StoryObj<typeof meta>;
`,
    ...stories,
  ].join("\n");
  await writeFile(file, body);
  return stories.length;
}

async function main(): Promise<void> {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(resolve(OUT, "widgets"), { recursive: true });
  await mkdir(resolve(OUT, "extensions"), { recursive: true });

  const configs = listWidgets();
  let widgetStories = 0;
  const covered = new Set<string>();
  for (const config of configs) {
    const { stories } = await writeWidgetFile(config);
    widgetStories += stories;
    if (stories > 0) covered.add(config.widgetId);
  }
  const unfixtured = await writeUnfixturedFile();
  for (const w of UNFIXTURED_WIDGETS) covered.add(w.widgetId);
  const extensions = await writeExtensionsFile();

  await writeFile(
    resolve(OUT, "coverage.json"),
    `${JSON.stringify({ widgets: [...covered].sort(), extensions: EXTENSION_SCENES.map((e) => e.id).sort() }, null, 2)}\n`,
  );
  console.log(
    `generate-stories: ${configs.length} render configs -> ${widgetStories} widget stories over ${covered.size} widgets, ${unfixtured} unfixtured, ${extensions} extension stories`,
  );
}

await main();
