/**
 * Writes the widget and extension stories from the render harness's own
 * configs and fixtures: one CSF file per render config, one story per scene
 * (and per install profile the scene declares), into `dist/stories/`.
 *
 * The output is build output, rebuilt by every `storybook`, `build-storybook`
 * and `typecheck` run, so a fixture added, renamed or deleted is reflected the
 * next time anything looks, with no committed copy to fall out of step.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { basename, dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { storyNameFromExport, toId } from "storybook/internal/csf";
import type {
  SizeMode,
  WidgetRenderConfig,
} from "../../components/scripts/widgetRenderHarness";
import { sceneFixtures } from "../../components/scripts/widgetRenderHarness";
import { listWidgets } from "../../components/scripts/widgets";
import { fixtureProfiles } from "../../components/src/test/installProfile";
import {
  readJsonObject,
  resolveUplinkPackage,
} from "../../uplink-tools/src/render/context";
import { UI_KIT_PRESETS } from "../src/uiKitPresets";
import { EXTENSION_SCENES, EXTRA_SCENES, UNFIXTURED_WIDGETS } from "./coverage";
import { writeUiKitStories } from "./uikit-stories";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../dist/stories");
const SRC = resolve(HERE, "../src");
const REPO = resolve(HERE, "../../..");

/** What a listing is: a registered widget, a registered augment or contribution, or a ui-kit export. */
export type TargetKind = "widget" | "extension" | "primitive";

/**
 * The story ids each widget, extension and ui-kit export is shown under, in
 * the order the stories are written, named as Storybook's own indexer names
 * them. Written to `review-targets.json` for the review sheet.
 */
const TARGETS: Record<TargetKind, Record<string, string[]>> = {
  widget: {},
  extension: {},
  primitive: {},
};

function target(
  kind: TargetKind,
  id: string,
  title: string,
  exportName: string,
): void {
  TARGETS[kind][id] ??= [];
  TARGETS[kind][id].push(toId(title, storyNameFromExport(exportName)));
}

/** An identifier a story export can be named: `eva-suit-link-lost` becomes `EvaSuitLinkLost`. */
function exportName(slug: string, taken: Set<string>): string {
  const words = slug.split(/[^A-Za-z0-9]+/).filter(Boolean);
  let name = words.map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  if (/^[0-9]/.test(name)) name = `Scene${name}`;
  let unique = name;
  for (let n = 2; taken.has(unique); n++) unique = `${name}${n}`;
  taken.add(unique);
  return unique;
}

function fileSlug(label: string): string {
  return label.replace(/[^A-Za-z0-9]+/g, "-");
}

function importPath(fromDir: string, file: string): string {
  const rel = relative(fromDir, file);
  return rel.startsWith(".") ? rel : `./${rel}`;
}

/** The mode's per-render extras: what `WidgetScene` takes as `mode`. */
function modeExtras(mode: SizeMode): Record<string, unknown> {
  const extras: Record<string, unknown> = {};
  if (mode.config) extras.config = mode.config;
  if (mode.clicks) extras.clicks = mode.clicks;
  if (mode.hovers) extras.hovers = mode.hovers;
  return extras;
}

function modesFor(config: WidgetRenderConfig, scene: string): SizeMode[] {
  return config.modes.filter(
    (m) => !m.forFixtures || m.forFixtures.includes(scene),
  );
}

interface StoryEntry {
  exportName: string;
  name: string;
  fixtureVar: string;
  profile?: string;
  mode: SizeMode;
  modeNames: string[];
}

const HEADER =
  "// Generated by packages/storybook/scripts/generate-stories.ts.\n";

function metaBlock(opts: {
  title: string;
  widgetId: string;
  modes: SizeMode[];
}): string {
  const modeMap = Object.fromEntries(
    opts.modes
      .filter((m) => Object.keys(modeExtras(m)).length > 0)
      .map((m) => [m.name, modeExtras(m)]),
  );
  const modes =
    Object.keys(modeMap).length > 0
      ? `const MODES = ${JSON.stringify(modeMap, null, 2)};\n\n`
      : "";
  return `${modes}const meta = {
  title: ${JSON.stringify(opts.title)},
  component: WidgetScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  args: { widgetId: ${JSON.stringify(opts.widgetId)} },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    withhold: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
    mode: { control: false },
  },
} satisfies Meta<typeof WidgetScene>;

export default meta;
type Story = StoryObj<typeof meta>;
`;
}

function storyBlock(s: StoryEntry): string {
  const extras = modeExtras(s.mode);
  const args = [
    `fixture: ${s.fixtureVar}`,
    `w: ${s.mode.w}`,
    `h: ${s.mode.h}`,
    Object.keys(extras).length > 0
      ? `mode: MODES[${JSON.stringify(s.mode.name)}]`
      : undefined,
    s.profile ? `profile: ${JSON.stringify(s.profile)}` : undefined,
  ].filter(Boolean);
  return `
/** Sizes this scene renders at in the harness: ${s.modeNames.join(", ")}. */
export const ${s.exportName}: Story = {
  name: ${JSON.stringify(s.name)},
  args: { ${args.join(", ")} },
};
`;
}

async function writeWidgetFile(
  config: WidgetRenderConfig,
): Promise<{ file: string; stories: number }> {
  const label = config.label ?? config.widgetId;
  const file = resolve(OUT, "widgets", `${fileSlug(label)}.stories.tsx`);
  const dir = dirname(file);
  const scenes = await sceneFixtures(config);
  const taken = new Set<string>();
  const imports: string[] = [];
  const stories: StoryEntry[] = [];
  scenes.forEach((scene, i) => {
    const fixtureVar = `scene${i}`;
    imports.push(
      `import ${fixtureVar} from ${JSON.stringify(importPath(dir, scene.file))};`,
    );
    const modes = modesFor(config, scene.name);
    if (modes.length === 0) return;
    const profiles = fixtureProfiles(scene.data);
    const installs = profiles.length > 0 ? profiles : [undefined];
    for (const profile of installs) {
      const name = profile ? `${scene.name} @ ${profile}` : scene.name;
      stories.push({
        exportName: exportName(name, taken),
        name,
        fixtureVar,
        profile,
        mode: modes.find((m) => m.name.startsWith("default")) ?? modes[0],
        modeNames: modes.map((m) => m.name),
      });
    }
  });
  if (label === config.widgetId) {
    for (const extra of EXTRA_SCENES.filter(
      (e) => e.widgetId === config.widgetId,
    )) {
      const fixtureVar = `extra${stories.length}`;
      const file = resolve(REPO, extra.fixture);
      imports.push(
        `import ${fixtureVar} from ${JSON.stringify(importPath(dir, file))};`,
      );
      const name = basename(file, ".json");
      stories.push({
        exportName: exportName(name, taken),
        name,
        fixtureVar,
        mode: { name: "extra", w: extra.w, h: extra.h },
        modeNames: [`${extra.w}x${extra.h}, through its own probe`],
      });
    }
  }
  const title = `Widgets/${label}`;
  for (const s of stories)
    target("widget", config.widgetId, title, s.exportName);
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    `import { WidgetScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "WidgetScene")))};`,
    ...imports,
    "",
    metaBlock({
      title,
      widgetId: config.widgetId,
      modes: config.modes,
    }),
    ...stories.map(storyBlock),
  ].join("\n");
  await writeFile(file, body);
  return { file, stories: stories.length };
}

const UNFIXTURED_TITLE = "Widgets/(unfixtured)";

async function writeUnfixturedFile(): Promise<number> {
  const file = resolve(OUT, "widgets", "unfixtured.stories.tsx");
  const dir = dirname(file);
  const taken = new Set<string>();
  const stories = UNFIXTURED_WIDGETS.map((w) => {
    const name = exportName(w.widgetId, taken);
    target("widget", w.widgetId, UNFIXTURED_TITLE, name);
    return `
/** No fixture exists for this widget: it renders unfed. ${w.reason} */
export const ${name}: Story = {
  name: ${JSON.stringify(w.widgetId)},
  args: { widgetId: ${JSON.stringify(w.widgetId)}, fixture: {}, w: ${w.w}, h: ${w.h}${w.wrapped ? `, wrap: APP_WIDGET_WRAPS[${JSON.stringify(w.widgetId)}]` : ""} },
};
`;
  });
  const registers = [
    ...new Set(UNFIXTURED_WIDGETS.flatMap((w) => w.registers ?? [])),
  ].map((m) => `import ${JSON.stringify(importPath(dir, resolve(REPO, m)))};`);
  if (UNFIXTURED_WIDGETS.some((w) => w.wrapped)) {
    registers.push(
      `import { APP_WIDGET_WRAPS } from ${JSON.stringify(importPath(dir, resolve(SRC, "appWidgets")))};`,
    );
  }
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    `import { WidgetScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "WidgetScene")))};`,
    ...registers,
    "",
    `const meta = {
  title: ${JSON.stringify(UNFIXTURED_TITLE)},
  component: WidgetScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    wrap: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
  },
} satisfies Meta<typeof WidgetScene>;

export default meta;
type Story = StoryObj<typeof meta>;
`,
    ...stories,
  ].join("\n");
  await writeFile(file, body);
  return stories.length;
}

/** The first install profile a fixture declares, which its scene renders under. */
function firstInstall(fixture: string): string {
  const [first] = fixtureProfiles(readJsonObject(resolve(REPO, fixture)));
  if (!first) throw new Error(`${fixture} declares no install profile`);
  return first;
}

const EXTENSIONS_TITLE = "Extensions";

async function writeExtensionsFile(): Promise<number> {
  const file = resolve(OUT, "extensions", "extensions.stories.tsx");
  const dir = dirname(file);
  const taken = new Set<string>();
  const fixtures = new Map<string, string>();
  const imports: string[] = [];
  const fixtureVar = (path: string): string => {
    const known = fixtures.get(path);
    if (known) return known;
    const name = `scene${fixtures.size}`;
    fixtures.set(path, name);
    imports.push(
      `import ${name} from ${JSON.stringify(importPath(dir, resolve(REPO, path)))};`,
    );
    return name;
  };
  const stories = EXTENSION_SCENES.map((e) => {
    const name = exportName(e.id, taken);
    target("extension", e.id, EXTENSIONS_TITLE, name);
    return `
/** \`${e.id}\` switched on in \`${e.widgetId}\`. Untick \`enabled\` to see the host without it. */
export const ${name}: ExtensionStory = {
  name: ${JSON.stringify(e.id)},
  args: {
    widgetId: ${JSON.stringify(e.widgetId)},
    fixture: ${fixtureVar(e.fixture)},
    w: ${e.w},
    h: ${e.h},
    extension: ${JSON.stringify(e.id)},
    enabled: true,${e.config ? `\n    mode: { config: ${JSON.stringify(e.config)} },` : ""}${e.underInstall ? `\n    profile: ${JSON.stringify(firstInstall(e.fixture))},` : ""}
  },
};
`;
  });
  const body = [
    HEADER,
    `import type { Meta, StoryObj } from "@storybook/react-vite";`,
    `import { ExtensionScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "ExtensionScene")))};`,
    `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
    ...imports,
    "",
    `const meta = {
  title: ${JSON.stringify(EXTENSIONS_TITLE)},
  component: ExtensionScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  argTypes: {
    widgetId: { control: false },
    fixture: { control: false },
    extension: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
  },
} satisfies Meta<typeof ExtensionScene>;

export default meta;
type ExtensionStory = StoryObj<typeof meta>;
`,
    ...stories,
  ].join("\n");
  await writeFile(file, body);
  return stories.length;
}

/** A scene's target, read off its `_scene` block. */
function sceneTarget(raw: Record<string, unknown>): {
  kind: "widget" | "augment" | "contribution";
  id: string;
} {
  const block = raw._scene;
  if (typeof block !== "object" || block === null) {
    throw new Error("fixture has no _scene block");
  }
  for (const kind of ["widget", "augment", "contribution"] as const) {
    const id = (block as Record<string, unknown>)[kind];
    if (typeof id === "string") return { kind, id };
  }
  throw new Error("_scene names no widget, augment or contribution");
}

/** The Uplink clients under `mod/`, with the id each declares in its manifest. */
function uplinkClients(): { dir: string; id: string; name: string }[] {
  const mod = resolve(REPO, "mod");
  const out: { dir: string; id: string; name: string }[] = [];
  for (const entry of readdirSync(mod).sort()) {
    const dir = resolve(mod, entry, "client");
    const manifest = resolve(dir, "gonogo-uplink.json");
    if (!existsSync(manifest)) continue;
    const { id, name } = JSON.parse(readFileSync(manifest, "utf8"));
    out.push({ dir, id: String(id), name: String(name) });
  }
  return out;
}

/** One file per Uplink target, one story per scene, mounted through the Uplink render probe. */
async function writeUplinkFiles(
  covered: Set<string>,
  extensions: Set<string>,
): Promise<number> {
  let count = 0;
  for (const uplink of uplinkClients()) {
    const pkg = resolveUplinkPackage(uplink.dir);
    const byTarget = new Map<
      string,
      { file: string; raw: Record<string, unknown> }[]
    >();
    for (const file of pkg.fixtures) {
      const raw = readJsonObject(file);
      const target = sceneTarget(raw);
      const key = `${target.kind}:${target.id}`;
      byTarget.set(key, [...(byTarget.get(key) ?? []), { file, raw }]);
      if (target.kind === "widget") covered.add(target.id);
      else extensions.add(target.id);
    }
    for (const [key, scenes] of byTarget) {
      const targetId = key.slice(key.indexOf(":") + 1);
      const title = `Uplinks/${uplink.name}/${targetId}`;
      const kind = key.startsWith("widget:") ? "widget" : "extension";
      const out = resolve(
        OUT,
        "uplinks",
        `${uplink.id}--${fileSlug(targetId)}.stories.tsx`,
      );
      const dir = dirname(out);
      const taken = new Set<string>();
      const imports: string[] = [];
      const stories: string[] = [];
      scenes.forEach(({ file, raw }, i) => {
        imports.push(
          `import scene${i} from ${JSON.stringify(importPath(dir, file))};`,
        );
        const name = basename(file, ".json");
        const story = exportName(name, taken);
        target(kind, targetId, title, story);
        const display = relative(REPO, file);
        const block = raw._scene;
        const caption =
          typeof block === "object" && block !== null && "caption" in block
            ? block.caption
            : undefined;
        stories.push(`
/** ${typeof caption === "string" ? caption : name} */
export const ${story}: Story = {
  name: ${JSON.stringify(name)},
  args: { fixture: scene${i}, file: ${JSON.stringify(display)} },
};
`);
      });
      count += stories.length;
      const body = [
        HEADER,
        `import type { Meta, StoryObj } from "@storybook/react-vite";`,
        `import { withGonogoFrame } from ${JSON.stringify(importPath(dir, resolve(SRC, "frame")))};`,
        `import { UplinkScene } from ${JSON.stringify(importPath(dir, resolve(SRC, "UplinkScene")))};`,
        // After the scene module, which installs the host the client registers through.
        `import ${JSON.stringify(importPath(dir, pkg.entry))};`,
        ...imports,
        "",
        `const meta = {
  title: ${JSON.stringify(title)},
  component: UplinkScene,
  decorators: [withGonogoFrame],
  parameters: { layout: "fullscreen" },
  args: { uplinkId: ${JSON.stringify(uplink.id)} },
  argTypes: {
    uplinkId: { control: false },
    fixture: { control: false },
    file: { control: false },
    w: { control: { type: "range", min: 1, max: 36, step: 1 } },
    h: { control: { type: "range", min: 1, max: 40, step: 1 } },
  },
} satisfies Meta<typeof UplinkScene>;

export default meta;
type Story = StoryObj<typeof meta>;
`,
        ...stories,
      ].join("\n");
      await writeFile(out, body);
    }
  }
  return count;
}

async function main(): Promise<void> {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(resolve(OUT, "widgets"), { recursive: true });
  await mkdir(resolve(OUT, "extensions"), { recursive: true });
  await mkdir(resolve(OUT, "uplinks"), { recursive: true });
  await mkdir(resolve(OUT, "ui-kit"), { recursive: true });

  const configs = listWidgets();
  let widgetStories = 0;
  const covered = new Set<string>();
  for (const config of configs) {
    const { stories } = await writeWidgetFile(config);
    widgetStories += stories;
    if (stories > 0) covered.add(config.widgetId);
  }
  const unfixtured = await writeUnfixturedFile();
  for (const w of UNFIXTURED_WIDGETS) covered.add(w.widgetId);
  const extensions = await writeExtensionsFile();
  const extensionIds = new Set(EXTENSION_SCENES.map((e) => e.id));
  const uplinkStories = await writeUplinkFiles(covered, extensionIds);

  const uiKit = await writeUiKitStories({
    repo: REPO,
    out: resolve(OUT, "ui-kit"),
    src: SRC,
    presets: Object.keys(UI_KIT_PRESETS),
    header: HEADER,
  });
  await writeFile(
    resolve(OUT, "ui-kit-coverage.json"),
    `${JSON.stringify(uiKit, null, 2)}\n`,
  );
  for (const [name, ids] of Object.entries(uiKit.stories)) {
    TARGETS.primitive[name] = ids;
  }
  for (const { name } of uiKit.uncovered) TARGETS.primitive[name] = [];

  const clients = uplinkClients().map((u) => resolveUplinkPackage(u.dir).entry);
  const registerModules = [
    // The render probe's planted Uplink, whose contributions the extension stories show.
    "packages/components/scripts/probe/plantedUplink.ts",
    ...new Set(UNFIXTURED_WIDGETS.flatMap((w) => w.registers ?? [])),
  ].map((m) => resolve(REPO, m));
  await writeFile(
    resolve(OUT, "registrations.ts"),
    [
      HEADER,
      "// Every module that registers a widget or extension the stories cover.",
      `import ${JSON.stringify(importPath(OUT, resolve(SRC, "setup")))};`,
      ...[...registerModules, ...clients].map(
        (m) => `import ${JSON.stringify(importPath(OUT, m))};`,
      ),
      "",
    ].join("\n"),
  );
  await writeFile(
    resolve(OUT, "coverage.json"),
    `${JSON.stringify({ widgets: [...covered].sort(), extensions: [...extensionIds].sort() }, null, 2)}\n`,
  );
  await writeFile(
    resolve(OUT, "review-targets.json"),
    `${JSON.stringify(TARGETS, null, 2)}\n`,
  );
  console.log(
    `generate-stories: ${configs.length} render configs -> ${widgetStories} widget stories, ${unfixtured} unfixtured, ${extensions} extension stories, ${uplinkStories} Uplink scene stories; ${covered.size} widgets covered`,
  );
  console.log(
    `generate-stories: ui-kit ${uiKit.defaults.length} defaults, ${uiKit.presets.length} preset sets, ${uiKit.handwritten.length} hand-written, ${uiKit.uncovered.length} uncovered`,
  );
}

await main();
