// tech-tree.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["career.mode", "spaceCenter.scene", "spaceCenter.state"],
  optionalChannelFamilies: [],
  commands: ["career.tech.unlock"],
} as const;
