// Compat shim — the icon set now lives in `@ksp-gonogo/ui-kit` so
// export-safe third-party Uplink clients can use it without depending on
// this package. Re-exported here unchanged so in-tree consumers of
// `@ksp-gonogo/ui` keep compiling. A later migration phase removes this file.
export {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BellIcon,
  BroadcastIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  DatabaseIcon,
  DiagnosticsIcon,
  FullHeightIcon,
  FullscreenEnterIcon,
  FullscreenExitIcon,
  FullWidthIcon,
  GearIcon,
  HalfHeightIcon,
  HalfWidthIcon,
  HistoryIcon,
  type IconProps,
  JoystickIcon,
  LayersIcon,
  PauseIcon,
  PencilIcon,
  PlayIcon,
  PlusIcon,
  PushUpIcon,
  RecallIcon,
  SatelliteIcon,
  SettingsIcon,
  StarIcon,
  StopIcon,
} from "@ksp-gonogo/ui-kit";
