// orbital-ascent.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["vessel.orbit", "vessel.propulsion"],
  optionalChannelFamilies: [],
  commands: [],
} as const;
