//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// THIS IS NOT A LIST OF EVERY COMMAND ON THE WIRE, for the same reason the
// topic map is not one: a command in a DYNAMIC namespace is addressed per
// subject at runtime and has no tagged type to find. What is below is every
// command that can be named before the game is running.

import type {
  PrincipiaBurnEditArgs,
  PrincipiaBurnRemoveArgs,
  PrincipiaPlanArmArgs,
  PrincipiaPlanHorizonArgs,
  PrincipiaPlanIntegratorArgs,
  PrincipiaPlanSendArgs,
  PrincipiaPlanSlotArgs,
} from "./contract.js";
import type {
  CommandResultOf,
} from "@ksp-gonogo/sitrep-sdk";

export interface GeneratedCommandArgsMap {
  "principia.plan.arm": PrincipiaPlanArmArgs;
  "principia.plan.burn.insert": PrincipiaBurnEditArgs;
  "principia.plan.burn.remove": PrincipiaBurnRemoveArgs;
  "principia.plan.burn.replace": PrincipiaBurnEditArgs;
  "principia.plan.create": PrincipiaPlanSlotArgs;
  "principia.plan.delete": PrincipiaPlanSlotArgs;
  "principia.plan.duplicate": PrincipiaPlanSlotArgs;
  "principia.plan.horizon": PrincipiaPlanHorizonArgs;
  "principia.plan.integrator": PrincipiaPlanIntegratorArgs;
  "principia.plan.send": PrincipiaPlanSendArgs;
}

export interface GeneratedCommandReplyMap {
  "principia.plan.arm": CommandResultOf<Record<string, unknown>>;
  "principia.plan.burn.insert": CommandResultOf<Record<string, unknown>>;
  "principia.plan.burn.remove": CommandResultOf<Record<string, unknown>>;
  "principia.plan.burn.replace": CommandResultOf<Record<string, unknown>>;
  "principia.plan.create": CommandResultOf<Record<string, unknown>>;
  "principia.plan.delete": CommandResultOf<Record<string, unknown>>;
  "principia.plan.duplicate": CommandResultOf<Record<string, unknown>>;
  "principia.plan.horizon": CommandResultOf<Record<string, unknown>>;
  "principia.plan.integrator": CommandResultOf<Record<string, unknown>>;
  "principia.plan.send": CommandResultOf<Record<string, unknown>>;
}

export const GENERATED_COMMAND_IDS = [
  "principia.plan.arm",
  "principia.plan.burn.insert",
  "principia.plan.burn.remove",
  "principia.plan.burn.replace",
  "principia.plan.create",
  "principia.plan.delete",
  "principia.plan.duplicate",
  "principia.plan.horizon",
  "principia.plan.integrator",
  "principia.plan.send",
] as const;
