//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface PrincipiaFlightPlan
{
	vesselId?: string;
	observedAtUt?: Value<"ut">;
	planExists?: boolean;
	finalTimeUt?: Value<"ut">;
	reachedDeadline?: boolean;
	planIntegrated?: boolean;
	statusError?: number;
	statusMessage?: string;
	firstErrorBurnIndex?: Value<"count">;
	firstFutureBurnIndex?: Value<"count">;
	anomalousBurnCount?: Value<"count">;
	burns?: PrincipiaFlightPlanBurn[];
}
export interface PrincipiaFlightPlanBurn
{
	index?: Value<"count">;
	ignitionUt?: Value<"ut">;
	cutoffUt?: Value<"ut">;
	durationSeconds?: Value<"s">;
	deltaV?: Value<"m/s">;
	thrustKilonewtons?: Value<"kN">;
	specificImpulseSeconds?: Value<"s">;
	initialMassTons?: Value<"t">;
	inertiallyFixed?: boolean;
	coordinateSystem?: number;
	anomalous?: boolean;
}
export interface PrincipiaReferenceFrame
{
	selector?: string;
	type?: number;
	centreBody?: string;
	primaryBody?: string;
	secondaryBody?: string;
	primaryBodies?: string[];
	secondaryBodies?: string[];
	targetFrameSelected?: boolean;
	targetVesselId?: string;
	targetVesselName?: string;
}
export interface PrincipiaSettings
{
	observedAtUt?: Value<"ut">;
	pluginVersion?: string;
	readingSuspended?: boolean;
	readingSuspendedReason?: string;
	plottingFrame?: PrincipiaReferenceFrame;
	burnFrames?: PrincipiaReferenceFrame[];
	selectingTargetVessel?: boolean;
	targetVesselId?: string;
	targetVesselName?: string;
	selectingTargetCelestial?: boolean;
	targetCelestialBody?: string;
	displayPatchedConics?: boolean;
	analysisMissionDurationRequestedSeconds?: Value<"s">;
	recurrenceAutodetect?: boolean;
	recurrenceRevolutionsPerCycle?: Value<"count">;
	recurrenceDaysPerCycle?: Value<"count">;
	groundTrackRevolution?: Value<"count">;
	predictionVesselId?: string;
	predictionToleranceMetres?: Value<"m">;
	predictionMaxSteps?: Value<"count">;
	planToleranceMetres?: Value<"m">;
	planMaxSteps?: Value<"count">;
	planInitialTimeUt?: Value<"ut">;
	planDesiredFinalTimeUt?: Value<"ut">;
	planActualFinalTimeUt?: Value<"ut">;
	flightPlanCount?: Value<"count">;
	selectedFlightPlan?: Value<"count">;
	optimiserTargetAltitudeMetres?: Value<"m">;
	optimiserTargetInclinationDegrees?: Value<"°">;
	historyLengthSeconds?: Value<"s">;
	unpinnedMarkersHiddenHere?: boolean;
	framesHidingUnpinnedMarkers?: Value<"count">;
	unpinnedCelestialsHiddenHere?: boolean;
	framesHidingUnpinnedCelestials?: Value<"count">;
	pinnedCelestials?: string[];
	targetPinned?: boolean;
	showManoeuvreOnNavball?: boolean;
	stabilityGridMaxEccentricityMinInclination?: boolean;
	stabilityGridMinEccentricityMaxInclination?: boolean;
	showElementGraphs?: boolean;
	verboseLevel?: Value<"count">;
	logThreshold?: Value<"count">;
	stderrThreshold?: Value<"count">;
	flushThreshold?: Value<"count">;
	recordJournalRequested?: boolean;
	journaling?: boolean;
}
export interface PrincipiaPlan
{
	vesselId?: string;
	sampledAtUt?: Value<"ut">;
	planExists?: boolean;
	writeSurface?: PrincipiaWriteSurface;
	planCount?: Value<"count">;
	selectedPlan?: Value<"count">;
	initialTimeUt?: Value<"ut">;
	desiredFinalTimeUt?: Value<"ut">;
	actualFinalTimeUt?: Value<"ut">;
	anomalousBurnCount?: Value<"count">;
	optimisationRunning?: boolean;
	integrator?: PrincipiaPlanIntegrator;
	burns?: PrincipiaPlannedBurn[];
}
export interface PrincipiaWriteSurface
{
	available?: boolean;
	armed?: boolean;
	reason?: string;
	analysedVersion?: string;
	detectedVersion?: string;
}
export interface PrincipiaPlanIntegrator
{
	maxSteps?: Value<"count">;
	lengthToleranceMetres?: Value<"m">;
	speedToleranceMetresPerSecond?: Value<"m/s">;
	integratorKind?: number;
	generalizedIntegratorKind?: number;
}
export interface PrincipiaPlannedBurn
{
	index?: Value<"count">;
	ignitionUt?: Value<"ut">;
	cutoffUt?: Value<"ut">;
	durationSeconds?: Value<"s">;
	timeToHalfDeltaVSeconds?: Value<"s">;
	deltaV?: Value<"m/s">;
	deltaVTangent?: Value<"m/s">;
	deltaVNormal?: Value<"m/s">;
	deltaVBinormal?: Value<"m/s">;
	coordinateSystem?: number;
	inertiallyFixed?: boolean;
	thrustKilonewtons?: Value<"kN">;
	specificImpulseSeconds?: Value<"s">;
	initialMassTons?: Value<"t">;
	finalMassTons?: Value<"t">;
	massFlowKilogramsPerSecond?: Value<"kg/s">;
	frameType?: number;
	frameEditable?: boolean;
	executing?: boolean;
	anomalous?: boolean;
}
export enum PrincipiaWriteOutcome {
	Refused = 0,
	Rejected = 1,
	Written = 2
}
export enum PrincipiaWriteRefusal {
	SurfaceUnavailable = 0,
	NotRefused = 1,
	NotArmed = 2,
	LayoutUnverified = 3,
	VesselUnknown = 4,
	NoFlightPlan = 5,
	PlanAlreadyExists = 6,
	PlanSlotsFull = 7,
	BurnIndexOutOfRange = 8,
	BurnExecuting = 9,
	BurnFrameUnsupported = 10,
	OptimisationRunning = 11,
	ValueNotFinite = 12,
	ThrustNotPositive = 13,
	IntegratorKindUnexpected = 14,
	IntegratorBoundsExceeded = 15,
	FinalTimeInPast = 16,
	PluginShapeChanged = 18,
	IgnitionInPast = 19,
	PlanMalformed = 20,
	ComposedBurnIncomplete = 21
}
export interface PrincipiaPlanWriteReceipt
{
	requestId?: string;
	replayed?: boolean;
	outcome: PrincipiaWriteOutcome;
	refusal: PrincipiaWriteRefusal;
	refusalDetail?: string;
	statusError?: number;
	statusMessage?: string;
	plan?: PrincipiaPlan;
}
export interface PrincipiaPlanArmArgs
{
	vesselId?: string;
	requestId?: string;
}
export enum PrincipiaBurnProfile {
	Unchanged = 0,
	InstantImpulse = 1
}
export interface PrincipiaBurnEditArgs
{
	vesselId?: string;
	requestId?: string;
	burnIndex: number;
	ignitionUt?: number;
	deltaVTangent?: number;
	deltaVNormal?: number;
	deltaVBinormal?: number;
	inertiallyFixed?: boolean;
	profile: PrincipiaBurnProfile;
	massTons?: number;
}
export interface PrincipiaComposedBurn
{
	ignitionUt: Value<"ut">;
	deltaVTangent: Value<"m/s">;
	deltaVNormal: Value<"m/s">;
	deltaVBinormal: Value<"m/s">;
	inertiallyFixed: boolean;
	profile: PrincipiaBurnProfile;
}
export interface PrincipiaPlanSendArgs
{
	vesselId?: string;
	requestId?: string;
	composedAtViewUt?: number;
	observedAtUt?: number;
	burns?: PrincipiaComposedBurn[];
	desiredFinalTimeUt?: number;
	massTons?: number;
}
export interface PrincipiaBurnRemoveArgs
{
	vesselId?: string;
	requestId?: string;
	burnIndex: number;
}
export interface PrincipiaPlanHorizonArgs
{
	vesselId?: string;
	requestId?: string;
	desiredFinalTimeUt: number;
}
export interface PrincipiaPlanIntegratorArgs
{
	vesselId?: string;
	requestId?: string;
	maxSteps?: number;
	lengthToleranceMetres?: number;
	speedToleranceMetresPerSecond?: number;
}
export interface PrincipiaPlanSlotArgs
{
	vesselId?: string;
	requestId?: string;
	finalTimeUt?: number;
	massTons?: number;
}
