//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface PrincipiaFlightPlan
{
	vesselId?: string;
	observedAtUt?: Value<"ut">;
	planExists?: boolean;
	finalTimeUt?: Value<"ut">;
	reachedDeadline?: boolean;
	planIntegrated?: boolean;
	statusError?: number;
	statusMessage?: string;
	firstErrorBurnIndex?: Value<"count">;
	firstFutureBurnIndex?: Value<"count">;
	anomalousBurnCount?: Value<"count">;
	burns?: PrincipiaFlightPlanBurn[];
}
export interface PrincipiaFlightPlanBurn
{
	index?: Value<"count">;
	ignitionUt?: Value<"ut">;
	cutoffUt?: Value<"ut">;
	durationSeconds?: Value<"s">;
	deltaV?: Value<"m/s">;
	thrustKilonewtons?: Value<"kN">;
	specificImpulseSeconds?: Value<"s">;
	initialMassTons?: Value<"t">;
	inertiallyFixed?: boolean;
	coordinateSystem?: number;
	anomalous?: boolean;
}
