//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface PrincipiaFlightPlan
{
	vesselId?: string;
	observedAtUt?: Value<"ut">;
	planExists?: boolean;
	finalTimeUt?: Value<"ut">;
	reachedDeadline?: boolean;
	planIntegrated?: boolean;
	statusError?: number;
	statusMessage?: string;
	firstErrorBurnIndex?: Value<"count">;
	firstFutureBurnIndex?: Value<"count">;
	anomalousBurnCount?: Value<"count">;
	burns?: PrincipiaFlightPlanBurn[];
}
export interface PrincipiaFlightPlanBurn
{
	index?: Value<"count">;
	ignitionUt?: Value<"ut">;
	cutoffUt?: Value<"ut">;
	durationSeconds?: Value<"s">;
	deltaV?: Value<"m/s">;
	thrustKilonewtons?: Value<"kN">;
	specificImpulseSeconds?: Value<"s">;
	initialMassTons?: Value<"t">;
	inertiallyFixed?: boolean;
	coordinateSystem?: number;
	anomalous?: boolean;
}
export interface PrincipiaReferenceFrame
{
	selector?: string;
	type?: number;
	centreBody?: string;
	primaryBody?: string;
	secondaryBody?: string;
	targetFrameSelected?: boolean;
	targetVesselId?: string;
	targetVesselName?: string;
}
export interface PrincipiaSettings
{
	observedAtUt?: Value<"ut">;
	pluginVersion?: string;
	readingSuspended?: boolean;
	readingSuspendedReason?: string;
	plottingFrame?: PrincipiaReferenceFrame;
	burnFrames?: PrincipiaReferenceFrame[];
	selectingTargetVessel?: boolean;
	targetVesselId?: string;
	targetVesselName?: string;
	selectingTargetCelestial?: boolean;
	targetCelestialBody?: string;
	displayPatchedConics?: boolean;
	analysisMissionDurationRequestedSeconds?: Value<"s">;
	recurrenceAutodetect?: boolean;
	recurrenceRevolutionsPerCycle?: Value<"count">;
	recurrenceDaysPerCycle?: Value<"count">;
	groundTrackRevolution?: Value<"count">;
	predictionVesselId?: string;
	predictionToleranceMetres?: Value<"m">;
	predictionMaxSteps?: Value<"count">;
	planToleranceMetres?: Value<"m">;
	planMaxSteps?: Value<"count">;
	planInitialTimeUt?: Value<"ut">;
	planDesiredFinalTimeUt?: Value<"ut">;
	planActualFinalTimeUt?: Value<"ut">;
	flightPlanCount?: Value<"count">;
	selectedFlightPlan?: Value<"count">;
	optimiserTargetAltitudeMetres?: Value<"m">;
	optimiserTargetInclinationDegrees?: Value<"°">;
	historyLengthSeconds?: Value<"s">;
	unpinnedMarkersHiddenHere?: boolean;
	framesHidingUnpinnedMarkers?: Value<"count">;
	unpinnedCelestialsHiddenHere?: boolean;
	framesHidingUnpinnedCelestials?: Value<"count">;
	pinnedCelestials?: string[];
	targetPinned?: boolean;
	showManoeuvreOnNavball?: boolean;
	stabilityGridMaxEccentricityMinInclination?: boolean;
	stabilityGridMinEccentricityMaxInclination?: boolean;
	showElementGraphs?: boolean;
	verboseLevel?: Value<"count">;
	logThreshold?: Value<"count">;
	stderrThreshold?: Value<"count">;
	flushThreshold?: Value<"count">;
	recordJournalRequested?: boolean;
	journaling?: boolean;
}
