import { dirname, join } from "node:path";
import type { WidgetScan } from "./types";

export interface Declarations {
  optionalChannels: string[];
  optionalChannelFamilies: string[];
  commands: string[];
}

const unique = (values: Iterable<string>) => [...new Set(values)].sort();

/** What the generated file declares for a widget: everything it reads beyond the required lists. */
export function declarationsOf(widget: WidgetScan): Declarations {
  const required = new Set(widget.registration.channels ?? []);
  const requiredFamilies = new Set(widget.registration.channelFamilies ?? []);
  return {
    optionalChannels: unique(
      widget.reads.flatMap((r) =>
        r.id !== undefined && !required.has(r.id) ? [r.id] : [],
      ),
    ),
    optionalChannelFamilies: unique(
      widget.reads.flatMap((r) =>
        r.family !== undefined && !requiredFamilies.has(r.family)
          ? [r.family]
          : [],
      ),
    ),
    commands: unique(widget.commands.flatMap((r) => (r.id ? [r.id] : []))),
  };
}

export const isEmpty = (d: Declarations) =>
  d.optionalChannels.length === 0 &&
  d.optionalChannelFamilies.length === 0 &&
  d.commands.length === 0;

/** Where a widget's generated declarations live: beside its registration, named by its id. */
export const declarationsPath = (widget: WidgetScan) =>
  join(
    dirname(widget.registration.file),
    `${widget.registration.id}.declarations.g.ts`,
  );

export function emitDeclarations(widget: WidgetScan): string {
  const d = declarationsOf(widget);
  const list = (name: string, values: string[]) =>
    `export const ${name} = [${values.map((v) => JSON.stringify(v)).join(", ")}] as const;\n`;
  return (
    `// ${widget.registration.id}.declarations.g.ts (generated by uplink-tools check --fix, do not edit)\n` +
    list("optionalChannels", d.optionalChannels) +
    list("optionalChannelFamilies", d.optionalChannelFamilies) +
    list("commands", d.commands)
  );
}
