import { dirname, join } from "node:path";
import type { WidgetScan } from "./types";

export interface Declarations {
  optionalChannels: string[];
  optionalChannelFamilies: string[];
  commands: string[];
}

/** A family with its placeholder names dropped, so `fleet.<vessel>.contact` and `fleet.<id>.contact` are one family. */
export const normalizeFamily = (pattern: string) =>
  pattern.replace(/<[^>]*>/g, "<>");

const unique = (values: Iterable<string>) => [...new Set(values)].sort();

/** One pattern per family, whatever its placeholders are called. */
const uniqueFamilies = (patterns: string[]) =>
  [...new Map(patterns.map((p) => [normalizeFamily(p), p])).values()].sort();

/** What the generated file declares for a widget: everything it reads beyond the required lists. */
export function declarationsOf(widget: WidgetScan): Declarations {
  const required = new Set(widget.registration.channels ?? []);
  const requiredFamilies = new Set(
    (widget.registration.channelFamilies ?? []).map(normalizeFamily),
  );
  return {
    optionalChannels: unique(
      widget.reads.flatMap((r) =>
        r.id !== undefined && !required.has(r.id) ? [r.id] : [],
      ),
    ),
    optionalChannelFamilies: uniqueFamilies(
      widget.reads.flatMap((r) =>
        r.family !== undefined &&
        !requiredFamilies.has(normalizeFamily(r.family))
          ? [r.family]
          : [],
      ),
    ),
    commands: unique(widget.commands.flatMap((r) => (r.id ? [r.id] : []))),
  };
}

export const isEmpty = (d: Declarations) =>
  d.optionalChannels.length === 0 &&
  d.optionalChannelFamilies.length === 0 &&
  d.commands.length === 0;

/** Where a widget's generated declarations live: beside its registration, named by its id. */
export const declarationsPath = (widget: WidgetScan) =>
  join(
    dirname(widget.registration.file),
    `${widget.registration.id}.declarations.g.ts`,
  );

/** The width a formatter breaks a line at when nothing configures it. */
const LINE_WIDTH = 80;

/** One property in the layout biome and prettier leave alone: on one line while it fits, otherwise one item per line with a trailing comma. */
function arrayProperty(name: string, values: string[]): string {
  const items = values.map((v) => JSON.stringify(v));
  const line = `  ${name}: [${items.join(", ")}],`;
  if (line.length <= LINE_WIDTH) return `${line}\n`;
  return `  ${name}: [\n${items.map((i) => `    ${i},\n`).join("")}  ],\n`;
}

/**
 * The file is one default export, so a widget spreads it (`...declarations`)
 * and a private package's exported names never gain `optionalChannels` or
 * `commands`, which the published docs also use for their own fields.
 */
export function emitDeclarations(widget: WidgetScan): string {
  const d = declarationsOf(widget);
  return (
    `// ${widget.registration.id}.declarations.g.ts (generated by uplink-tools check --fix, do not edit)\n` +
    "export default {\n" +
    arrayProperty("optionalChannels", d.optionalChannels) +
    arrayProperty("optionalChannelFamilies", d.optionalChannelFamilies) +
    arrayProperty("commands", d.commands) +
    "} as const;\n"
  );
}
