// power-systems.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["parts.power", "vessel.resources"],
  optionalChannelFamilies: [],
  commands: [],
} as const;
