using System.Collections.Generic;
using System.Linq;

namespace Sitrep.Core
{
    /// <summary>
    /// C# port of <c>mod/sitrep-kernel/src/broker.ts</c>: orders capability
    /// activation so that a provider's declared <see cref="DependencyNode.Deps"/>
    /// are already active by the time its factory runs (i.e.
    /// <c>ctx.Query(dep)</c> inside the factory resolves successfully).
    ///
    /// Selection-agnostic, same as the TS reference: it consumes the
    /// *already selected* provider(s) per capability — see
    /// <see cref="Kernel.Resolve"/>, which runs selection first, builds one
    /// <see cref="DependencyNode"/> per capability from the winning
    /// provider(s)' deps, topo-sorts here, and only then invokes factories in
    /// that order.
    ///
    /// Semantics MUST stay byte-for-byte identical to the TS reference —
    /// conformance is asserted indirectly via the kernel golden fixture
    /// (<c>mod/golden-fixtures/kernel.json</c>, generated by
    /// <c>mod/golden-fixtures/gen/kernel.gen.ts</c>), not re-derived here.
    /// </summary>
    public sealed class DependencyNode
    {
        /// <summary>The capability id this node represents.</summary>
        public string Id { get; }

        /// <summary>Capabilities this node's selected provider(s) must see active first.</summary>
        public IReadOnlyList<string> Deps { get; }

        public DependencyNode(string id, IReadOnlyList<string> deps)
        {
            Id = id;
            Deps = deps;
        }
    }

    public static class Broker
    {
        /// <summary>
        /// Kahn's algorithm topo-sort over the capability dependency graph.
        ///
        /// - A dep naming a capability that isn't in <paramref name="nodes"/>
        ///   is not an edge (it isn't a graph node) — it doesn't block
        ///   activation. Whatever depends on it will simply get a
        ///   "not exactly one active provider" error from <c>ctx.Query</c> at
        ///   factory time if it actually calls query for that id; the broker
        ///   doesn't pre-empt that.
        /// - Deterministic: ties are broken by <paramref name="nodes"/> order
        ///   (registration order), never by hash-set/dictionary iteration of
        ///   intermediate structures — the initial ready queue is seeded in
        ///   <paramref name="nodes"/> order, and nodes that become ready later
        ///   are appended to that same FIFO queue in the order their
        ///   dependencies clear.
        /// - Throws <see cref="DependencyCycleError"/> (naming the cycle) if
        ///   a cycle prevents a full ordering.
        /// </summary>
        public static List<string> TopoSortActivationOrder(IReadOnlyList<DependencyNode> nodes)
        {
            var knownIds = new HashSet<string>(nodes.Select(n => n.Id));
            var dependents = new Dictionary<string, List<string>>();
            var inDegree = new Dictionary<string, int>();

            foreach (var node in nodes)
            {
                inDegree[node.Id] = 0;
                dependents[node.Id] = new List<string>();
            }

            foreach (var node in nodes)
            {
                foreach (var dep in node.Deps)
                {
                    if (!knownIds.Contains(dep))
                    {
                        // Dep on a capability that isn't part of this graph
                        // (never registered) — not an edge; not this
                        // broker's problem.
                        continue;
                    }
                    dependents[dep].Add(node.Id);
                    inDegree[node.Id] = inDegree[node.Id] + 1;
                }
            }

            var queue = new List<string>();
            foreach (var node in nodes)
            {
                if (inDegree[node.Id] == 0)
                {
                    queue.Add(node.Id);
                }
            }

            var order = new List<string>();
            var head = 0;
            while (head < queue.Count)
            {
                var current = queue[head];
                head += 1;
                order.Add(current);

                foreach (var dependent in dependents[current])
                {
                    var remaining = inDegree[dependent] - 1;
                    inDegree[dependent] = remaining;
                    if (remaining == 0)
                    {
                        queue.Add(dependent);
                    }
                }
            }

            if (order.Count != nodes.Count)
            {
                var orderedSet = new HashSet<string>(order);
                var remainingIds = nodes
                    .Select(n => n.Id)
                    .Where(id => !orderedSet.Contains(id))
                    .ToList();
                throw new DependencyCycleError(FindCycle(remainingIds, nodes, knownIds));
            }

            return order;
        }

        /// <summary>
        /// DFS cycle finder, scoped to the nodes that Kahn's algorithm
        /// couldn't order (i.e. everything left over is part of, or feeds
        /// into, at least one cycle). Walks each node's deps edges directly
        /// (the "depends on" direction) using a visiting/visited marker, so
        /// the returned path is an actual dependency chain that loops back on
        /// itself — useful in the thrown error message.
        /// </summary>
        private static List<string> FindCycle(
            List<string> remainingIds,
            IReadOnlyList<DependencyNode> nodes,
            HashSet<string> knownIds)
        {
            var depsById = nodes.ToDictionary(n => n.Id, n => n.Deps);
            var remainingSet = new HashSet<string>(remainingIds);
            var visiting = new HashSet<string>();
            var visited = new HashSet<string>();
            var stack = new List<string>();

            List<string>? Dfs(string id)
            {
                visiting.Add(id);
                stack.Add(id);

                foreach (var dep in depsById[id])
                {
                    if (!knownIds.Contains(dep) || !remainingSet.Contains(dep))
                    {
                        continue;
                    }
                    if (visiting.Contains(dep))
                    {
                        var startIndex = stack.IndexOf(dep);
                        var cycle = stack.Skip(startIndex).ToList();
                        cycle.Add(dep);
                        return cycle;
                    }
                    if (!visited.Contains(dep))
                    {
                        var found = Dfs(dep);
                        if (found != null)
                        {
                            return found;
                        }
                    }
                }

                visiting.Remove(id);
                visited.Add(id);
                stack.RemoveAt(stack.Count - 1);
                return null;
            }

            foreach (var id in remainingIds)
            {
                if (visited.Contains(id))
                {
                    continue;
                }
                var found = Dfs(id);
                if (found != null)
                {
                    return found;
                }
            }

            // Should be unreachable (Kahn's algorithm only leaves nodes that
            // are part of some cycle) — fall back to naming everything left
            // over.
            return remainingIds;
        }
    }
}
