// strategies.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [],
  optionalChannelFamilies: [],
  commands: ["career.strategy.activate", "career.strategy.deactivate"],
} as const;
