// resource-ops.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["system.bodies", "vessel.identity"],
  optionalChannelFamilies: [],
  commands: [],
} as const;
