// twr.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["vessel.flight", "vessel.orbit"],
  optionalChannelFamilies: [],
  commands: [],
} as const;
