//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// WHAT THE COUNT COUNTS, because a grep gets it wrong. It is one entry per
// [SitrepCommand] ATTRIBUTE, not per tagged type: SetEnabledArgs alone carries
// six. Counting `AddCommandHandler` call sites instead misses the ones the
// engine registers directly; counting `const string \w*Command\w*` catches
// CommandCentreTopic, which is a Topic; counting the strings the bundled
// clients dispatch counts what a widget presses today rather than what the
// mod accepts, and gets a quarter of the answer. Read this file.
//
// THIS IS NOT A LIST OF EVERY COMMAND ON THE WIRE, for the same reason the
// topic map is not one: a command in a DYNAMIC namespace is addressed per
// subject at runtime and has no tagged type to find. What is below is every
// command that can be named before the game is running. How many that
// excludes is not knowable from here and is not a fixed number: a dynamic
// command materialises per subject, so the count is per CPU, per vessel, per
// compute topic, and it is zero in a session that has none. Grep the mod for
// `RegisterDynamicNamespace` to enumerate the namespaces themselves.

import type {
  KerbalismSubjectActionArgs,
  KerbalismSubjectFlagArgs,
} from "./contract.js";
import type {
  CommandResult,
} from "@ksp-gonogo/sitrep-sdk";

export interface GeneratedCommandArgsMap {
  "kerbalism.file.delete": KerbalismSubjectActionArgs;
  "kerbalism.file.send": KerbalismSubjectFlagArgs;
  "kerbalism.sample.analyze": KerbalismSubjectFlagArgs;
  "kerbalism.sample.dump": KerbalismSubjectActionArgs;
  "kerbalism.sample.moveToLab": KerbalismSubjectActionArgs;
}

export interface GeneratedCommandReplyMap {
  "kerbalism.file.delete": CommandResult;
  "kerbalism.file.send": CommandResult;
  "kerbalism.sample.analyze": CommandResult;
  "kerbalism.sample.dump": CommandResult;
  "kerbalism.sample.moveToLab": CommandResult;
}

export const GENERATED_COMMAND_IDS = [
  "kerbalism.file.delete",
  "kerbalism.file.send",
  "kerbalism.sample.analyze",
  "kerbalism.sample.dump",
  "kerbalism.sample.moveToLab",
] as const;
