//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface KerbalismSubjectFlagArgs
{
	subjectId: string;
	flag: boolean;
}
export interface KerbalismSubjectActionArgs
{
	subjectId: string;
}
export interface KerbalismIsruDrillExtension
{
	issue?: string;
	harvestType?: string;
	ecRate?: Value<"units/s">;
	sourceMassRemaining?: Value<"t">;
	sourceMassThreshold?: Value<"t">;
}
export interface KerbalismIsruConverterExtension
{
	processToken?: string;
	title?: string;
	capacity?: Value<"units">;
	broken?: boolean;
	valveIndex?: Value<"count">;
}
export interface KerbalismSpaceWeather
{
	radiationRadPerSecond?: Value<"rad/s">;
	habitatRadiationRadPerSecond?: Value<"rad/s">;
	magnetosphere?: boolean;
	innerBelt?: boolean;
	outerBelt?: boolean;
	stormIncoming?: boolean;
	stormInProgress?: boolean;
	blackout?: boolean;
	inSunlight?: boolean;
	shieldingAmount?: Value<"units">;
	shieldingCapacity?: Value<"units">;
	stars?: KerbalismStarInfo[];
	storms?: KerbalismStormEntry[];
	stormEjectionSpeed?: Value<"m/s">;
}
export interface KerbalismStarInfo
{
	star?: string;
	direction?: Vec3Of<"1">;
	distance?: Value<"m">;
}
export enum KerbalismStormTargetKind {
	Body = 0,
	Vessel = 1
}
export interface KerbalismStormEntry
{
	star?: string;
	targetKind?: KerbalismStormTargetKind;
	targetName?: string;
	stormState?: Value<"count">;
	stormTime?: Value<"ut">;
	stormDuration?: Value<"s">;
	dist?: Value<"m">;
}
export interface KerbalismResource
{
	amount?: Value<"units">;
	capacity?: Value<"units">;
	rate?: Value<"units/s">;
}
export interface KerbalismHabitat
{
	pressure?: Value<"ratio">;
	poisoning?: Value<"ratio">;
	shielding?: Value<"ratio">;
	livingSpace?: Value<"ratio">;
	comfort?: Value<"ratio">;
	volume?: Value<"m³">;
	surface?: Value<"m²">;
}
export interface KerbalismProcessEntry
{
	resource?: string;
	title?: string;
	capacity?: Value<"units">;
	running?: boolean;
	broken?: boolean;
	flightId?: number;
	valveIndex?: Value<"count">;
	envModifier?: Value<"1">;
}
export interface KerbalismResourceDef
{
	flowMode?: string;
	flowModeOrdinal?: number;
	displayName?: string;
	density?: Value<"kg/m³">;
	isSupply?: boolean;
	lowThreshold?: Value<"ratio">;
}
export interface KerbalismRuleDef
{
	name?: string;
	input?: string;
	output?: string;
	ratePerSecond?: Value<"units/s">;
	rate?: Value<"units">;
	interval?: Value<"s">;
	degeneration?: Value<"units/s">;
	fatalThreshold?: Value<"units">;
	breakdown?: boolean;
	modifiers?: string[];
}
export interface KerbalismProcessDef
{
	name?: string;
	inputs?: { [key: string]: Value<"units/s"> };
	outputs?: { [key: string]: Value<"units/s"> };
	modifiers?: string[];
	dumpValves?: string[];
}
export interface KerbalismProfile
{
	name?: string;
	resources?: { [key:string]: KerbalismResourceDef };
	rules?: KerbalismRuleDef[];
	processes?: KerbalismProcessDef[];
}
export interface KerbalismGreenhouseEntry
{
	cropResource?: string;
	foodRatePerSec?: Value<"units/s">;
	natural?: Value<"W/m²">;
	artificial?: Value<"W/m²">;
	active?: boolean;
	issue?: string;
	ecRateMaxPerSec?: Value<"units/s">;
	lampEcDrawPerSec?: Value<"units/s">;
	lightToleranceWm2?: Value<"W/m²">;
	pressureTolerance?: Value<"ratio">;
	radiationToleranceRadPerSec?: Value<"rad/s">;
}
export interface KerbalismLifeSupport
{
	rates?: { [key: string]: Value<"units/s"> };
	habitat?: KerbalismHabitat;
	processes?: KerbalismProcessEntry[];
	ruleEnvModifiers?: { [key: string]: Value<"1"> };
	greenhouses?: KerbalismGreenhouseEntry[];
	asOfUt?: Value<"ut">;
}
export interface KerbalismCrewRule
{
	name?: string;
	value?: Value<"units">;
	degenPerSec?: Value<"units/s">;
	fatalThreshold?: Value<"units">;
}
export interface KerbalismCrewEntry
{
	name?: string;
	trait?: string;
	rules?: KerbalismCrewRule[];
	deathClockUt?: Value<"ut">;
	asOfUt?: Value<"ut">;
}
export interface KerbalismFeatures
{
	reliability?: boolean;
	radiation?: boolean;
	spaceWeather?: boolean;
	shielding?: boolean;
	livingSpace?: boolean;
	comfort?: boolean;
	poisoning?: boolean;
	pressure?: boolean;
	habitat?: boolean;
	supplies?: boolean;
	science?: boolean;
	automation?: boolean;
	deploy?: boolean;
}
export interface KerbalismReliabilityExt
{
	worstMtbfHours?: Value<"h">;
	brokenPartCount?: Value<"count">;
	maintenanceDueCount?: Value<"count">;
}
export interface KerbalismScienceExperimentExt
{
	dataSizeMB?: Value<"MB">;
	sciencePerMB?: Value<"science/MB">;
	kind?: string;
	sampleMass?: Value<"t">;
	analyze?: boolean;
	storageCapacityMB?: Value<"MB">;
	storageUsedMB?: Value<"MB">;
	sampleSlotsTotal?: Value<"count">;
	sampleSlotsUsed?: Value<"count">;
	transmitRateMBps?: Value<"MB/s">;
	transmitting?: boolean;
	sendFlagged?: boolean;
}
export interface KerbalismScienceInstrumentExt
{
	kind?: string;
	issue?: string;
	runningState?: string;
	expStatus?: string;
	dataRateMBps?: Value<"MB/s">;
	prodFactor?: Value<"ratio">;
	remainingSampleMass?: Value<"t">;
	scanning?: boolean;
	powerDisabled?: boolean;
	bodyCoveragePercent?: Value<"%">;
	ecRate?: Value<"units/s">;
}
export interface KerbalismScienceLabExt
{
	analysisRateMBps?: Value<"MB/s">;
	effectiveRateMBps?: Value<"MB/s">;
	status?: string;
}
export interface KerbalismScienceBreakdownExt
{
	scienceRemainingTotal?: Value<"science">;
	percentCollectedTotal?: Value<"ratio">;
	scienceCollectedInFlight?: Value<"science">;
	timesCompleted?: Value<"count">;
}
