//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.

import type {
  KerbalismCrewEntry,
  KerbalismFeatures,
  KerbalismLifeSupport,
  KerbalismProfile,
  KerbalismSpaceWeather,
} from "./contract";

export interface GeneratedTopicPayloadMap {
  "kerbalism.crew": KerbalismCrewEntry[];
  "kerbalism.features": KerbalismFeatures;
  "kerbalism.lifesupport": KerbalismLifeSupport;
  "kerbalism.profile": KerbalismProfile;
  "kerbalism.spaceweather": KerbalismSpaceWeather;
}

export const GENERATED_TOPIC_IDS = [
  "kerbalism.crew",
  "kerbalism.features",
  "kerbalism.lifesupport",
  "kerbalism.profile",
  "kerbalism.spaceweather",
] as const;
