// landing-status.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "comms.delay",
    "dv.stages",
    "dv.summary",
    "system.bodies",
    "vessel.identity",
    "vessel.orbit",
    "vessel.propulsion",
    "vessel.structure",
    "vessel.surface",
    "vessel.target",
  ],
  optionalChannelFamilies: [],
  commands: [],
} as const;
