using System.Collections.Generic;
using System.Linq;

namespace Sitrep.Contract
{
    /// <summary>
    /// One capability in the activation graph <see cref="Broker"/> orders: its id
    /// and the capabilities its selected provider or providers depend on.
    /// </summary>
    /// <category>Host and Kernel</category>
    public sealed class DependencyNode
    {
        /// <summary>The capability id this node represents.</summary>
        public string Id { get; }

        /// <summary>Capabilities this node's selected provider(s) must see active first.</summary>
        public IReadOnlyList<string> Deps { get; }

        /// <summary>A node for capability <paramref name="id"/>.</summary>
        /// <param name="id">The capability id.</param>
        /// <param name="deps">The capability ids that must be active before this one.</param>
        public DependencyNode(string id, IReadOnlyList<string> deps)
        {
            Id = id;
            Deps = deps;
        }
    }

    /// <summary>
    /// Orders capability activation so that every capability a provider depends
    /// on (<see cref="DependencyNode.Deps"/>) is already active when its factory
    /// runs, so <c>ctx.Query(dep)</c> inside the factory resolves.
    ///
    /// <para>It does not select providers. <see cref="Kernel.Resolve"/> selects
    /// first, builds one <see cref="DependencyNode"/> per capability from the
    /// winning providers' dependencies, sorts them here, and then runs the
    /// factories in that order.</para>
    /// <internal>
    /// C# port of mod/sitrep-kernel/src/broker.ts. Semantics must stay identical
    /// to the TS reference; conformance is asserted through the kernel golden
    /// fixture (mod/golden-fixtures/kernel.json, generated by
    /// mod/golden-fixtures/gen/kernel.gen.ts), not re-derived here.
    /// </internal>
    /// </summary>
    /// <category>Host and Kernel</category>
    public static class Broker
    {
        /// <summary>
        /// Sorts the capability dependency graph topologically (Kahn's algorithm)
        /// into an activation order.
        ///
        /// <para>A dependency on a capability that is not in
        /// <paramref name="nodes"/> is not an edge and does not block activation.
        /// A factory that then queries that id gets a "not exactly one active
        /// provider" error from <c>ctx.Query</c>; the sort does not pre-empt
        /// it.</para>
        ///
        /// <para>Deterministic: ties are broken by the order of
        /// <paramref name="nodes"/> (registration order). The ready queue is
        /// seeded in that order, and nodes that become ready later are appended
        /// in the order their dependencies clear.</para>
        /// </summary>
        /// <param name="nodes">One node per capability, in registration order.</param>
        /// <returns>Every capability id in <paramref name="nodes"/>, dependencies first.</returns>
        /// <exception cref="DependencyCycleError">A cycle prevents a full ordering. The error names the cycle.</exception>
        public static List<string> TopoSortActivationOrder(IReadOnlyList<DependencyNode> nodes)
        {
            var knownIds = new HashSet<string>(nodes.Select(n => n.Id));
            var dependents = new Dictionary<string, List<string>>();
            var inDegree = new Dictionary<string, int>();

            foreach (var node in nodes)
            {
                inDegree[node.Id] = 0;
                dependents[node.Id] = new List<string>();
            }

            foreach (var node in nodes)
            {
                foreach (var dep in node.Deps)
                {
                    if (!knownIds.Contains(dep))
                    {
                        // A dependency on a capability that was never registered is not an edge.
                        continue;
                    }
                    dependents[dep].Add(node.Id);
                    inDegree[node.Id] = inDegree[node.Id] + 1;
                }
            }

            var queue = new List<string>();
            foreach (var node in nodes)
            {
                if (inDegree[node.Id] == 0)
                {
                    queue.Add(node.Id);
                }
            }

            var order = new List<string>();
            var head = 0;
            while (head < queue.Count)
            {
                var current = queue[head];
                head += 1;
                order.Add(current);

                foreach (var dependent in dependents[current])
                {
                    var remaining = inDegree[dependent] - 1;
                    inDegree[dependent] = remaining;
                    if (remaining == 0)
                    {
                        queue.Add(dependent);
                    }
                }
            }

            if (order.Count != nodes.Count)
            {
                var orderedSet = new HashSet<string>(order);
                var remainingIds = nodes
                    .Select(n => n.Id)
                    .Where(id => !orderedSet.Contains(id))
                    .ToList();
                throw new DependencyCycleError(FindCycle(remainingIds, nodes, knownIds));
            }

            return order;
        }

        /// <summary>
        /// DFS cycle finder, scoped to the nodes that Kahn's algorithm
        /// couldn't order (i.e. everything left over is part of, or feeds
        /// into, at least one cycle). Walks each node's deps edges directly
        /// (the "depends on" direction) using a visiting/visited marker, so
        /// the returned path is an actual dependency chain that loops back on
        /// itself: useful in the thrown error message.
        /// </summary>
        private static List<string> FindCycle(
            List<string> remainingIds,
            IReadOnlyList<DependencyNode> nodes,
            HashSet<string> knownIds)
        {
            var depsById = nodes.ToDictionary(n => n.Id, n => n.Deps);
            var remainingSet = new HashSet<string>(remainingIds);
            var visiting = new HashSet<string>();
            var visited = new HashSet<string>();
            var stack = new List<string>();

            List<string>? Dfs(string id)
            {
                visiting.Add(id);
                stack.Add(id);

                foreach (var dep in depsById[id])
                {
                    if (!knownIds.Contains(dep) || !remainingSet.Contains(dep))
                    {
                        continue;
                    }
                    if (visiting.Contains(dep))
                    {
                        var startIndex = stack.IndexOf(dep);
                        var cycle = stack.Skip(startIndex).ToList();
                        cycle.Add(dep);
                        return cycle;
                    }
                    if (!visited.Contains(dep))
                    {
                        var found = Dfs(dep);
                        if (found != null)
                        {
                            return found;
                        }
                    }
                }

                visiting.Remove(id);
                visited.Add(id);
                stack.RemoveAt(stack.Count - 1);
                return null;
            }

            foreach (var id in remainingIds)
            {
                if (visited.Contains(id))
                {
                    continue;
                }
                var found = Dfs(id);
                if (found != null)
                {
                    return found;
                }
            }

            // Unreachable while Kahn's algorithm only leaves nodes on or feeding a cycle; name everything left over.
            return remainingIds;
        }
    }
}
