// astronaut-complex.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [],
  optionalChannelFamilies: [],
  commands: ["career.crew.fire", "career.crew.hire"],
} as const;
