#!/usr/bin/env tsx
/**
 * Render a craft losing contact, coming due, going overdue and finally being
 * declared lost, as an mp4.
 *
 * The states are cheap to screenshot one at a time but the thing worth seeing
 * is the TRANSITION: a countdown running down to nothing, the marker turning
 * amber as it passes its predicted reacquisition, and the name being struck
 * through when the deadline expires. A still cannot show that the amber state
 * is reached by waiting rather than by an event.
 *
 * Pipeline mirrors `render-navball-gif.ts`: synthesise one fixture per frame
 * into a temp dir under `src/` (the harness resolves `fixturesPath` relative to
 * it), render each through the existing playwright harness, stitch with ffmpeg.
 *
 * Most frames hold ONE contact row and only advance the view clock, because
 * that is exactly how the real thing behaves: `contactPhase` compares now
 * against the predicted UT, so expected becomes overdue with no new data
 * arriving at all. Only the final segment swaps in a row the tracker has moved
 * to `Lost`, which IS a wire change.
 *
 * Output: `local_docs/renders/system-view-contact-timeline.mp4`
 * Run via `pnpm --filter @ksp-gonogo/components render-contact-timeline`.
 */
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { renderWidget } from "./widgetRenderHarness";

const execFileAsync = promisify(execFile);

const HERE = dirname(fileURLToPath(import.meta.url));
const COMPONENTS_SRC = resolve(HERE, "../src");
const LOCAL_DOCS = resolve(HERE, "../../../local_docs");
const BASE_FIXTURE = resolve(
  COMPONENTS_SRC,
  "SystemView/__fixtures__/kerbin-orbit-no-target.json",
);

const FPS = 10;
/** Predicted reacquisition, in the fixture's own UT frame. */
const PREDICTED_UT = 600;
/** Deadline = prediction + the 0.25T grace the policy applies. */
const DEADLINE_UT = 1100;

interface Frame {
  ut: number;
  contact: Record<string, unknown> | null;
}

/**
 * nominal → silent-with-prediction (counting down) → overdue (counting up) →
 * lost. Held frames at each threshold so the mp4 does not blink past the moment
 * the state actually changes.
 */
function timeline(): Frame[] {
  const silent = {
    connected: false,
    state: "Silent",
    lastContactUt: -20,
    silenceSinceUt: -19,
    deadlineUt: DEADLINE_UT,
    deadlineBasis: "predicted-reacquisition",
    predictedReacquisitionUt: PREDICTED_UT,
  };
  const lost = { ...silent, state: "Lost" };
  const frames: Frame[] = [];

  // In contact.
  for (let i = 0; i < 8; i++) {
    frames.push({
      ut: -100 + i * 10,
      contact: {
        connected: true,
        state: "Nominal",
        lastContactUt: -100 + i * 10,
        silenceSinceUt: null,
        deadlineUt: null,
        deadlineBasis: null,
        predictedReacquisitionUt: null,
      },
    });
  }
  // Dark, counting down to the predicted return.
  for (let ut = 0; ut < PREDICTED_UT; ut += 40)
    frames.push({ ut, contact: silent });
  // Past it, and still nothing: overdue.
  for (let ut = PREDICTED_UT; ut < DEADLINE_UT; ut += 40)
    frames.push({ ut, contact: silent });
  // Deadline expired.
  for (let i = 0; i < 14; i++)
    frames.push({ ut: DEADLINE_UT + i * 20, contact: lost });
  return frames;
}

async function main(): Promise<void> {
  const base = JSON.parse(await readFile(BASE_FIXTURE, "utf8")) as {
    _meta?: unknown;
    _stream: {
      carriedChannels: string[];
      pinnedUt: number;
      emits: { channel: string; value: unknown }[];
    };
  };

  const frames = timeline();
  const tmp = await mkdtemp(join(COMPONENTS_SRC, "contact-timeline-"));
  const fixturesRel = `${tmp.slice(COMPONENTS_SRC.length + 1)}`;
  const outDir = resolve(LOCAL_DOCS, "renders/contact-timeline-frames");
  await mkdir(outDir, { recursive: true });

  try {
    for (const [i, frame] of frames.entries()) {
      const fx = JSON.parse(JSON.stringify(base)) as typeof base;
      fx._meta = { notes: "generated by render-contact-timeline" };
      fx._stream.pinnedUt = frame.ut;
      // Dynamic namespaces are carried by PREFIX; the concrete topic never
      // matches, so nothing subscribes and the emit is silently dropped.
      fx._stream.carriedChannels = [...fx._stream.carriedChannels, "fleet."];
      if (frame.contact) {
        fx._stream.emits.push({
          channel: "fleet.Tester.contact",
          value: frame.contact,
        });
      }
      await writeFile(
        join(tmp, `${String(i).padStart(4, "0")}.json`),
        JSON.stringify(fx, null, 2),
      );
    }

    await renderWidget(
      {
        widgetId: "system-view",
        fixturesPath: fixturesRel,
        outPath: "renders/contact-timeline-frames",
        modes: [{ name: "f", w: 10, h: 12 }],
      },
      { engine: "chromium" },
    );

    const out = resolve(LOCAL_DOCS, "renders/system-view-contact-timeline.mp4");
    await execFileAsync("ffmpeg", [
      "-y",
      "-framerate",
      String(FPS),
      "-pattern_type",
      "glob",
      "-i",
      join(outDir, "*--f.png"),
      "-c:v",
      "libx264",
      "-pix_fmt",
      "yuv420p",
      // Even dimensions, required by yuv420p.
      "-vf",
      "scale=trunc(iw/2)*2:trunc(ih/2)*2",
      out,
    ]);
    console.log(`Wrote ${out} (${frames.length} frames at ${FPS}fps)`);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
