// ship-map.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [],
  optionalChannelFamilies: ["vessel.partActions.<flightId>"],
  commands: ["vessel.invokePartAction"],
} as const;
