// fuel-status.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "dv.currentStageResource",
    "dv.currentStageResourceMax",
    "dv.stages",
    "dv.summary",
    "vessel.propulsion",
    "vessel.structure",
  ],
  optionalChannelFamilies: [],
  commands: [],
} as const;
