// transfer-window.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["dv.stages", "vessel.structure"],
  optionalChannelFamilies: [],
  commands: ["system.bodies.statesAt"],
} as const;
