//     This code was generated by scripts/gen-unit-kinds.mjs.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// A unit's KIND is a model fact, owned by mod/sitrep-sdk's UNIT_DEFINITIONS.
// ui-kit reads it from here rather than keeping its own copy, because the two
// copies drifted: seven units disagreed on what their kind was called.
//
// Generated rather than imported so that packages/ui-kit keeps its zero
// runtime dependencies. A token the contract declares but the model has no
// unit for is a non-quantity, and its kind is the token itself.

export const GENERATED_UNIT_KINDS: Readonly<Record<string, string>> = {
  "%": "percent",
  "1": "dimensionless",
  "Gm": "length",
  "J": "energy",
  "J/s": "power",
  "K": "temperature",
  "Mit": "scienceData",
  "Mm": "length",
  "N": "force",
  "N·m": "torque",
  "Pa": "pressure",
  "Tm": "length",
  "W": "power",
  "W/m²": "irradiance",
  "bit": "data",
  "bit/s": "dataRate",
  "count": "count",
  "d": "time",
  "dB": "level",
  "enum": "enum",
  "flag": "flag",
  "funds": "funds",
  "g": "acceleration",
  "h": "time",
  "id": "id",
  "irl:d": "irlTime",
  "irl:h": "irlTime",
  "irl:min": "irlTime",
  "irl:s": "irlTime",
  "kN": "force",
  "kPa": "pressure",
  "kW": "power",
  "kg": "mass",
  "kg/m³": "density",
  "km": "length",
  "km/h": "speed",
  "km/s": "speed",
  "m": "length",
  "m/s": "speed",
  "m/s²": "acceleration",
  "min": "time",
  "m²": "area",
  "m³": "volume",
  "m³/s²": "gravParameter",
  "n/a": "n/a",
  "rad": "planeAngle",
  "rad/s": "doseRate",
  "ratio": "ratio",
  "rep": "reputation",
  "rpm": "angularSpeed",
  "s": "time",
  "science": "science",
  "science/day": "scienceRate",
  "t": "mass",
  "text": "text",
  "units": "resourceUnits",
  "units/s": "resourceFlow",
  "°": "planeAngle",
};
