//     This code was generated by scripts/gen-unit-kinds.mjs.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// A unit's KIND is a model fact, owned by mod/sitrep-sdk's UNIT_DEFINITIONS.
// ui-kit reads it from here rather than keeping its own copy, because the two
// copies drifted: seven units disagreed on what their kind was called.
//
// Generated rather than imported so that packages/ui-kit keeps its zero
// runtime dependencies. A token the contract declares but the model has no
// unit for is a non-quantity, and its kind is the token itself.
//
// The ratio converts to the kind's BASE unit, which is what lets the format
// prop re-express a value in any unit of the same kind without ui-kit
// keeping conversion factors of its own.

// The RUNTIME copy of what the SDK's UnitDeclarations states for first-party
// units. The types read the declarations, never this table, so an Uplink's
// declared unit is checked exactly as one of these is; unit-kinds.test-d.ts
// holds the two to one another. `as const` keeps that comparison exact.
export const GENERATED_UNIT_KINDS = {
  "%": { kind: "percent", ratio: 0.01 },
  "1": { kind: "dimensionless", ratio: 1 },
  "Eg": { kind: "mass", ratio: 1000000000000000, ladder: "mass" },
  "Gm": { kind: "length", ratio: 1000000000, ladder: "length" },
  "J": { kind: "energy", ratio: 1 },
  "J/s": { kind: "power", ratio: 1, ladder: "power" },
  "K": { kind: "temperature", ratio: 1 },
  "MN": { kind: "force", ratio: 1000000, ladder: "force" },
  "Mit": { kind: "scienceData", ratio: 1 },
  "Mm": { kind: "length", ratio: 1000000, ladder: "length" },
  "N": { kind: "force", ratio: 1, ladder: "force" },
  "N·m": { kind: "torque", ratio: 1 },
  "Pa": { kind: "pressure", ratio: 1, ladder: "pressure" },
  "Pg": { kind: "mass", ratio: 1000000000000, ladder: "mass" },
  "Tg": { kind: "mass", ratio: 1000000000, ladder: "mass" },
  "Tm": { kind: "length", ratio: 1000000000000, ladder: "length" },
  "W": { kind: "power", ratio: 1, ladder: "power" },
  "W/m²": { kind: "irradiance", ratio: 1 },
  "Yg": { kind: "mass", ratio: 1e+21, ladder: "mass" },
  "Zg": { kind: "mass", ratio: 1000000000000000000, ladder: "mass" },
  "bit": { kind: "data", ratio: 1, ladder: "data" },
  "bit/s": { kind: "dataRate", ratio: 1, ladder: "dataRate" },
  "count": { kind: "count", ratio: 1 },
  "d": { kind: "time", ratio: 21600 },
  "dB": { kind: "level", ratio: 1 },
  "enum": { kind: "enum", ratio: 1 },
  "f/day": { kind: "fundsRate", ratio: 0.000046296296296296294 },
  "flag": { kind: "flag", ratio: 1 },
  "funds": { kind: "funds", ratio: 1 },
  "g": { kind: "acceleration", ratio: 9.80665 },
  "h": { kind: "time", ratio: 3600 },
  "id": { kind: "id", ratio: 1 },
  "irl:d": { kind: "irlTime", ratio: 86400 },
  "irl:h": { kind: "irlTime", ratio: 3600 },
  "irl:min": { kind: "irlTime", ratio: 60 },
  "irl:s": { kind: "irlTime", ratio: 1 },
  "isp": { kind: "specificImpulse", ratio: 1 },
  "kN": { kind: "force", ratio: 1000, ladder: "force" },
  "kPa": { kind: "pressure", ratio: 1000, ladder: "pressure" },
  "kW": { kind: "power", ratio: 1000, ladder: "power" },
  "kg": { kind: "mass", ratio: 1, ladder: "mass" },
  "kg/m³": { kind: "density", ratio: 1 },
  "kg/s": { kind: "massFlow", ratio: 1 },
  "km": { kind: "length", ratio: 1000, ladder: "length" },
  "km/h": { kind: "speed", ratio: 0.2777777777777778 },
  "km/s": { kind: "speed", ratio: 1000 },
  "kt": { kind: "mass", ratio: 1000000, ladder: "mass" },
  "m": { kind: "length", ratio: 1, ladder: "length" },
  "m/s": { kind: "speed", ratio: 1 },
  "m/s²": { kind: "acceleration", ratio: 1 },
  "mPa": { kind: "pressure", ratio: 0.001, ladder: "pressure" },
  "min": { kind: "time", ratio: 60 },
  "m²": { kind: "area", ratio: 1 },
  "m³": { kind: "volume", ratio: 1 },
  "m³/s²": { kind: "gravParameter", ratio: 1 },
  "n/a": { kind: "n/a", ratio: 1 },
  "rad": { kind: "planeAngle", ratio: 1 },
  "rad/h": { kind: "doseRate", ratio: 0.0002777777777777778, ladder: "doseRate" },
  "rad/s": { kind: "doseRate", ratio: 1, ladder: "doseRate" },
  "ratio": { kind: "ratio", ratio: 1 },
  "rep": { kind: "reputation", ratio: 1 },
  "rep/day": { kind: "reputationRate", ratio: 0.000046296296296296294 },
  "rpm": { kind: "angularSpeed", ratio: 0.10471975511965977 },
  "s": { kind: "time", ratio: 1 },
  "science": { kind: "science", ratio: 1 },
  "science/day": { kind: "scienceRate", ratio: 0.000046296296296296294 },
  "t": { kind: "mass", ratio: 1000, ladder: "mass" },
  "text": { kind: "text", ratio: 1 },
  "units": { kind: "resourceUnits", ratio: 1 },
  "units/s": { kind: "resourceFlow", ratio: 1 },
  "ut": { kind: "universalTime", ratio: 1 },
  "y": { kind: "time", ratio: 9201600 },
  "°": { kind: "planeAngle", ratio: 0.017453292519943295 },
} as const;
