import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { build, type Plugin } from "esbuild";
import {
  type FontFace,
  jetbrainsMonoFace,
  themeTokensCss,
  type UplinkPackage,
} from "./context";

const require = createRequire(import.meta.url);

/**
 * The page a scene is rendered in, built once per run.
 *
 * The browser entry is GENERATED rather than owned by each Uplink, and that is
 * load-bearing rather than tidy. The sdk's author surface is host-injected shims,
 * so a widget's module-load `registerComponent` throws against an uninstalled
 * host; static ES imports are hoisted above every statement, so an entry that
 * installs the host and then side-effect-imports the client is correct only by
 * import ORDER, which an import sorter is free to change. Generating the entry
 * moves that footgun out of every author's file into one place with no lines for
 * a sorter to move.
 */

/** The one `<style id="probe-theme">` slot and the one script slot. */
const PAGE_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Uplink render probe</title>
    <style id="probe-theme"></style>
    <style>
      html, body {
        margin: 0;
        padding: 0;
        background: var(--color-surface-app);
        color: var(--color-text-primary);
        font-family: var(--font-family-mono);
      }
      body {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
      }
      #root { box-sizing: border-box; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script id="probe-entry" type="module"></script>
  </body>
</html>
`;

/**
 * A widget's own bare `import "some.css"` has to land in the page as a `<style>`
 * tag. `loader: "text"` alone makes an inert string module that esbuild then
 * tree-shakes away whenever the importing package declares `sideEffects: false`,
 * producing an ignored-bare-import warning and a fully unstyled render. Resolution
 * goes through Node's resolver rather than `pluginBuild.resolve()`, which
 * re-enters this same `onResolve` filter and hung the esbuild service.
 */
const cssSideEffectPlugin: Plugin = {
  name: "css-side-effect",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /\.css$/ }, (args) => ({
      path: require.resolve(args.path, { paths: [args.resolveDir] }),
      sideEffects: true,
    }));
    pluginBuild.onLoad({ filter: /\.css$/ }, async (args) => {
      const css = await readFile(args.path, "utf8");
      return {
        loader: "js",
        contents:
          'const __style = document.createElement("style");\n' +
          `__style.textContent = ${JSON.stringify(css)};\n` +
          "document.head.appendChild(__style);",
      };
    });
  },
};

function posix(path: string): string {
  return path.split("\\").join("/");
}

/** The generated browser entry. Awaited imports, never static ones. */
export function generateEntry(pkg: UplinkPackage): string {
  const lines = [
    "// GENERATED by @ksp-gonogo/ui-kit/render. Never committed, never edited.",
    'import { installRenderProbe } from "@ksp-gonogo/ui-kit/render-probe";',
    "",
    "// Before anything the Uplink registers: the host has to exist first, and a",
    "// static import of the client would be hoisted above this line.",
    "await installRenderProbe();",
    `await import("${posix(pkg.entry)}");`,
  ];
  if (pkg.setup) {
    lines.push(
      "// The author's own browser-side glue, when they wrote any.",
      `await import("${posix(pkg.setup)}");`,
    );
  }
  return `${lines.join("\n")}\n`;
}

export interface ProbePage {
  file: string;
  font: FontFace;
}

export async function buildProbePage(pkg: UplinkPackage): Promise<ProbePage> {
  const result = await build({
    stdin: {
      contents: generateEntry(pkg),
      resolveDir: pkg.dir,
      sourcefile: "gonogo-render-entry.tsx",
      loader: "tsx",
    },
    bundle: true,
    format: "esm",
    target: "es2022",
    platform: "browser",
    jsx: "automatic",
    write: false,
    sourcemap: "inline",
    define: { "process.env.NODE_ENV": '"production"' },
    plugins: [cssSideEffectPlugin],
    absWorkingDir: pkg.dir,
  });
  const bundle = result.outputFiles[0].text;
  const font = jetbrainsMonoFace();
  // Function-form replacements throughout: a React bundle contains `$&`, and
  // String.replace's string form reads it as a backreference and corrupts it.
  const escaped = bundle.replace(/<\/script/gi, "<\\/script");
  const html = PAGE_TEMPLATE.replace(
    '<style id="probe-theme"></style>',
    () => `<style id="probe-theme">${font.css}\n${themeTokensCss()}</style>`,
  ).replace(
    '<script id="probe-entry" type="module"></script>',
    () => `<script id="probe-entry" type="module">${escaped}</script>`,
  );
  const file = join(tmpdir(), `gonogo-uplink-probe-${process.pid}.html`);
  await writeFile(file, html, "utf8");
  return { file, font };
}
