// action-group.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: ["comms.link", "time.warp", "vessel.structure"],
  optionalChannelFamilies: [],
  commands: [
    "vessel.control.setAbort",
    "vessel.control.setActionGroup",
    "vessel.control.setBrakes",
    "vessel.control.setGear",
    "vessel.control.setLights",
    "vessel.control.setRcs",
    "vessel.control.setSas",
    "vessel.control.stage",
  ],
} as const;
