// system-view.declarations.g.ts (generated by uplink-tools check --fix, do not edit)
export default {
  optionalChannels: [
    "comms.network",
    "system.frame",
    "system.uplink.pending",
    "vessel.identity",
    "vessel.orbit",
    "vessel.target",
  ],
  optionalChannelFamilies: ["silence.<guid>.state"],
  commands: [],
} as const;
